! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Global Data Module File
! 
! Generated by KPP-2.2.3 symbolic chemistry Kinetics PreProcessor
!       (http://www.cs.vt.edu/~asandu/Software/KPP)
! KPP is distributed under GPL, the general public licence
!       (http://www.gnu.org/copyleft/gpl.html)
! (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa
! (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech
!     With important contributions from:
!        M. Damian, Villanova University, USA
!        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany
! 
! File                 : CRI_5VOC_Global.f90
! Time                 : Tue Aug 27 15:48:09 2013
! Working directory    : /home/hes134/kpp-2.2.3/CRI_5VOC
! Equation file        : CRI_5VOC.kpp
! Output root filename : CRI_5VOC
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



MODULE CRI_5VOC_Global

  USE CRI_5VOC_Parameters, ONLY: dp, NSPEC, NVAR, NFIX, NREACT
  PUBLIC
  SAVE


! Declaration of global variables

! C - Concentration of all species
  REAL(kind=dp) :: C(NSPEC)
! VAR - Concentrations of variable species (global)
  REAL(kind=dp) :: VAR(NVAR)
! FIX - Concentrations of fixed species (global)
  REAL(kind=dp) :: FIX(NFIX)
! VAR, FIX are chunks of array C
      EQUIVALENCE( C(1),VAR(1) )
      EQUIVALENCE( C(132),FIX(1) )
! RCONST - Rate constants (global)
  REAL(kind=dp) :: RCONST(NREACT)
! TIME - Current integration time
  REAL(kind=dp) :: TIME
! SUN - Sunlight intensity between [0,1]
  REAL(kind=dp) :: SUN
! TEMP - Temperature
  REAL(kind=dp) :: TEMP
! RTOLS - (scalar) Relative tolerance
  REAL(kind=dp) :: RTOLS
! TSTART - Integration start time
  REAL(kind=dp) :: TSTART
! TEND - Integration end time
  REAL(kind=dp) :: TEND
! DT - Integration step
  REAL(kind=dp) :: DT
! ATOL - Absolute tolerance
  REAL(kind=dp) :: ATOL(NVAR)
! RTOL - Relative tolerance
  REAL(kind=dp) :: RTOL(NVAR)
! STEPMIN - Lower bound for integration step
  REAL(kind=dp) :: STEPMIN
! STEPMAX - Upper bound for integration step
  REAL(kind=dp) :: STEPMAX
! CFACTOR - Conversion factor for concentration units
  REAL(kind=dp) :: CFACTOR
! DDMTYPE - DDM sensitivity w.r.t.: 0=init.val., 1=params
  INTEGER :: DDMTYPE

! INLINED global variable declarations
 
  INTEGER, parameter :: NUSRGL = 66
  INTEGER, parameter :: NUSRNAMES = 6
  REAL(kind=dp) :: USRGL(NUSRGL)
  REAL(kind=dp) :: M, N2, O2, RO2, H2O 
  REAL(kind=dp), dimension(61) :: J
    EQUIVALENCE(USRGL(1), M)
    EQUIVALENCE(USRGL(2), N2)
    EQUIVALENCE(USRGL(3), O2)
    EQUIVALENCE(USRGL(4), RO2)
    EQUIVALENCE(USRGL(5), H2O)
    EQUIVALENCE(USRGL(6), J(1))
  INTEGER, PARAMETER, DIMENSION(NUSRNAMES) :: USRGL_LEN = (/1,1,1,1,1,61/)
  CHARACTER(LEN=15), PARAMETER, DIMENSION(NUSRNAMES) :: USRGL_NAMES = (/ &
    'M              ', &
    'N2             ', &
    'O2             ', & 
    'RO2            ', &
    'H2O            ', & 
    'J              ' /)

! INLINED global variable declarations


END MODULE CRI_5VOC_Global

