! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Main Program File
! 
! Generated by KPP-2.2.3 symbolic chemistry Kinetics PreProcessor
!       (http://www.cs.vt.edu/~asandu/Software/KPP)
! KPP is distributed under GPL, the general public licence
!       (http://www.gnu.org/copyleft/gpl.html)
! (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa
! (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech
!     With important contributions from:
!        M. Damian, Villanova University, USA
!        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany
! 
! File                 : CRI_5VOC_Main.f90
! Time                 : Tue Aug 27 15:48:09 2013
! Working directory    : /home/hes134/kpp-2.2.3/CRI_5VOC
! Equation file        : CRI_5VOC.kpp
! Output root filename : CRI_5VOC
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! MAIN - Main program - driver routine
!   Arguments :
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

SUBROUTINE R_GetNumGlobals(R_nusrgl, R_nusrnames)
  USE CRI_5VOC_Global, only: NUSRGL, NUSRNAMES
  implicit none
  integer :: R_nusrgl, R_nusrnames
  R_nusrgl = NUSRGL
  R_nusrnames = NUSRNAMES
END SUBROUTINE 


SUBROUTINE R_GetGlobalsName(R_usrgl_name, R_usrgl_len, idx)
  USE CRI_5VOC_Global, only: NUSRNAMES, USRGL_NAMES, USRGL_LEN
  implicit none

  CHARACTER(LEN=255) :: R_usrgl_name
  INTEGER  :: idx, R_usrgl_len
! TODO test index

  R_usrgl_name = USRGL_NAMES(idx)
  R_usrgl_len = USRGL_LEN(idx)

END SUBROUTINE

SUBROUTINE R_GetSelectedGlobals(nn, idx, R_usrgl)
  USE CRI_5VOC_Global, only: NUSRGL, USRGL
  USE CRI_5VOC_Precision, only: dp
  implicit none

  integer :: ii, nn, idx(nn)
  REAL(kind=dp) :: R_usrgl(nn)

! TODO Check values of idx for out of range
  do ii=1, nn
    R_usrgl(ii) = USRGL(idx(ii))
  end do

END SUBROUTINE 


SUBROUTINE R_SetSelectedGlobals(nn, idx, R_usrgl)
  USE CRI_5VOC_Global, only: NUSRGL, USRGL
  USE CRI_5VOC_Precision, only: dp
  implicit none

  integer :: ii, nn, idx(nn)
  REAL(kind=dp) :: R_usrgl(nn)

  do ii=1, nn
    USRGL(idx(ii)) = R_usrgl(ii) 
  end do
END SUBROUTINE 

SUBROUTINE R_GetAllGlobals(R_usrgl)
  USE CRI_5VOC_Global, only: USRGL, NUSRGL
  USE CRI_5VOC_Precision, only: dp
  implicit none
  integer :: ii
  REAL(kind=dp) :: R_usrgl(NUSRGL)

  do ii=1, NUSRGL
    R_usrgl(ii) = USRGL(ii)
  end do
END SUBROUTINE 


SUBROUTINE R_SetAllGlobals(R_usrgl)
  USE CRI_5VOC_Global, only: USRGL, NUSRGL
  USE CRI_5VOC_Precision, only: dp
  implicit none
  integer :: ii
  REAL(kind=dp) :: R_usrgl(NUSRGL)

  do ii=1, NUSRGL
    USRGL(ii) = R_usrgl(ii) 
  end do
END SUBROUTINE 

SUBROUTINE R_SetTEMP(R_tt)
  USE CRI_5VOC_Model
  implicit none

  REAL(kind=dp) :: R_tt

  TEMP = R_tt
END SUBROUTINE R_SetTEMP


SUBROUTINE R_Initialize(initval, R_dt, R_tt)
  USE CRI_5VOC_Model
  implicit none

  REAL(kind=dp) :: initval(NVAR)
  REAL(kind=dp) :: R_dt, R_tt
  integer :: ii

  STEPMIN = 0.0d0
  STEPMAX = 0.0d0
  CFACTOR = 1.0d0
  TEMP = R_tt
  DT = R_dt

  do ii=1,NVAR
    RTOL(ii) = 1.0d-4
    ATOL(ii) = 1.0d-3
  end do

  do ii=1,NSPEC
    C(ii) = initval(ii)
  end do 

END SUBROUTINE R_Initialize

SUBROUTINE R_GetSelectedConc(nn, idx, conc)
  USE CRI_5VOC_Global, only: C
  USE CRI_5VOC_Precision, only: dp
  implicit none

  integer :: ii, nn, idx(nn)
  REAL(kind=dp) :: conc(nn)

  do ii=1, nn
    conc(ii) = C(idx(ii))
  end do
END SUBROUTINE 


SUBROUTINE R_SetSelectedConc(nn, idx, conc)
  USE CRI_5VOC_Global, only: C
  USE CRI_5VOC_Precision, only: dp
  implicit none

  integer :: ii, nn, idx(nn)
  REAL(kind=dp) :: conc(nn)

  do ii=1, nn
    C(idx(ii)) = conc(ii) 
  end do
END SUBROUTINE 

SUBROUTINE R_GetAllConc(conc)
  USE CRI_5VOC_Global, only: NSPEC, C
  USE CRI_5VOC_Precision, only: dp
  implicit none
  integer :: ii
  REAL(kind=dp) :: conc(NSPEC)

  do ii=1, NSPEC
    conc(ii) = C(ii)
  end do
END SUBROUTINE 


SUBROUTINE R_SetAllConc(conc)
  USE CRI_5VOC_Global, only: NSPEC, C
  USE CRI_5VOC_Precision, only: dp
  implicit none
  integer :: ii
  REAL(kind=dp) :: conc(NSPEC)

  do ii=1, NSPEC
    C(ii) = conc(ii) 
  end do
END SUBROUTINE 

SUBROUTINE R_GetAllVar(conc)
  USE CRI_5VOC_Global, only: NVAR, VAR
  USE CRI_5VOC_Precision, only: dp
  implicit none
  REAL(kind=dp) :: conc(NVAR)
  integer :: ii

  do ii=1, NVAR
    conc(ii) = VAR(ii)
  end do
END SUBROUTINE 


SUBROUTINE R_SetAllVar(conc)
  USE CRI_5VOC_Global, only: NVAR, VAR
  USE CRI_5VOC_Precision, only: dp
  implicit none
  REAL(kind=dp) :: conc(NVAR)
  integer :: ii

  do ii=1, NVAR
    VAR(ii) = conc(ii) 
  end do
END SUBROUTINE 


SUBROUTINE R_GetNumSpec(numspec)
  USE CRI_5VOC_Global, only: NSPEC
  implicit none
  integer :: numspec
  numspec = NSPEC
END SUBROUTINE 


SUBROUTINE R_GetNumVar(numvar)
  USE CRI_5VOC_Global, only: NVAR
  implicit none
  integer :: numvar
  numvar = NVAR
END SUBROUTINE 


SUBROUTINE R_GetSpeciesName(spec, idx)
  USE CRI_5VOC_Global, only: NSPEC
  USE CRI_5VOC_Monitor, only: SPC_NAMES
  implicit none

  CHARACTER(LEN=255) :: spec
  INTEGER  :: idx

  spec = SPC_NAMES(idx)

END SUBROUTINE


SUBROUTINE R_Integrate(T, curval)
  USE CRI_5VOC_Model
  implicit none

  REAL(kind=dp) :: RSTATE(20)
  REAL(kind=dp) :: curval(NSPEC)
  REAL(kind=dp) :: T
  integer :: ii

  TIME = T

  CALL Update_SUN()
  CALL Update_RCONST()

  CALL INTEGRATE( TIN = T, TOUT = T+DT, RSTATUS_U = RSTATE, &
    ICNTRL_U = (/ 0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0 /) )

  T = RSTATE(1)

  do ii=1,NSPEC
    curval(ii) = C(ii)
  enddo

END SUBROUTINE R_Integrate
! End of MAIN function
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


