! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! The Reaction Rates File
! 
! Generated by KPP-2.2.3 symbolic chemistry Kinetics PreProcessor
!       (http://www.cs.vt.edu/~asandu/Software/KPP)
! KPP is distributed under GPL, the general public licence
!       (http://www.gnu.org/copyleft/gpl.html)
! (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa
! (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech
!     With important contributions from:
!        M. Damian, Villanova University, USA
!        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany
! 
! File                 : CRI_5VOC_Rates.f90
! Time                 : Tue Aug 27 15:48:09 2013
! Working directory    : /home/hes134/kpp-2.2.3/CRI_5VOC
! Equation file        : CRI_5VOC.kpp
! Output root filename : CRI_5VOC
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



MODULE CRI_5VOC_Rates

  USE CRI_5VOC_Parameters
  USE CRI_5VOC_Global
  IMPLICIT NONE

CONTAINS



! Begin Rate Law Functions from KPP_HOME/util/UserRateLaws

!~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!  User-defined Rate Law functions
!  Note: the default argument type for rate laws, as read from the equations file, is single precision
!        but all the internal calculations are performed in double precision
!~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

!~~~>  Arrhenius
   REAL(kind=dp) FUNCTION ARR( A0,B0,C0 )
      REAL A0,B0,C0      
      ARR =  DBLE(A0) * EXP(-DBLE(B0)/TEMP) * (TEMP/300.0_dp)**DBLE(C0)
   END FUNCTION ARR        

!~~~> Simplified Arrhenius, with two arguments
!~~~> Note: The argument B0 has a changed sign when compared to ARR
   REAL(kind=dp) FUNCTION ARR2( A0,B0 )
      REAL A0,B0           
      ARR2 =  DBLE(A0) * EXP( DBLE(B0)/TEMP )              
   END FUNCTION ARR2          

   REAL(kind=dp) FUNCTION EP2(A0,C0,A2,C2,A3,C3)
      REAL A0,C0,A2,C2,A3,C3
      REAL(kind=dp) K0,K2,K3            
      K0 = DBLE(A0) * EXP(-DBLE(C0)/TEMP)
      K2 = DBLE(A2) * EXP(-DBLE(C2)/TEMP)
      K3 = DBLE(A3) * EXP(-DBLE(C3)/TEMP)
      K3 = K3*CFACTOR*1.0E6_dp
      EP2 = K0 + K3/(1.0_dp+K3/K2 )
   END FUNCTION EP2

   REAL(kind=dp) FUNCTION EP3(A1,C1,A2,C2) 
      REAL A1, C1, A2, C2
      REAL(kind=dp) K1, K2      
      K1 = DBLE(A1) * EXP(-DBLE(C1)/TEMP)
      K2 = DBLE(A2) * EXP(-DBLE(C2)/TEMP)
      EP3 = K1 + K2*(1.0E6_dp*CFACTOR)
   END FUNCTION EP3 

   REAL(kind=dp) FUNCTION FALL ( A0,B0,C0,A1,B1,C1,CF)
      REAL A0,B0,C0,A1,B1,C1,CF
      REAL(kind=dp) K0, K1     
      K0 = DBLE(A0) * EXP(-DBLE(B0)/TEMP)* (TEMP/300.0_dp)**DBLE(C0)
      K1 = DBLE(A1) * EXP(-DBLE(B1)/TEMP)* (TEMP/300.0_dp)**DBLE(C1)
      K0 = K0*CFACTOR*1.0E6_dp
      K1 = K0/K1
      FALL = (K0/(1.0_dp+K1))*   &
           DBLE(CF)**(1.0_dp/(1.0_dp+(LOG10(K1))**2))
   END FUNCTION FALL

  !---------------------------------------------------------------------------

  ELEMENTAL REAL(kind=dp) FUNCTION k_3rd(temp,cair,k0_300K,n,kinf_300K,m,fc)

    INTRINSIC LOG10

    REAL(kind=dp), INTENT(IN) :: temp      ! temperature [K]
    REAL(kind=dp), INTENT(IN) :: cair      ! air concentration [molecules/cm3]
    REAL, INTENT(IN) :: k0_300K   ! low pressure limit at 300 K
    REAL, INTENT(IN) :: n         ! exponent for low pressure limit
    REAL, INTENT(IN) :: kinf_300K ! high pressure limit at 300 K
    REAL, INTENT(IN) :: m         ! exponent for high pressure limit
    REAL, INTENT(IN) :: fc        ! broadening factor (usually fc=0.6)
    REAL(kind=dp) :: zt_help, k0_T, kinf_T, k_ratio

    zt_help = 300._dp/temp
    k0_T    = k0_300K   * zt_help**(n) * cair ! k_0   at current T
    kinf_T  = kinf_300K * zt_help**(m)        ! k_inf at current T
    k_ratio = k0_T/kinf_T
    k_3rd   = k0_T/(1._dp+k_ratio)*fc**(1._dp/(1._dp+LOG10(k_ratio)**2))

  END FUNCTION k_3rd

  !---------------------------------------------------------------------------

  ELEMENTAL REAL(kind=dp) FUNCTION k_arr (k_298,tdep,temp)
    ! Arrhenius function

    REAL,     INTENT(IN) :: k_298 ! k at T = 298.15K
    REAL,     INTENT(IN) :: tdep  ! temperature dependence
    REAL(kind=dp), INTENT(IN) :: temp  ! temperature

    INTRINSIC EXP

    k_arr = k_298 * EXP(tdep*(1._dp/temp-3.3540E-3_dp)) ! 1/298.15=3.3540e-3

  END FUNCTION k_arr

!~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!  End of User-defined Rate Law functions
!~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

! End Rate Law Functions from KPP_HOME/util/UserRateLaws


! Begin INLINED Rate Law Functions


! End INLINED Rate Law Functions

! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Update_SUN - update SUN light using TIME
!   Arguments :
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  SUBROUTINE Update_SUN()
      !USE CRI_5VOC_Parameters
      !USE CRI_5VOC_Global

    IMPLICIT NONE

    REAL(kind=dp) :: SunRise, SunSet
    REAL(kind=dp) :: Thour, Tlocal, Ttmp 
    ! PI - Value of pi
    REAL(kind=dp), PARAMETER :: PI = 3.14159265358979d0
    
    SunRise = 4.5_dp 
    SunSet  = 19.5_dp 
    Thour = TIME/3600.0_dp 
    Tlocal = Thour - (INT(Thour)/24)*24

    IF ((Tlocal>=SunRise).AND.(Tlocal<=SunSet)) THEN
       Ttmp = (2.0*Tlocal-SunRise-SunSet)/(SunSet-SunRise)
       IF (Ttmp.GT.0) THEN
          Ttmp =  Ttmp*Ttmp
       ELSE
          Ttmp = -Ttmp*Ttmp
       END IF
       SUN = ( 1.0_dp + COS(PI*Ttmp) )/2.0_dp 
    ELSE
       SUN = 0.0_dp 
    END IF

 END SUBROUTINE Update_SUN

! End of Update_SUN function
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Update_RCONST - function to update rate constants
!   Arguments :
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

SUBROUTINE Update_RCONST ( )




! Begin INLINED RCONST

 
 USE constants
 !end of USE statements 
 !
 ! start of executable statements
 RO2 = & 
 C(ind_RI16O2) + C(ind_HOCH2CH2O2) + C(ind_NRN6O2) + C(ind_RA13O2) + & 
   C(ind_RA16O2) + C(ind_RU14O2) + C(ind_NRU14O2) + C(ind_C2H5O2) + &  
   C(ind_RU10O2) + C(ind_CH3CO3) + C(ind_RN8O2) + C(ind_CH3O2) + &  
   C(ind_RI14O2) + C(ind_IC3H7O2) + C(ind_HOCH2CO3) + C(ind_RN10O2) + &  
   C(ind_RU12O2) + C(ind_NRU12O2) + C(ind_C2H5CO3) + C(ind_RN9O2) + &  
   C(ind_RN13O2) + C(ind_RN16O2) + C(ind_RN15AO2) + C(ind_RN11O2) + &  
   C(ind_RN15O2) + C(ind_RN14O2) + C(ind_RN12O2 ) 
 CALL mcm_constants(time, temp, M, N2, O2, RO2, H2O) 
 
KRO2NO = 2.7D-12*EXP(360/TEMP)
KRO2HO2 = 2.91D-13*EXP(1300/TEMP)
KAPHO2 = 5.2D-13*EXP(980/TEMP)
KAPNO = 7.5D-12*EXP(290/TEMP)
KRO2NO3 = 2.3D-12
KNO3AL = 1.4D-12*EXP(-1860/TEMP)
KDEC = 1.00D+06
KROPRIM = 2.50D-14*EXP(-300/TEMP)
KROSEC = 2.50D-14*EXP(-300/TEMP)
KCH3O2 = 1.03D-13*EXP(365/TEMP)
K298CH3O2 = 3.5D-13
KD0 = 4.90D-3*EXP(-12100/TEMP)*M
KDI = 5.4D+16*EXP(-13830/TEMP)
KRD = KD0/KDI
FCD = 0.30
NCD = 0.75-1.27*(LOG10(FCD))
FD = 10**(LOG10(FCD)/(1+(LOG10(KRD)/NCD)**2))
KBPAN = (KD0*KDI)*FD/(KD0+KDI)
KC0 = 2.7D-28*M*(TEMP/300)**(-7.1)
KCI = 1.2D-11*(TEMP/300)**(-0.9)
KRC = KC0/KCI
FCC = 0.30
NC = 0.75-1.27*(LOG10(FCC))
FC = 10**(LOG10(FCC)/(1+(LOG10(KRC)/NC)**2))
KFPAN = (KC0*KCI)*FC/(KC0+KCI)
K10 = 1.0D-31*M*(TEMP/300)**(-1.6)
K1I = 3.00D-11*(TEMP/300)**0.3
KR1 = K10/K1I
FC1 = 0.85
NC1 = 0.75-1.27*(LOG10(FC1))
F1 = 10**(LOG10(FC1)/(1+(LOG10(KR1)/NC1)**2))
KMT01 = (K10*K1I)*F1/(K10+K1I)
K20 = 1.3D-31*M*(TEMP/300)**(-1.5)
K2I = 2.3D-11*(TEMP/300)**0.24
KR2 = K20/K2I
FC2 = 0.6
NC2 = 0.75-1.27*(LOG10(FC2))
F2 = 10**(LOG10(FC2)/(1+(LOG10(KR2)/NC2)**2))
KMT02 = (K20*K2I)*F2/(K20+K2I)
K30 = 3.6D-30*M*(TEMP/300)**(-4.1)
K3I = 1.9D-12*(TEMP/300)**0.2
KR3 = K30/K3I
FC3 = 0.35
NC3 = 0.75-1.27*(LOG10(FC3))
F3 = 10**(LOG10(FC3)/(1+(LOG10(KR3)/NC3)**2))
KMT03 = (K30*K3I)*F3/(K30+K3I)
K40 = 1.3D-3*M*(TEMP/300)**(-3.5)*EXP(-11000/TEMP)
K4I = 9.7D+14*(TEMP/300)**0.1*EXP(-11080/TEMP)
KR4 = K40/K4I
FC4 = 0.35
NC4 = 0.75-1.27*(LOG10(FC4))
F4 = 10**(LOG10(FC4)/(1+(LOG10(KR4)/NC4)**2))
KMT04 = (K40*K4I)*F4/(K40+K4I)
KMT05 = 1.44D-13*(1+(M/4.2D+19))
KMT06 = 1 + (1.40D-21*EXP(2200/TEMP)*H2O)
K70 = 7.4D-31*M*(TEMP/300)**(-2.4)
K7I = 3.3D-11*(TEMP/300)**(-0.3)
KR7 = K70/K7I
FC7 = EXP(-TEMP/1420)
NC7 = 0.75-1.27*(LOG10(FC7))
F7 = 10**(LOG10(FC7)/(1+(LOG10(KR7)/NC7)**2))
KMT07 = (K70*K7I)*F7/(K70+K7I)
K80 = 3.3D-30*M*(TEMP/300)**(-3.0)
K8I = 4.1D-11
KR8 = K80/K8I
FC8 = 0.4
NC8 = 0.75-1.27*(LOG10(FC8))
F8 = 10**(LOG10(FC8)/(1+(LOG10(KR8)/NC8)**2))
KMT08 = (K80*K8I)*F8/(K80+K8I)
K90 = 1.8D-31*M*(TEMP/300)**(-3.2)
K9I = 4.7D-12
KR9 = K90/K9I
FC9 = 0.6
NC9 = 0.75-1.27*(LOG10(FC9))
F9 = 10**(LOG10(FC9)/(1+(LOG10(KR9)/NC9)**2))
KMT09 = (K90*K9I)*F9/(K90+K9I)
K100 = 4.10D-05*M*EXP(-10650/TEMP)
K10I = 4.8D+15*EXP(-11170/TEMP)
KR10 = K100/K10I
FC10 = 0.6
NC10 = 0.75-1.27*(LOG10(FC10))
F10 = 10**(LOG10(FC10)/(1+(LOG10(KR10)/NC10)**2))
KMT10 = (K100*K10I)*F10/(K100+K10I)
K1 = 2.40D-14*EXP(460/TEMP)
K3 = 6.50D-34*EXP(1335/TEMP)
K4 = 2.70D-17*EXP(2199/TEMP)
K2 = (K3*M)/(1+(K3*M/K4))
KMT11 = K1 + K2
K120 = 4.5D-31*M*(TEMP/300)**(-3.9)
K12I = 1.3D-12*(TEMP/300)**(-0.7)
KR12 = K120/K12I
FC12 = 0.525
NC12 = 0.75-1.27*(LOG10(FC12))
F12 = 10**(LOG10(FC12)/(1.0+(LOG10(KR12)/NC12)**2))
KMT12 = (K120*K12I*F12)/(K120+K12I)
K130 = 2.5D-30*M*(TEMP/300)**(-5.5)
K13I = 1.8D-11
KR13 = K130/K13I
FC13 = 0.36
NC13 = 0.75-1.27*(LOG10(FC13))
F13 = 10**(LOG10(FC13)/(1+(LOG10(KR13)/NC13)**2))
KMT13 = (K130*K13I)*F13/(K130+K13I)
K140 = 9.0D-5*EXP(-9690/TEMP)*M
K14I = 1.1D+16*EXP(-10560/TEMP)
KR14 = K140/K14I
FC14 = 0.4
NC14 = 0.75-1.27*(LOG10(FC14))
F14 = 10**(LOG10(FC14)/(1+(LOG10(KR14)/NC14)**2))
KMT14 = (K140*K14I)*F14/(K140+K14I)
K150 = 8.6D-29*M*(TEMP/300)**(-3.1)
K15I = 9.0D-12*(TEMP/300)**(-0.85)
KR15 = K150/K15I
FC15 = 0.48
NC15 = 0.75-1.27*(LOG10(FC15))
F15 = 10**(LOG10(FC15)/(1+(LOG10(KR15)/NC15)**2))
KMT15 = (K150*K15I)*F15/(K150+K15I)
K160 = 8D-27*M*(TEMP/300)**(-3.5)
K16I = 3.0D-11*(TEMP/300)**(-1)
KR16 = K160/K16I
FC16 = 0.5
NC16 = 0.75-1.27*(LOG10(FC16))
F16 = 10**(LOG10(FC16)/(1+(LOG10(KR16)/NC16)**2))
KMT16 = (K160*K16I)*F16/(K160+K16I)
K170 = 5.0D-30*M*(TEMP/300)**(-1.5)
K17I = 1.0D-12
KR17 = K170/K17I
FC17 = 0.17*EXP(-51/TEMP)+EXP(-TEMP/204)
NC17 = 0.75-1.27*(LOG10(FC17))
F17 = 10**(LOG10(FC17)/(1.0+(LOG10(KR17)/NC17)**2))
KMT17 = (K170*K17I*F17)/(K170+K17I)
KMT18 = 9.5D-39*O2*EXP(5270/TEMP)/(1+7.5D-29*O2*EXP(5610/TEMP))

! End INLINED RCONST

  RCONST(1) = (5.6D-34*N2*(TEMP/300)**(-2.6)*O2+6.0D-34*O2*(TEMP/300)**(-2.6)*O2)
  RCONST(2) = (8.0D-12*EXP(-2060/TEMP))
  RCONST(3) = (KMT01)
  RCONST(4) = (5.5D-12*EXP(188/TEMP))
  RCONST(5) = (KMT02)
  RCONST(6) = (3.2D-11*EXP(67/TEMP)*O2+2.0D-11*EXP(130/TEMP)*N2)
  RCONST(7) = (1.4D-12*EXP(-1310/TEMP))
  RCONST(8) = (1.4D-13*EXP(-2470/TEMP))
  RCONST(9) = (3.3D-39*EXP(530/TEMP)*O2)
  RCONST(10) = (1.8D-11*EXP(110/TEMP))
  RCONST(11) = (4.50D-14*EXP(-1260/TEMP))
  RCONST(12) = (KMT03)
  RCONST(13) = (2.14D-10*H2O)
  RCONST(14) = (1.70D-12*EXP(-940/TEMP))
  RCONST(15) = (7.7D-12*EXP(-2100/TEMP))
  RCONST(16) = (KMT05)
  RCONST(17) = (2.9D-12*EXP(-160/TEMP))
  RCONST(18) = (2.03D-16*(TEMP/300)**4.57*EXP(693/TEMP))
  RCONST(19) = (4.8D-11*EXP(250/TEMP))
  RCONST(20) = (2.20D-13*KMT06*EXP(600/TEMP)+1.90D-33*M*KMT06*EXP(980/TEMP))
  RCONST(21) = (KMT07)
  RCONST(22) = (KMT08)
  RCONST(23) = (2.0D-11)
  RCONST(24) = (3.45D-12*EXP(270/TEMP))
  RCONST(25) = (KMT09)
  RCONST(26) = (3.2D-13*EXP(690/TEMP)*1.0)
  RCONST(27) = (4.0D-12)
  RCONST(28) = (2.5D-12*EXP(260/TEMP))
  RCONST(29) = (KMT11)
  RCONST(30) = (4.0D-32*EXP(-1000/TEMP)*M)
  RCONST(31) = (KMT12)
  RCONST(32) = (1.3D-12*EXP(-330/TEMP)*O2)
  RCONST(33) = (6.00D-06)
  RCONST(34) = (4.00D-04)
  RCONST(35) = (1.20D-15*H2O)
  RCONST(36) = (J(1))
  RCONST(37) = (J(2))
  RCONST(38) = (J(3))
  RCONST(39) = (J(4))
  RCONST(40) = (J(5))
  RCONST(41) = (J(6))
  RCONST(42) = (J(7))
  RCONST(43) = (J(8))
  RCONST(44) = (KMT04)
  RCONST(45) = (KMT10)
  RCONST(46) = (3.70D-12)
  RCONST(47) = (KMT15)
  RCONST(48) = (2.10D-16)
  RCONST(49) = (9.14D-15*EXP(-2580/TEMP)*0.13)
  RCONST(50) = (9.14D-15*EXP(-2580/TEMP)*0.87)
  RCONST(51) = (2.33D-12*EXP(-193/TEMP)*0.47)
  RCONST(52) = (2.33D-12*EXP(-193/TEMP)*0.53)
  RCONST(53) = (1.81D-12*EXP(338/TEMP)*0.82)
  RCONST(54) = (1.81D-12*EXP(338/TEMP)*0.18)
  RCONST(55) = (2.54D-11*EXP(410/TEMP))
  RCONST(56) = (3.03D-12*EXP(-446/TEMP))
  RCONST(57) = (7.86D-15*EXP(-1913/TEMP)*0.27)
  RCONST(58) = (7.86D-15*EXP(-1913/TEMP)*0.73)
  RCONST(59) = (KRO2NO*0.075)
  RCONST(60) = (KRO2HO2*0.706)
  RCONST(61) = (6.70D-13*RO2)
  RCONST(62) = (KRO2NO*0.925*0.913)
  RCONST(63) = (KRO2NO*0.925*0.087)
  RCONST(64) = (KRO2NO3*0.913)
  RCONST(65) = (KRO2NO3*0.087)
  RCONST(66) = (KRO2NO*0.005)
  RCONST(67) = (2.03D-13*EXP(1250/TEMP))
  RCONST(68) = (2.00D-12*RO2*0.224)
  RCONST(69) = (KRO2NO*0.995*0.224)
  RCONST(70) = (KRO2NO3*0.224)
  RCONST(71) = (KRO2NO3*0.776)
  RCONST(72) = (KRO2NO*0.995*0.776)
  RCONST(73) = (2.00D-12*RO2*0.776)
  RCONST(74) = (KRO2HO2*0.387)
  RCONST(75) = (6.00D-13*RO2)
  RCONST(76) = (KRO2NO3)
  RCONST(77) = (KRO2NO)
  RCONST(78) = (J(12))
  RCONST(79) = (1.20D-14*TEMP*EXP(287/TEMP))
  RCONST(80) = (5.80D-16)
  RCONST(81) = (J(11))
  RCONST(82) = (4.50D-13)
  RCONST(83) = (KRO2NO*0.082)
  RCONST(84) = (KRO2HO2*0.770)
  RCONST(85) = (8.80D-13*RO2)
  RCONST(86) = (KRO2NO*0.918)
  RCONST(87) = (KRO2NO3)
  RCONST(88) = (2.63D-11)
  RCONST(89) = (3.78D-12)
  RCONST(90) = (KRO2NO*0.111)
  RCONST(91) = (KRO2HO2*0.820)
  RCONST(92) = (8.80D-13*RO2*0.7)
  RCONST(93) = (8.80D-13*RO2*0.3)
  RCONST(94) = (KRO2NO*0.889*0.7)
  RCONST(95) = (KRO2NO*0.889*0.3)
  RCONST(96) = (KRO2NO3*0.7)
  RCONST(97) = (KRO2NO3*0.3)
  RCONST(98) = (4.65D-11)
  RCONST(99) = (1.25D-11)
  RCONST(100) = (KRO2NO*0.100)
  RCONST(101) = (KRO2HO2*0.770)
  RCONST(102) = (1.71D-12*RO2*0.252)
  RCONST(103) = (KRO2NO*0.900*0.252)
  RCONST(104) = (1.71D-12*RO2*0.748)
  RCONST(105) = (KRO2NO*0.900*0.748)
  RCONST(106) = (KRO2NO3*0.252)
  RCONST(107) = (KRO2NO3*0.748)
  RCONST(108) = (KRO2HO2*0.770)
  RCONST(109) = (1.30D-12*RO2)
  RCONST(110) = (KRO2NO)
  RCONST(111) = (KRO2NO3)
  RCONST(112) = (2.50D-11)
  RCONST(113) = (2.85D-18*0.59)
  RCONST(114) = (J(18)*2)
  RCONST(115) = (KNO3AL)
  RCONST(116) = (2.85D-18*0.41)
  RCONST(117) = (J(55))
  RCONST(118) = (9.67D-13)
  RCONST(119) = (J(41))
  RCONST(120) = (1.23D-11)
  RCONST(121) = (5.34D-18*TEMP**2*EXP(-230/TEMP))
  RCONST(122) = (J(21))
  RCONST(123) = (2.60D-12*EXP(365/TEMP)*0.009)
  RCONST(124) = (3.10D-13*0.2*RO2)
  RCONST(125) = (3.10D-13*0.2*RO2)
  RCONST(126) = (7.50D-13*EXP(700/TEMP))
  RCONST(127) = (3.10D-13*0.6*RO2)
  RCONST(128) = (2.60D-12*EXP(365/TEMP)*0.991)
  RCONST(129) = (KRO2NO3)
  RCONST(130) = (2.77D-12)
  RCONST(131) = (J(22))
  RCONST(132) = (1.09D-12)
  RCONST(133) = (2.13D-11)
  RCONST(134) = (J(41))
  RCONST(135) = (1.00D-11)
  RCONST(136) = (KNO3AL)
  RCONST(137) = (J(15))
  RCONST(138) = (J(41))
  RCONST(139) = (5.22D-12)
  RCONST(140) = (7.30D-11)
  RCONST(141) = (J(54))
  RCONST(142) = (9.77D-11)
  RCONST(143) = (J(41))
  RCONST(144) = (1.14D-11)
  RCONST(145) = (J(33))
  RCONST(146) = (5.20D-11*0.50)
  RCONST(147) = (5.20D-11*0.50)
  RCONST(148) = (J(4)*0.02*0.64)
  RCONST(149) = (J(4)*0.02*0.36)
  RCONST(150) = (2.08D-12)
  RCONST(151) = (7.16D-11)
  RCONST(152) = (J(54))
  RCONST(153) = (9.64D-11)
  RCONST(154) = (J(41))
  RCONST(155) = (5.58D-11*0.55)
  RCONST(156) = (5.58D-11*0.45)
  RCONST(157) = (J(4)*0.02*0.55)
  RCONST(158) = (J(4)*0.02*0.45)
  RCONST(159) = (1.72D-11)
  RCONST(160) = (J(34))
  RCONST(161) = (2.08D-12)
  RCONST(162) = (5.55D-11)
  RCONST(163) = (7.51D-11)
  RCONST(164) = (J(41)*0.252)
  RCONST(165) = (J(41)*0.748)
  RCONST(166) = (4.52D-11)
  RCONST(167) = (2.40D-17*0.89)
  RCONST(168) = (2.40D-17*0.11)
  RCONST(169) = (KNO3AL*4.25)
  RCONST(170) = (J(18)*2)
  RCONST(171) = (1.03D-10)
  RCONST(172) = (J(41))
  RCONST(173) = (4.16D-11)
  RCONST(174) = (J(18))
  RCONST(175) = (KFPAN*0.041)
  RCONST(176) = (2.00D-12*RO2*0.5)
  RCONST(177) = (KRO2HO2*0.625)
  RCONST(178) = (2.00D-12*RO2*0.3)
  RCONST(179) = (2.00D-12*RO2*0.2)
  RCONST(180) = (KRO2NO*0.5)
  RCONST(181) = (KRO2NO3*0.5)
  RCONST(182) = (KRO2NO*0.2)
  RCONST(183) = (KRO2NO*0.3)
  RCONST(184) = (KRO2NO3*0.2)
  RCONST(185) = (KRO2NO3*0.3)
  RCONST(186) = (1.00D-11*RO2)
  RCONST(187) = (KFPAN)
  RCONST(188) = (KAPHO2)
  RCONST(189) = (KAPNO)
  RCONST(190) = (KRO2NO3*1.60)
  RCONST(191) = (5.55D-12*EXP(311/TEMP))
  RCONST(192) = (J(13))
  RCONST(193) = (KNO3AL)
  RCONST(194) = (1.40D-12*RO2)
  RCONST(195) = (KRO2HO2*0.520)
  RCONST(196) = (KRO2NO)
  RCONST(197) = (KRO2NO3)
  RCONST(198) = (1.82D-13*EXP(416/TEMP)*0.335*RO2)
  RCONST(199) = (3.00D-12*EXP(280/TEMP)*0.001)
  RCONST(200) = (1.82D-13*EXP(416/TEMP)*0.335*RO2)
  RCONST(201) = (1.82D-13*EXP(416/TEMP)*0.33*RO2)
  RCONST(202) = (4.10D-13*EXP(790/TEMP))
  RCONST(203) = (3.00D-12*EXP(280/TEMP)*0.999)
  RCONST(204) = (KRO2NO3*0.40)
  RCONST(205) = (4.40D-14*EXP(720/TEMP))
  RCONST(206) = (J(52))
  RCONST(207) = (6.18D-18*TEMP**2*EXP(532/TEMP)*0.113)
  RCONST(208) = (6.18D-18*TEMP**2*EXP(532/TEMP)*0.887)
  RCONST(209) = (1.36D-11)
  RCONST(210) = (J(41))
  RCONST(211) = (KRO2HO2*0.706)
  RCONST(212) = (1.40D-12*RO2)
  RCONST(213) = (KRO2NO*0.52)
  RCONST(214) = (KRO2NO*0.48)
  RCONST(215) = (KRO2NO3*0.52)
  RCONST(216) = (KRO2NO3*0.48)
  RCONST(217) = (4.00D-14*0.2*RO2)
  RCONST(218) = (4.00D-14*0.2*RO2)
  RCONST(219) = (2.70D-12*EXP(360/TEMP)*0.042)
  RCONST(220) = (4.00D-14*0.6*RO2)
  RCONST(221) = (KRO2HO2*0.520)
  RCONST(222) = (2.70D-12*EXP(360/TEMP)*0.958)
  RCONST(223) = (KRO2NO3)
  RCONST(224) = (KAPHO2)
  RCONST(225) = (1.00D-11*RO2)
  RCONST(226) = (KFPAN)
  RCONST(227) = (KAPNO)
  RCONST(228) = (KRO2NO3*1.60)
  RCONST(229) = (1.50D-12)
  RCONST(230) = (9.00D-13)
  RCONST(231) = (9.00D-14)
  RCONST(232) = (6.00D-13*0.2*RO2)
  RCONST(233) = (6.00D-13*0.2*RO2)
  RCONST(234) = (2.80D-12*EXP(360/TEMP)*0.020)
  RCONST(235) = (KRO2HO2*0.520)
  RCONST(236) = (6.00D-13*0.6*RO2)
  RCONST(237) = (2.80D-12*EXP(360/TEMP)*0.980)
  RCONST(238) = (KRO2NO3)
  RCONST(239) = (1.53D-12)
  RCONST(240) = (3.13D-13)
  RCONST(241) = (KFPAN*0.061)
  RCONST(242) = (KRO2HO2*0.706)
  RCONST(243) = (2.00D-12*RO2*0.7)
  RCONST(244) = (2.00D-12*RO2*0.3)
  RCONST(245) = (KRO2NO*0.3)
  RCONST(246) = (KRO2NO*0.7)
  RCONST(247) = (KRO2NO3*0.3)
  RCONST(248) = (KRO2NO3*0.7)
  RCONST(249) = (KRO2HO2*0.625)
  RCONST(250) = (9.60D-13*RO2)
  RCONST(251) = (KRO2NO)
  RCONST(252) = (KRO2NO3)
  RCONST(253) = (1.30D-13)
  RCONST(254) = (J(56)+J(57))
  RCONST(255) = (KBPAN)
  RCONST(256) = (3.60D-12)
  RCONST(257) = (3.00D-11)
  RCONST(258) = (J(41))
  RCONST(259) = (3.00D-12)
  RCONST(260) = (J(22))
  RCONST(261) = (KBPAN)
  RCONST(262) = (9.50D-13*EXP(-650/TEMP))
  RCONST(263) = (J(41))
  RCONST(264) = (3.70D-12)
  RCONST(265) = (J(41))
  RCONST(266) = (4.42D-12)
  RCONST(267) = (6.01D-18*TEMP**2*EXP(170/TEMP))
  RCONST(268) = (1.00D-14*EXP(1060/TEMP))
  RCONST(269) = (J(51))
  RCONST(270) = (1.90D-12*EXP(190/TEMP))
  RCONST(271) = (1.00D-12*EXP(190/TEMP))
  RCONST(272) = (J(41))
  RCONST(273) = (1.58D-11)
  RCONST(274) = (J(41))
  RCONST(275) = (1.00D-11*RO2)
  RCONST(276) = (KFPAN)
  RCONST(277) = (KAPHO2)
  RCONST(278) = (KAPNO)
  RCONST(279) = (KRO2NO3*1.60)
  RCONST(280) = (4.06D-18*TEMP**2*EXP(788/TEMP)*0.14)
  RCONST(281) = (4.06D-18*TEMP**2*EXP(788/TEMP)*0.86)
  RCONST(282) = (4.90D-13)
  RCONST(283) = (J(54))
  RCONST(284) = (2.78D-11)
  RCONST(285) = (J(41))
  RCONST(286) = (6.19D-12)
  RCONST(287) = (J(41))
  RCONST(288) = (KBPAN)
  RCONST(289) = (1.12D-12)
  RCONST(290) = (1.65D-11)
  RCONST(291) = (J(22)*3.00)
  RCONST(292) = (5.53D-12*0.51)
  RCONST(293) = (5.53D-12*0.49)
  RCONST(294) = (1.96D-11)
  RCONST(295) = (J(14))
  RCONST(296) = (KNO3AL*2.4)
  RCONST(297) = (7.30D-13)
  RCONST(298) = (J(53))
  RCONST(299) = (1.89D-11)
  RCONST(300) = (J(41))
  RCONST(301) = (1.25D-11)
  RCONST(302) = (J(22)*3.35)
  RCONST(303) = (KBPAN)
  RCONST(304) = (2.52D-11)
  RCONST(305) = (3.00D-11)
  RCONST(306) = (J(41))
  RCONST(307) = (2.65D-11)
  RCONST(308) = (J(41))
  RCONST(309) = (KBPAN)
  RCONST(310) = (1.27D-12)
  RCONST(311) = (J(41))
  RCONST(312) = (4.42D-12)
  RCONST(313) = (KRO2NO*0.021)
  RCONST(314) = (KRO2HO2*0.520)
  RCONST(315) = (8.80D-13*RO2)
  RCONST(316) = (KRO2NO*0.979)
  RCONST(317) = (KRO2NO3)
  RCONST(318) = (KRO2NO*0.083)
  RCONST(319) = (2.50D-13*RO2*0.398)
  RCONST(320) = (2.50D-13*RO2*0.602)
  RCONST(321) = (KRO2HO2*0.625)
  RCONST(322) = (KRO2NO*0.917*0.602)
  RCONST(323) = (KRO2NO*0.917*0.398)
  RCONST(324) = (KRO2NO3*0.398)
  RCONST(325) = (KRO2NO3*0.602)
  RCONST(326) = (2.50D-13*RO2)
  RCONST(327) = (KRO2NO*0.123)
  RCONST(328) = (KRO2HO2*0.706)
  RCONST(329) = (KRO2NO*0.877)
  RCONST(330) = (KRO2NO3)
  RCONST(331) = (1.31D-12)
  RCONST(332) = (2.50D-11)
  RCONST(333) = (J(41))
  RCONST(334) = (9.20D-13)
  RCONST(335) = (J(53)*0.398)
  RCONST(336) = (J(53)*0.602)
  RCONST(337) = (3.24D-18*TEMP**2*EXP(414/TEMP))
  RCONST(338) = (J(22))
  RCONST(339) = (3.57D-11)
  RCONST(340) = (J(41)*0.398)
  RCONST(341) = (J(41)*0.602)
  RCONST(342) = (KRO2NO*0.025)
  RCONST(343) = (KRO2HO2*0.706)
  RCONST(344) = (8.80D-13*RO2)
  RCONST(345) = (KRO2NO*0.975)
  RCONST(346) = (KRO2NO3)
  RCONST(347) = (J(53))
  RCONST(348) = (1.85D-12)
  RCONST(349) = (J(41))
  RCONST(350) = (4.21D-11)
  RCONST(351) = (KRO2HO2*0.625)
  RCONST(352) = (1.40D-12*RO2)
  RCONST(353) = (KRO2NO)
  RCONST(354) = (KRO2NO3)
  RCONST(355) = (1.03D-11)
  RCONST(356) = (3.74D-11)
  RCONST(357) = (J(41))
  RCONST(358) = (KRO2NO*0.064)
  RCONST(359) = (KRO2HO2*0.706)
  RCONST(360) = (8.80D-13*RO2)
  RCONST(361) = (KRO2NO*0.936)
  RCONST(362) = (KRO2NO3)
  RCONST(363) = (1.87D-11)
  RCONST(364) = (J(22)*4.74)
  RCONST(365) = (J(41))
  RCONST(366) = (2.50D-11)
  RCONST(367) = (KRO2HO2*0.706)
  RCONST(368) = (1.40D-12*RO2)
  RCONST(369) = (KRO2NO)
  RCONST(370) = (KRO2NO3)
  RCONST(371) = (2.40D-13)
  RCONST(372) = (J(35))
  RCONST(373) = (J(41))
  RCONST(374) = (3.20D-11)
  RCONST(375) = (1.38D-12)
  RCONST(376) = (J(35))
  RCONST(377) = (KRO2NO*0.041)
  RCONST(378) = (KRO2HO2*0.625)
  RCONST(379) = (KRO2NO3)
  RCONST(380) = (KRO2NO*0.959)
  RCONST(381) = (8.80D-13*RO2)
  RCONST(382) = (1.79D-12)
  RCONST(383) = (3.25D-11)
  RCONST(384) = (J(41))
  RCONST(385) = (5.86D-12)
  RCONST(386) = (J(22))
      
END SUBROUTINE Update_RCONST

! End of Update_RCONST function
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Update_PHOTO - function to update photolytical rate constants
!   Arguments :
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

SUBROUTINE Update_PHOTO ( )


   USE CRI_5VOC_Global

      
END SUBROUTINE Update_PHOTO

! End of Update_PHOTO function
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



END MODULE CRI_5VOC_Rates

