! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Utility Data Module File
! 
! Generated by KPP-2.2.3 symbolic chemistry Kinetics PreProcessor
!       (http://www.cs.vt.edu/~asandu/Software/KPP)
! KPP is distributed under GPL, the general public licence
!       (http://www.gnu.org/copyleft/gpl.html)
! (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa
! (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech
!     With important contributions from:
!        M. Damian, Villanova University, USA
!        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany
! 
! File                 : CRI_5VOC_Monitor.f90
! Time                 : Tue Aug 27 15:48:10 2013
! Working directory    : /home/hes134/kpp-2.2.3/CRI_5VOC
! Equation file        : CRI_5VOC.kpp
! Output root filename : CRI_5VOC
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



MODULE CRI_5VOC_Monitor


  CHARACTER(LEN=15), PARAMETER, DIMENSION(90) :: SPC_NAMES_0 = (/ &
     'NA             ','SA             ','SO3            ', &
     'HSO3           ','O1D            ','IC5H12         ', &
     'TOLUENE        ','N2O5           ','BENZENE        ', &
     'H2             ','HONO           ','CH3OH          ', &
     'ANHY           ','SO2            ','C2H5OH         ', &
     'HCOOH          ','AROH17         ','RAROH17        ', &
     'NPROPOL        ','CARB12         ','AROH14         ', &
     'RAROH14        ','IPROPOL        ','NRU14OOH       ', &
     'C2H5CO3H       ','RN8OOH         ','NRN6OOH        ', &
     'HOC2H4NO3      ','RN12NO3        ','RN10OOH        ', &
     'IC3H7OOH       ','HO2NO2         ','C2H5OOH        ', &
     'CARB9          ','RU14NO3        ','RN9NO3         ', &
     'RN16OOH        ','CH3CO3H        ','H2O2           ', &
     'RI14OOH        ','HOC2H4OOH      ','RA13OOH        ', &
     'IC3H7NO3       ','RN15NO3        ','RU12PAN        ', &
     'RN12OOH        ','RN10NO3        ','RI16OOH        ', &
     'RN16NO3        ','HOCH2CO3H      ','RA16OOH        ', &
     'RU10OOH        ','RN11OOH        ','CH3NO3         ', &
     'CH3OOH         ','NRU12OOH       ','C2H5NO3        ', &
     'PAN            ','RU12OOH        ','ARNOH14        ', &
     'ARNOH17        ','RU14OOH        ','PHAN           ', &
     'RA13NO3        ','RN13OOH        ','PPN            ', &
     'RN9OOH         ','CARB16         ','RI16NO3        ', &
     'RA16NO3        ','RN14OOH        ','MPAN           ', &
     'MIPK           ','CARB14         ','RN13NO3        ', &
     'CARB3          ','CARB10         ','RN15OOH        ', &
     'CARB11A        ','UDCARB8        ','C2H4           ', &
     'C5H8           ','UDCARB11       ','NUCARB12       ', &
     'HNO3           ','CH3COCH3       ','NOA            ', &
     'O              ','NRN6O2         ','RA13O2         ' /)
  CHARACTER(LEN=15), PARAMETER, DIMENSION(42) :: SPC_NAMES_1 = (/ &
     'CARB13         ','RU14O2         ','RN12O2         ', &
     'CARB7          ','HOCH2CO3       ','CO             ', &
     'RA16O2         ','NRU12O2        ','CARB6          ', &
     'NRU14O2        ','UCARB12        ','RN10O2         ', &
     'HOCH2CH2O2     ','RN11O2         ','RN15AO2        ', &
     'IC3H7O2        ','RN15O2         ','C2H5CHO        ', &
     'CH3O2          ','HOCH2CHO       ','RU10O2         ', &
     'RU12O2         ','O3             ','UCARB10        ', &
     'RI16O2         ','RI14O2         ','HCHO           ', &
     'RN8O2          ','RN9O2          ','CH3CO3         ', &
     'RN14O2         ','RN16O2         ','RN13O2         ', &
     'C2H5CO3        ','C2H5O2         ','OH             ', &
     'NO             ','HO2            ','NO2            ', &
     'CH3CHO         ','NO3            ','DUMMY          ' /)
  CHARACTER(LEN=15), PARAMETER, DIMENSION(132) :: SPC_NAMES = (/&
    SPC_NAMES_0, SPC_NAMES_1 /)

  INTEGER, PARAMETER, DIMENSION(132) :: LOOKAT = (/ &
       1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, &
      13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, &
      25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, &
      37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, &
      49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, &
      61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, &
      73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, &
      85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, &
      97, 98, 99,100,101,102,103,104,105,106,107,108, &
     109,110,111,112,113,114,115,116,117,118,119,120, &
     121,122,123,124,125,126,127,128,129,130,131,132 /)

  INTEGER, DIMENSION(1) :: MONITOR
  CHARACTER(LEN=15), DIMENSION(1) :: SMASS
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_0 = (/ &
     '               O --> O3                                                                             ', &
     '          O + O3 --> DUMMY                                                                          ', &
     '          O + NO --> NO2                                                                            ', &
     '         O + NO2 --> NO                                                                             ', &
     '         O + NO2 --> NO3                                                                            ', &
     '             O1D --> O                                                                              ', &
     '         O3 + NO --> NO2                                                                            ', &
     '        O3 + NO2 --> NO3                                                                            ', &
     '            2 NO --> 2 NO2                                                                          ', &
     '        NO + NO3 --> 2 NO2                                                                          ', &
     '       NO2 + NO3 --> NO + NO2                                                                       ', &
     '       NO2 + NO3 --> N2O5                                                                           ', &
     '             O1D --> 2 OH                                                                           ', &
     '         O3 + OH --> HO2                                                                            ', &
     '         H2 + OH --> HO2                                                                            ', &
     '         CO + OH --> HO2                                                                            ', &
     '       H2O2 + OH --> HO2                                                                            ', &
     '        O3 + HO2 --> OH                                                                             ', &
     '        OH + HO2 --> DUMMY                                                                          ', &
     '           2 HO2 --> H2O2                                                                           ', &
     '         OH + NO --> HONO                                                                           ', &
     '        OH + NO2 --> HNO3                                                                           ', &
     '        OH + NO3 --> HO2 + NO2                                                                      ', &
     '        NO + HO2 --> OH + NO2                                                                       ', &
     '       HO2 + NO2 --> HO2NO2                                                                         ', &
     '     HO2NO2 + OH --> NO2                                                                            ', &
     '       HO2 + NO3 --> OH + NO2                                                                       ', &
     '       HONO + OH --> NO2                                                                            ', &
     '       HNO3 + OH --> NO3                                                                            ', &
     '         SO2 + O --> SO3                                                                            ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_1 = (/ &
     '        SO2 + OH --> HSO3                                                                           ', &
     '            HSO3 --> SO3 + HO2                                                                      ', &
     '            HNO3 --> NA                                                                             ', &
     '            N2O5 --> 2 NA                                                                           ', &
     '             SO3 --> SA                                                                             ', &
     '              O3 --> O1D                                                                            ', &
     '              O3 --> O                                                                              ', &
     '            H2O2 --> 2 OH                                                                           ', &
     '             NO2 --> O + NO                                                                         ', &
     '             NO3 --> NO                                                                             ', &
     '             NO3 --> O + NO2                                                                        ', &
     '            HONO --> OH + NO                                                                        ', &
     '            HNO3 --> OH + NO2                                                                       ', &
     '            N2O5 --> NO2 + NO3                                                                      ', &
     '          HO2NO2 --> HO2 + NO2                                                                      ', &
     '     IC5H12 + OH --> RI16O2                                                                         ', &
     '       C2H4 + OH --> HOCH2CH2O2                                                                     ', &
     '      C2H4 + NO3 --> NRN6O2                                                                         ', &
     '       C2H4 + O3 --> CO + HCHO + OH + HO2                                                           ', &
     '       C2H4 + O3 --> HCOOH + HCHO                                                                   ', &
     '    BENZENE + OH --> RA13O2                                                                         ', &
     '    BENZENE + OH --> AROH14 + HO2                                                                   ', &
     '    TOLUENE + OH --> RA16O2                                                                         ', &
     '    TOLUENE + OH --> AROH17 + HO2                                                                   ', &
     '       C5H8 + OH --> RU14O2                                                                         ', &
     '      C5H8 + NO3 --> NRU14O2                                                                        ', &
     '       C5H8 + O3 --> CO + UCARB10 + OH + HO2                                                        ', &
     '       C5H8 + O3 --> HCOOH + UCARB10                                                                ', &
     '     RI16O2 + NO --> RI16NO3                                                                        ', &
     '    RI16O2 + HO2 --> RI16OOH                                                                        ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_2 = (/ &
     '          RI16O2 --> CH3COCH3 + C2H5O2                                                              ', &
     '     RI16O2 + NO --> CH3COCH3 + C2H5O2 + NO2                                                        ', &
     '     RI16O2 + NO --> MIPK + HO2 + NO2                                                               ', &
     '    RI16O2 + NO3 --> CH3COCH3 + C2H5O2 + NO2                                                        ', &
     '    RI16O2 + NO3 --> MIPK + HO2 + NO2                                                               ', &
     ' HOCH2CH2O2 + NO --> HOC2H4NO3                                                                      ', &
     'HOCH2CH2O2 + HO2 --> HOC2H4OOH                                                                      ', &
     '      HOCH2CH2O2 --> HOCH2CHO + HO2                                                                 ', &
     ' HOCH2CH2O2 + NO --> HOCH2CHO + HO2 + NO2                                                           ', &
     'HOCH2CH2O2 + NO3 --> HOCH2CHO + HO2 + NO2                                                           ', &
     'HOCH2CH2O2 + NO3 --> 2 HCHO + HO2 + NO2                                                             ', &
     ' HOCH2CH2O2 + NO --> 2 HCHO + HO2 + NO2                                                             ', &
     '      HOCH2CH2O2 --> 2 HCHO + HO2                                                                   ', &
     '    NRN6O2 + HO2 --> NRN6OOH                                                                        ', &
     '          NRN6O2 --> 2 HCHO + NO2                                                                   ', &
     '    NRN6O2 + NO3 --> 2 HCHO + 2 NO2                                                                 ', &
     '     NRN6O2 + NO --> 2 HCHO + 2 NO2                                                                 ', &
     '            HCHO --> H2 + CO                                                                        ', &
     '       HCHO + OH --> CO + HO2                                                                       ', &
     '      HCHO + NO3 --> HNO3 + CO + HO2                                                                ', &
     '            HCHO --> CO + 2 HO2                                                                     ', &
     '      HCOOH + OH --> HO2                                                                            ', &
     '     RA13O2 + NO --> RA13NO3                                                                        ', &
     '    RA13O2 + HO2 --> RA13OOH                                                                        ', &
     '          RA13O2 --> CARB3 + UDCARB8 + HO2                                                          ', &
     '     RA13O2 + NO --> CARB3 + UDCARB8 + HO2 + NO2                                                    ', &
     '    RA13O2 + NO3 --> CARB3 + UDCARB8 + HO2 + NO2                                                    ', &
     '     AROH14 + OH --> RAROH14                                                                        ', &
     '    AROH14 + NO3 --> RAROH14 + HNO3                                                                 ', &
     '     RA16O2 + NO --> RA16NO3                                                                        ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_3 = (/ &
     '    RA16O2 + HO2 --> RA16OOH                                                                        ', &
     '          RA16O2 --> CARB3 + UDCARB11 + HO2                                                         ', &
     '          RA16O2 --> UDCARB8 + CARB6 + HO2                                                          ', &
     '     RA16O2 + NO --> CARB3 + UDCARB11 + HO2 + NO2                                                   ', &
     '     RA16O2 + NO --> UDCARB8 + CARB6 + HO2 + NO2                                                    ', &
     '    RA16O2 + NO3 --> CARB3 + UDCARB11 + HO2 + NO2                                                   ', &
     '    RA16O2 + NO3 --> UDCARB8 + CARB6 + HO2 + NO2                                                    ', &
     '     AROH17 + OH --> RAROH17                                                                        ', &
     '    AROH17 + NO3 --> RAROH17 + HNO3                                                                 ', &
     '     RU14O2 + NO --> RU14NO3                                                                        ', &
     '    RU14O2 + HO2 --> RU14OOH                                                                        ', &
     '          RU14O2 --> UCARB12 + HO2                                                                  ', &
     '     RU14O2 + NO --> UCARB12 + HO2 + NO2                                                            ', &
     '          RU14O2 --> UCARB10 + HCHO + HO2                                                           ', &
     '     RU14O2 + NO --> UCARB10 + HCHO + HO2 + NO2                                                     ', &
     '    RU14O2 + NO3 --> UCARB12 + HO2 + NO2                                                            ', &
     '    RU14O2 + NO3 --> UCARB10 + HCHO + HO2 + NO2                                                     ', &
     '   NRU14O2 + HO2 --> NRU14OOH                                                                       ', &
     '         NRU14O2 --> NUCARB12 + HO2                                                                 ', &
     '    NRU14O2 + NO --> NUCARB12 + HO2 + NO2                                                           ', &
     '   NRU14O2 + NO3 --> NUCARB12 + HO2 + NO2                                                           ', &
     '    UCARB10 + OH --> RU10O2                                                                         ', &
     '    O3 + UCARB10 --> CO + HCHO + CH3CO3 + OH                                                        ', &
     '         UCARB10 --> HCHO + CH3CO3 + HO2                                                            ', &
     '   UCARB10 + NO3 --> HNO3 + RU10O2                                                                  ', &
     '    O3 + UCARB10 --> H2O2 + CARB6 + HCHO                                                            ', &
     '         RI16NO3 --> CH3COCH3 + C2H5O2 + NO2                                                        ', &
     '    RI16NO3 + OH --> CH3COCH3 + NO2 + CH3CHO                                                        ', &
     '         RI16OOH --> CH3COCH3 + C2H5O2 + OH                                                         ', &
     '    RI16OOH + OH --> CH3COCH3 + OH + CH3CHO                                                         ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_4 = (/ &
     '   CH3COCH3 + OH --> RN8O2                                                                          ', &
     '        CH3COCH3 --> CH3O2 + CH3CO3                                                                 ', &
     '     C2H5O2 + NO --> C2H5NO3                                                                        ', &
     '          C2H5O2 --> CH3CHO                                                                         ', &
     '          C2H5O2 --> C2H5OH                                                                         ', &
     '    C2H5O2 + HO2 --> C2H5OOH                                                                        ', &
     '          C2H5O2 --> HO2 + CH3CHO                                                                   ', &
     '     C2H5O2 + NO --> HO2 + NO2 + CH3CHO                                                             ', &
     '    C2H5O2 + NO3 --> HO2 + NO2 + CH3CHO                                                             ', &
     '       MIPK + OH --> RI14O2                                                                         ', &
     '            MIPK --> IC3H7O2 + CH3CO3                                                               ', &
     '  HOC2H4NO3 + OH --> HOCH2CHO + NO2                                                                 ', &
     '  HOC2H4OOH + OH --> HOCH2CHO + OH                                                                  ', &
     '       HOC2H4OOH --> 2 HCHO + OH + HO2                                                              ', &
     '   HOCH2CHO + OH --> HOCH2CO3                                                                       ', &
     '  HOCH2CHO + NO3 --> HNO3 + HOCH2CO3                                                                ', &
     '        HOCH2CHO --> CO + HCHO + 2 HO2                                                              ', &
     '         NRN6OOH --> 2 HCHO + OH + NO2                                                              ', &
     '    NRN6OOH + OH --> 2 HCHO + OH + NO2                                                              ', &
     '    RA13NO3 + OH --> CARB3 + UDCARB8 + NO2                                                          ', &
     '         RA13NO3 --> CARB3 + UDCARB8 + HO2 + NO2                                                    ', &
     '    RA13OOH + OH --> CARB3 + UDCARB8 + OH                                                           ', &
     '         RA13OOH --> CARB3 + UDCARB8 + OH + HO2                                                     ', &
     '      CARB3 + OH --> 2 CO + HO2                                                                     ', &
     '           CARB3 --> 2 CO + 2 HO2                                                                   ', &
     '    UDCARB8 + OH --> C2H5O2                                                                         ', &
     '    UDCARB8 + OH --> ANHY + HO2                                                                     ', &
     '         UDCARB8 --> C2H5O2 + HO2                                                                   ', &
     '         UDCARB8 --> ANHY + 2 HO2                                                                   ', &
     '   RAROH14 + NO2 --> ARNOH14                                                                        ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_5 = (/ &
     '    RA16NO3 + OH --> CARB3 + UDCARB11 + NO2                                                         ', &
     '         RA16NO3 --> CARB3 + UDCARB11 + HO2 + NO2                                                   ', &
     '    RA16OOH + OH --> CARB3 + UDCARB11 + OH                                                          ', &
     '         RA16OOH --> CARB3 + UDCARB11 + OH + HO2                                                    ', &
     '   UDCARB11 + OH --> RN10O2                                                                         ', &
     '   UDCARB11 + OH --> ANHY + CH3O2                                                                   ', &
     '        UDCARB11 --> RN10O2 + HO2                                                                   ', &
     '        UDCARB11 --> ANHY + CH3O2 + HO2                                                             ', &
     '      CARB6 + OH --> CO + CH3CO3                                                                    ', &
     '           CARB6 --> CO + CH3CO3 + HO2                                                              ', &
     '   RAROH17 + NO2 --> ARNOH17                                                                        ', &
     '    RU14NO3 + OH --> UCARB12 + NO2                                                                  ', &
     '    RU14OOH + OH --> UCARB12 + OH                                                                   ', &
     '         RU14OOH --> UCARB12 + OH + HO2                                                             ', &
     '         RU14OOH --> UCARB10 + HCHO + OH + HO2                                                      ', &
     '    UCARB12 + OH --> RU12O2                                                                         ', &
     '    UCARB12 + O3 --> CO + HOCH2CHO + CH3CO3 + OH                                                    ', &
     '    UCARB12 + O3 --> H2O2 + CARB6 + HOCH2CHO                                                        ', &
     '   UCARB12 + NO3 --> HNO3 + RU12O2                                                                  ', &
     '         UCARB12 --> CO + HOCH2CHO + CH3CO3 + HO2                                                   ', &
     '   NRU14OOH + OH --> NUCARB12 + OH                                                                  ', &
     '        NRU14OOH --> NUCARB12 + OH + HO2                                                            ', &
     '   NUCARB12 + OH --> NRU12O2                                                                        ', &
     '        NUCARB12 --> NOA + 2 CO + 2 HO2                                                             ', &
     '    RU10O2 + NO2 --> MPAN                                                                           ', &
     '          RU10O2 --> HOCH2CHO + CH3CO3                                                              ', &
     '    RU10O2 + HO2 --> RU10OOH                                                                        ', &
     '          RU10O2 --> CARB6 + HCHO + HO2                                                             ', &
     '          RU10O2 --> CARB7 + HCHO + HO2                                                             ', &
     '     RU10O2 + NO --> HOCH2CHO + CH3CO3 + NO2                                                        ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_6 = (/ &
     '    RU10O2 + NO3 --> HOCH2CHO + CH3CO3 + NO2                                                        ', &
     '     RU10O2 + NO --> CARB7 + HCHO + HO2 + NO2                                                       ', &
     '     RU10O2 + NO --> CARB6 + HCHO + HO2 + NO2                                                       ', &
     '    RU10O2 + NO3 --> CARB7 + HCHO + HO2 + NO2                                                       ', &
     '    RU10O2 + NO3 --> CARB6 + HCHO + HO2 + NO2                                                       ', &
     '          CH3CO3 --> CH3O2                                                                          ', &
     '    CH3CO3 + NO2 --> PAN                                                                            ', &
     '    CH3CO3 + HO2 --> CH3CO3H                                                                        ', &
     '     CH3CO3 + NO --> CH3O2 + NO2                                                                    ', &
     '    CH3CO3 + NO3 --> CH3O2 + NO2                                                                    ', &
     '     OH + CH3CHO --> CH3CO3                                                                         ', &
     '          CH3CHO --> CO + CH3O2 + HO2                                                               ', &
     '    CH3CHO + NO3 --> HNO3 + CH3CO3                                                                  ', &
     '           RN8O2 --> HCHO + CH3CO3                                                                  ', &
     '     RN8O2 + HO2 --> RN8OOH                                                                         ', &
     '      RN8O2 + NO --> HCHO + CH3CO3 + NO2                                                            ', &
     '     RN8O2 + NO3 --> HCHO + CH3CO3 + NO2                                                            ', &
     '           CH3O2 --> CH3OH                                                                          ', &
     '      CH3O2 + NO --> CH3NO3                                                                         ', &
     '           CH3O2 --> HCHO                                                                           ', &
     '           CH3O2 --> HCHO + HO2                                                                     ', &
     '     CH3O2 + HO2 --> CH3OOH                                                                         ', &
     '      CH3O2 + NO --> HCHO + HO2 + NO2                                                               ', &
     '     CH3O2 + NO3 --> HCHO + HO2 + NO2                                                               ', &
     '    C2H5NO3 + OH --> NO2 + CH3CHO                                                                   ', &
     '         C2H5NO3 --> HO2 + NO2 + CH3CHO                                                             ', &
     '     C2H5OH + OH --> HOCH2CH2O2                                                                     ', &
     '     C2H5OH + OH --> HO2 + CH3CHO                                                                   ', &
     '    C2H5OOH + OH --> OH + CH3CHO                                                                    ', &
     '         C2H5OOH --> OH + HO2 + CH3CHO                                                              ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_7 = (/ &
     '    RI14O2 + HO2 --> RI14OOH                                                                        ', &
     '          RI14O2 --> CH3COCH3 + CH3CO3                                                              ', &
     '     RI14O2 + NO --> CH3COCH3 + CH3CO3 + NO2                                                        ', &
     '     RI14O2 + NO --> C2H5CO3 + NO2 + CH3CHO                                                         ', &
     '    RI14O2 + NO3 --> CH3COCH3 + CH3CO3 + NO2                                                        ', &
     '    RI14O2 + NO3 --> C2H5CO3 + NO2 + CH3CHO                                                         ', &
     '         IC3H7O2 --> IPROPOL                                                                        ', &
     '         IC3H7O2 --> CH3COCH3                                                                       ', &
     '    IC3H7O2 + NO --> IC3H7NO3                                                                       ', &
     '         IC3H7O2 --> CH3COCH3 + HO2                                                                 ', &
     '   IC3H7O2 + HO2 --> IC3H7OOH                                                                       ', &
     '    IC3H7O2 + NO --> CH3COCH3 + HO2 + NO2                                                           ', &
     '   IC3H7O2 + NO3 --> CH3COCH3 + HO2 + NO2                                                           ', &
     '  HOCH2CO3 + HO2 --> HOCH2CO3H                                                                      ', &
     '        HOCH2CO3 --> HCHO + HO2                                                                     ', &
     '  HOCH2CO3 + NO2 --> PHAN                                                                           ', &
     '   HOCH2CO3 + NO --> HCHO + HO2 + NO2                                                               ', &
     '  HOCH2CO3 + NO3 --> HCHO + HO2 + NO2                                                               ', &
     '       ANHY + OH --> HOCH2CH2O2                                                                     ', &
     '    ARNOH14 + OH --> CARB13 + NO2                                                                   ', &
     '   ARNOH14 + NO3 --> HNO3 + CARB13 + NO2                                                            ', &
     '          RN10O2 --> NPROPOL                                                                        ', &
     '          RN10O2 --> C2H5CHO                                                                        ', &
     '     RN10O2 + NO --> RN10NO3                                                                        ', &
     '    RN10O2 + HO2 --> RN10OOH                                                                        ', &
     '          RN10O2 --> C2H5CHO + HO2                                                                  ', &
     '     RN10O2 + NO --> C2H5CHO + HO2 + NO2                                                            ', &
     '    RN10O2 + NO3 --> C2H5CHO + HO2 + NO2                                                            ', &
     '    ARNOH17 + OH --> CARB16 + NO2                                                                   ', &
     '   ARNOH17 + NO3 --> CARB16 + HNO3 + NO2                                                            ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_8 = (/ &
     '    RU12O2 + NO2 --> RU12PAN                                                                        ', &
     '    RU12O2 + HO2 --> RU12OOH                                                                        ', &
     '          RU12O2 --> HOCH2CHO + CH3CO3                                                              ', &
     '          RU12O2 --> CARB7 + HOCH2CHO + HO2                                                         ', &
     '     RU12O2 + NO --> CARB7 + CO + HO2 + NO2                                                         ', &
     '     RU12O2 + NO --> HOCH2CHO + CH3CO3 + NO2                                                        ', &
     '    RU12O2 + NO3 --> CARB7 + CO + HO2 + NO2                                                         ', &
     '    RU12O2 + NO3 --> HOCH2CHO + CH3CO3 + NO2                                                        ', &
     '   NRU12O2 + HO2 --> NRU12OOH                                                                       ', &
     '         NRU12O2 --> NOA + CO + HO2                                                                 ', &
     '    NRU12O2 + NO --> NOA + CO + HO2 + NO2                                                           ', &
     '   NRU12O2 + NO3 --> NOA + CO + HO2 + NO2                                                           ', &
     '        NOA + OH --> CARB6 + NO2                                                                    ', &
     '             NOA --> HCHO + CH3CO3 + NO2                                                            ', &
     '            MPAN --> RU10O2 + NO2                                                                   ', &
     '       MPAN + OH --> CARB7 + CO + NO2                                                               ', &
     '    RU10OOH + OH --> RU10O2                                                                         ', &
     '         RU10OOH --> HOCH2CHO + CH3CO3 + OH                                                         ', &
     '      CARB7 + OH --> CARB6 + HO2                                                                    ', &
     '           CARB7 --> HCHO + CH3CO3 + HO2                                                            ', &
     '             PAN --> CH3CO3 + NO2                                                                   ', &
     '        PAN + OH --> CO + HCHO + NO2                                                                ', &
     '         CH3CO3H --> CH3O2 + OH                                                                     ', &
     '    CH3CO3H + OH --> CH3CO3                                                                         ', &
     '          RN8OOH --> C2H5O2 + OH                                                                    ', &
     '     RN8OOH + OH --> CARB6 + OH                                                                     ', &
     '      CH3OH + OH --> HCHO + HO2                                                                     ', &
     '     CH3NO3 + OH --> HCHO + NO2                                                                     ', &
     '          CH3NO3 --> HCHO + HO2 + NO2                                                               ', &
     '     CH3OOH + OH --> CH3O2                                                                          ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_9 = (/ &
     '     CH3OOH + OH --> HCHO + OH                                                                      ', &
     '          CH3OOH --> HCHO + OH + HO2                                                                ', &
     '    RI14OOH + OH --> RI14O2                                                                         ', &
     '         RI14OOH --> CH3COCH3 + CH3CO3 + OH                                                         ', &
     '         C2H5CO3 --> C2H5O2                                                                         ', &
     '   C2H5CO3 + NO2 --> PPN                                                                            ', &
     '   C2H5CO3 + HO2 --> C2H5CO3H                                                                       ', &
     '    C2H5CO3 + NO --> C2H5O2 + NO2                                                                   ', &
     '   C2H5CO3 + NO3 --> C2H5O2 + NO2                                                                   ', &
     '    IPROPOL + OH --> RN9O2                                                                          ', &
     '    IPROPOL + OH --> CH3COCH3 + HO2                                                                 ', &
     '   IC3H7NO3 + OH --> CH3COCH3 + NO2                                                                 ', &
     '        IC3H7NO3 --> CH3COCH3 + HO2 + NO2                                                           ', &
     '   IC3H7OOH + OH --> CH3COCH3 + OH                                                                  ', &
     '        IC3H7OOH --> CH3COCH3 + OH + HO2                                                            ', &
     '  HOCH2CO3H + OH --> HOCH2CO3                                                                       ', &
     '       HOCH2CO3H --> HCHO + OH + HO2                                                                ', &
     '            PHAN --> HOCH2CO3 + NO2                                                                 ', &
     '       PHAN + OH --> CO + HCHO + NO2                                                                ', &
     '     CARB13 + OH --> RN13O2                                                                         ', &
     '          CARB13 --> RN8O2 + HO2 + CH3CHO                                                           ', &
     '    NPROPOL + OH --> RN9O2                                                                          ', &
     '    NPROPOL + OH --> C2H5CHO + HO2                                                                  ', &
     '    C2H5CHO + OH --> C2H5CO3                                                                        ', &
     '         C2H5CHO --> CO + C2H5O2 + HO2                                                              ', &
     '   C2H5CHO + NO3 --> HNO3 + C2H5CO3                                                                 ', &
     '    RN10NO3 + OH --> C2H5CHO + NO2                                                                  ', &
     '         RN10NO3 --> C2H5CHO + HO2 + NO2                                                            ', &
     '    RN10OOH + OH --> C2H5CHO + OH                                                                   ', &
     '         RN10OOH --> C2H5CHO + OH + HO2                                                             ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_10 = (/ &
     '     CARB16 + OH --> RN16O2                                                                         ', &
     '          CARB16 --> C2H5CHO + RN8O2 + HO2                                                          ', &
     '         RU12PAN --> RU12O2 + NO2                                                                   ', &
     '    RU12PAN + OH --> UCARB10 + NO2                                                                  ', &
     '    RU12OOH + OH --> RU12O2                                                                         ', &
     '         RU12OOH --> CARB6 + HOCH2CHO + OH + HO2                                                    ', &
     '   NRU12OOH + OH --> NOA + CO + OH                                                                  ', &
     '        NRU12OOH --> NOA + CO + OH + HO2                                                            ', &
     '             PPN --> C2H5CO3 + NO2                                                                  ', &
     '        PPN + OH --> CO + NO2 + CH3CHO                                                              ', &
     '        C2H5CO3H --> C2H5O2 + OH                                                                    ', &
     '   C2H5CO3H + OH --> C2H5CO3                                                                        ', &
     '      RN9O2 + NO --> RN9NO3                                                                         ', &
     '     RN9O2 + HO2 --> RN9OOH                                                                         ', &
     '           RN9O2 --> HCHO + HO2 + CH3CHO                                                            ', &
     '      RN9O2 + NO --> HCHO + HO2 + NO2 + CH3CHO                                                      ', &
     '     RN9O2 + NO3 --> HCHO + HO2 + NO2 + CH3CHO                                                      ', &
     '     RN13O2 + NO --> RN13NO3                                                                        ', &
     '          RN13O2 --> C2H5O2 + CH3CHO                                                                ', &
     '          RN13O2 --> CARB11A + HO2                                                                  ', &
     '    RN13O2 + HO2 --> RN13OOH                                                                        ', &
     '     RN13O2 + NO --> CARB11A + HO2 + NO2                                                            ', &
     '     RN13O2 + NO --> C2H5O2 + NO2 + CH3CHO                                                          ', &
     '    RN13O2 + NO3 --> C2H5O2 + NO2 + CH3CHO                                                          ', &
     '    RN13O2 + NO3 --> CARB11A + HO2 + NO2                                                            ', &
     '          RN16O2 --> RN15AO2                                                                        ', &
     '     RN16O2 + NO --> RN16NO3                                                                        ', &
     '    RN16O2 + HO2 --> RN16OOH                                                                        ', &
     '     RN16O2 + NO --> RN15AO2 + NO2                                                                  ', &
     '    RN16O2 + NO3 --> RN15AO2 + NO2                                                                  ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_11 = (/ &
     '     RN9NO3 + OH --> CARB7 + NO2                                                                    ', &
     '     RN9OOH + OH --> CARB7 + OH                                                                     ', &
     '          RN9OOH --> HCHO + OH + HO2 + CH3CHO                                                       ', &
     '    RN13NO3 + OH --> CARB11A + NO2                                                                  ', &
     '         RN13NO3 --> C2H5O2 + NO2 + CH3CHO                                                          ', &
     '         RN13NO3 --> CARB11A + HO2 + NO2                                                            ', &
     '    CARB11A + OH --> RN11O2                                                                         ', &
     '         CARB11A --> CH3CO3 + C2H5O2                                                                ', &
     '    RN13OOH + OH --> CARB11A + OH                                                                   ', &
     '         RN13OOH --> C2H5O2 + OH + CH3CHO                                                           ', &
     '         RN13OOH --> CARB11A + OH + HO2                                                             ', &
     '    RN15AO2 + NO --> RN15NO3                                                                        ', &
     '   RN15AO2 + HO2 --> RN15OOH                                                                        ', &
     '         RN15AO2 --> CARB13 + HO2                                                                   ', &
     '    RN15AO2 + NO --> CARB13 + HO2 + NO2                                                             ', &
     '   RN15AO2 + NO3 --> CARB13 + HO2 + NO2                                                             ', &
     '         RN16NO3 --> RN15O2 + NO2                                                                   ', &
     '    RN16NO3 + OH --> CARB14 + NO2                                                                   ', &
     '         RN16OOH --> RN15AO2 + OH                                                                   ', &
     '    RN16OOH + OH --> CARB14 + OH                                                                    ', &
     '    RN11O2 + HO2 --> RN11OOH                                                                        ', &
     '          RN11O2 --> CH3CO3 + CH3CHO                                                                ', &
     '     RN11O2 + NO --> CH3CO3 + NO2 + CH3CHO                                                          ', &
     '    RN11O2 + NO3 --> CH3CO3 + NO2 + CH3CHO                                                          ', &
     '    RN15NO3 + OH --> CARB13 + NO2                                                                   ', &
     '    RN15OOH + OH --> CARB13 + OH                                                                    ', &
     '         RN15OOH --> C2H5CHO + OH + HO2 + CH3CHO                                                    ', &
     '     RN15O2 + NO --> RN15NO3                                                                        ', &
     '    RN15O2 + HO2 --> RN15OOH                                                                        ', &
     '          RN15O2 --> C2H5CHO + HO2 + CH3CHO                                                         ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(26) :: EQN_NAMES_12 = (/ &
     '     RN15O2 + NO --> C2H5CHO + HO2 + NO2 + CH3CHO                                                   ', &
     '    RN15O2 + NO3 --> C2H5CHO + HO2 + NO2 + CH3CHO                                                   ', &
     '     CARB14 + OH --> RN14O2                                                                         ', &
     '          CARB14 --> RN10O2 + CH3CO3                                                                ', &
     '         RN11OOH --> RN10O2 + OH                                                                    ', &
     '    RN11OOH + OH --> CARB9 + OH                                                                     ', &
     '    RN14O2 + HO2 --> RN14OOH                                                                        ', &
     '          RN14O2 --> C2H5CO3 + CH3CHO                                                               ', &
     '     RN14O2 + NO --> C2H5CO3 + NO2 + CH3CHO                                                         ', &
     '    RN14O2 + NO3 --> C2H5CO3 + NO2 + CH3CHO                                                         ', &
     '      CARB9 + OH --> RN9O2                                                                          ', &
     '           CARB9 --> 2 CH3CO3                                                                       ', &
     '         RN14OOH --> RN13O2 + OH                                                                    ', &
     '    RN14OOH + OH --> CARB12 + OH                                                                    ', &
     '     CARB12 + OH --> RN12O2                                                                         ', &
     '          CARB12 --> RN8O2 + CH3CO3                                                                 ', &
     '     RN12O2 + NO --> RN12NO3                                                                        ', &
     '    RN12O2 + HO2 --> RN12OOH                                                                        ', &
     '    RN12O2 + NO3 --> HO2 + NO2 + 2 CH3CHO                                                           ', &
     '     RN12O2 + NO --> HO2 + NO2 + 2 CH3CHO                                                           ', &
     '          RN12O2 --> HO2 + 2 CH3CHO                                                                 ', &
     '    RN12NO3 + OH --> CARB10 + NO2                                                                   ', &
     '    RN12OOH + OH --> CARB10 + OH                                                                    ', &
     '         RN12OOH --> OH + HO2 + 2 CH3CHO                                                            ', &
     '     CARB10 + OH --> CARB9 + HO2                                                                    ', &
     '          CARB10 --> CH3CO3 + HO2 + CH3CHO                                                          ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(386) :: EQN_NAMES = (/&
    EQN_NAMES_0, EQN_NAMES_1, EQN_NAMES_2, EQN_NAMES_3, EQN_NAMES_4, &
    EQN_NAMES_5, EQN_NAMES_6, EQN_NAMES_7, EQN_NAMES_8, EQN_NAMES_9, &
    EQN_NAMES_10, EQN_NAMES_11, EQN_NAMES_12 /)

! INLINED global variables

! End INLINED global variables


END MODULE CRI_5VOC_Monitor
