! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Parameter Module File
! 
! Generated by KPP-2.2.3 symbolic chemistry Kinetics PreProcessor
!       (http://www.cs.vt.edu/~asandu/Software/KPP)
! KPP is distributed under GPL, the general public licence
!       (http://www.gnu.org/copyleft/gpl.html)
! (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa
! (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech
!     With important contributions from:
!        M. Damian, Villanova University, USA
!        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany
! 
! File                 : CRI_5VOC_Parameters.f90
! Time                 : Tue Aug 27 15:48:09 2013
! Working directory    : /home/hes134/kpp-2.2.3/CRI_5VOC
! Equation file        : CRI_5VOC.kpp
! Output root filename : CRI_5VOC
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



MODULE CRI_5VOC_Parameters

  USE CRI_5VOC_Precision
  PUBLIC
  SAVE


! NSPEC - Number of chemical species
  INTEGER, PARAMETER :: NSPEC = 132 
! NVAR - Number of Variable species
  INTEGER, PARAMETER :: NVAR = 131 
! NVARACT - Number of Active species
  INTEGER, PARAMETER :: NVARACT = 129 
! NFIX - Number of Fixed species
  INTEGER, PARAMETER :: NFIX = 1 
! NREACT - Number of reactions
  INTEGER, PARAMETER :: NREACT = 386 
! NVARST - Starting of variables in conc. vect.
  INTEGER, PARAMETER :: NVARST = 1 
! NFIXST - Starting of fixed in conc. vect.
  INTEGER, PARAMETER :: NFIXST = 132 
! NONZERO - Number of nonzero entries in Jacobian
  INTEGER, PARAMETER :: NONZERO = 1090 
! LU_NONZERO - Number of nonzero entries in LU factoriz. of Jacobian
  INTEGER, PARAMETER :: LU_NONZERO = 1270 
! CNVAR - (NVAR+1) Number of elements in compressed row format
  INTEGER, PARAMETER :: CNVAR = 132 
! CNEQN - (NREACT+1) Number stoicm elements in compressed col format
  INTEGER, PARAMETER :: CNEQN = 387 
! NHESS - Length of Sparse Hessian
  INTEGER, PARAMETER :: NHESS = 865 
! NLOOKAT - Number of species to look at
  INTEGER, PARAMETER :: NLOOKAT = 132 
! NMONITOR - Number of species to monitor
  INTEGER, PARAMETER :: NMONITOR = 0 
! NMASS - Number of atoms to check mass balance
  INTEGER, PARAMETER :: NMASS = 1 

! Index declaration for variable species in C and VAR
!   VAR(ind_spc) = C(ind_spc)

  INTEGER, PARAMETER :: ind_NA = 1 
  INTEGER, PARAMETER :: ind_SA = 2 
  INTEGER, PARAMETER :: ind_SO3 = 3 
  INTEGER, PARAMETER :: ind_HSO3 = 4 
  INTEGER, PARAMETER :: ind_O1D = 5 
  INTEGER, PARAMETER :: ind_IC5H12 = 6 
  INTEGER, PARAMETER :: ind_TOLUENE = 7 
  INTEGER, PARAMETER :: ind_N2O5 = 8 
  INTEGER, PARAMETER :: ind_BENZENE = 9 
  INTEGER, PARAMETER :: ind_H2 = 10 
  INTEGER, PARAMETER :: ind_HONO = 11 
  INTEGER, PARAMETER :: ind_CH3OH = 12 
  INTEGER, PARAMETER :: ind_ANHY = 13 
  INTEGER, PARAMETER :: ind_SO2 = 14 
  INTEGER, PARAMETER :: ind_C2H5OH = 15 
  INTEGER, PARAMETER :: ind_HCOOH = 16 
  INTEGER, PARAMETER :: ind_AROH17 = 17 
  INTEGER, PARAMETER :: ind_RAROH17 = 18 
  INTEGER, PARAMETER :: ind_NPROPOL = 19 
  INTEGER, PARAMETER :: ind_CARB12 = 20 
  INTEGER, PARAMETER :: ind_AROH14 = 21 
  INTEGER, PARAMETER :: ind_RAROH14 = 22 
  INTEGER, PARAMETER :: ind_IPROPOL = 23 
  INTEGER, PARAMETER :: ind_NRU14OOH = 24 
  INTEGER, PARAMETER :: ind_C2H5CO3H = 25 
  INTEGER, PARAMETER :: ind_RN8OOH = 26 
  INTEGER, PARAMETER :: ind_NRN6OOH = 27 
  INTEGER, PARAMETER :: ind_HOC2H4NO3 = 28 
  INTEGER, PARAMETER :: ind_RN12NO3 = 29 
  INTEGER, PARAMETER :: ind_RN10OOH = 30 
  INTEGER, PARAMETER :: ind_IC3H7OOH = 31 
  INTEGER, PARAMETER :: ind_HO2NO2 = 32 
  INTEGER, PARAMETER :: ind_C2H5OOH = 33 
  INTEGER, PARAMETER :: ind_CARB9 = 34 
  INTEGER, PARAMETER :: ind_RU14NO3 = 35 
  INTEGER, PARAMETER :: ind_RN9NO3 = 36 
  INTEGER, PARAMETER :: ind_RN16OOH = 37 
  INTEGER, PARAMETER :: ind_CH3CO3H = 38 
  INTEGER, PARAMETER :: ind_H2O2 = 39 
  INTEGER, PARAMETER :: ind_RI14OOH = 40 
  INTEGER, PARAMETER :: ind_HOC2H4OOH = 41 
  INTEGER, PARAMETER :: ind_RA13OOH = 42 
  INTEGER, PARAMETER :: ind_IC3H7NO3 = 43 
  INTEGER, PARAMETER :: ind_RN15NO3 = 44 
  INTEGER, PARAMETER :: ind_RU12PAN = 45 
  INTEGER, PARAMETER :: ind_RN12OOH = 46 
  INTEGER, PARAMETER :: ind_RN10NO3 = 47 
  INTEGER, PARAMETER :: ind_RI16OOH = 48 
  INTEGER, PARAMETER :: ind_RN16NO3 = 49 
  INTEGER, PARAMETER :: ind_HOCH2CO3H = 50 
  INTEGER, PARAMETER :: ind_RA16OOH = 51 
  INTEGER, PARAMETER :: ind_RU10OOH = 52 
  INTEGER, PARAMETER :: ind_RN11OOH = 53 
  INTEGER, PARAMETER :: ind_CH3NO3 = 54 
  INTEGER, PARAMETER :: ind_CH3OOH = 55 
  INTEGER, PARAMETER :: ind_NRU12OOH = 56 
  INTEGER, PARAMETER :: ind_C2H5NO3 = 57 
  INTEGER, PARAMETER :: ind_PAN = 58 
  INTEGER, PARAMETER :: ind_RU12OOH = 59 
  INTEGER, PARAMETER :: ind_ARNOH14 = 60 
  INTEGER, PARAMETER :: ind_ARNOH17 = 61 
  INTEGER, PARAMETER :: ind_RU14OOH = 62 
  INTEGER, PARAMETER :: ind_PHAN = 63 
  INTEGER, PARAMETER :: ind_RA13NO3 = 64 
  INTEGER, PARAMETER :: ind_RN13OOH = 65 
  INTEGER, PARAMETER :: ind_PPN = 66 
  INTEGER, PARAMETER :: ind_RN9OOH = 67 
  INTEGER, PARAMETER :: ind_CARB16 = 68 
  INTEGER, PARAMETER :: ind_RI16NO3 = 69 
  INTEGER, PARAMETER :: ind_RA16NO3 = 70 
  INTEGER, PARAMETER :: ind_RN14OOH = 71 
  INTEGER, PARAMETER :: ind_MPAN = 72 
  INTEGER, PARAMETER :: ind_MIPK = 73 
  INTEGER, PARAMETER :: ind_CARB14 = 74 
  INTEGER, PARAMETER :: ind_RN13NO3 = 75 
  INTEGER, PARAMETER :: ind_CARB3 = 76 
  INTEGER, PARAMETER :: ind_CARB10 = 77 
  INTEGER, PARAMETER :: ind_RN15OOH = 78 
  INTEGER, PARAMETER :: ind_CARB11A = 79 
  INTEGER, PARAMETER :: ind_UDCARB8 = 80 
  INTEGER, PARAMETER :: ind_C2H4 = 81 
  INTEGER, PARAMETER :: ind_C5H8 = 82 
  INTEGER, PARAMETER :: ind_UDCARB11 = 83 
  INTEGER, PARAMETER :: ind_NUCARB12 = 84 
  INTEGER, PARAMETER :: ind_HNO3 = 85 
  INTEGER, PARAMETER :: ind_CH3COCH3 = 86 
  INTEGER, PARAMETER :: ind_NOA = 87 
  INTEGER, PARAMETER :: ind_O = 88 
  INTEGER, PARAMETER :: ind_NRN6O2 = 89 
  INTEGER, PARAMETER :: ind_RA13O2 = 90 
  INTEGER, PARAMETER :: ind_CARB13 = 91 
  INTEGER, PARAMETER :: ind_RU14O2 = 92 
  INTEGER, PARAMETER :: ind_RN12O2 = 93 
  INTEGER, PARAMETER :: ind_CARB7 = 94 
  INTEGER, PARAMETER :: ind_HOCH2CO3 = 95 
  INTEGER, PARAMETER :: ind_CO = 96 
  INTEGER, PARAMETER :: ind_RA16O2 = 97 
  INTEGER, PARAMETER :: ind_NRU12O2 = 98 
  INTEGER, PARAMETER :: ind_CARB6 = 99 
  INTEGER, PARAMETER :: ind_NRU14O2 = 100 
  INTEGER, PARAMETER :: ind_UCARB12 = 101 
  INTEGER, PARAMETER :: ind_RN10O2 = 102 
  INTEGER, PARAMETER :: ind_HOCH2CH2O2 = 103 
  INTEGER, PARAMETER :: ind_RN11O2 = 104 
  INTEGER, PARAMETER :: ind_RN15AO2 = 105 
  INTEGER, PARAMETER :: ind_IC3H7O2 = 106 
  INTEGER, PARAMETER :: ind_RN15O2 = 107 
  INTEGER, PARAMETER :: ind_C2H5CHO = 108 
  INTEGER, PARAMETER :: ind_CH3O2 = 109 
  INTEGER, PARAMETER :: ind_HOCH2CHO = 110 
  INTEGER, PARAMETER :: ind_RU10O2 = 111 
  INTEGER, PARAMETER :: ind_RU12O2 = 112 
  INTEGER, PARAMETER :: ind_O3 = 113 
  INTEGER, PARAMETER :: ind_UCARB10 = 114 
  INTEGER, PARAMETER :: ind_RI16O2 = 115 
  INTEGER, PARAMETER :: ind_RI14O2 = 116 
  INTEGER, PARAMETER :: ind_HCHO = 117 
  INTEGER, PARAMETER :: ind_RN8O2 = 118 
  INTEGER, PARAMETER :: ind_RN9O2 = 119 
  INTEGER, PARAMETER :: ind_CH3CO3 = 120 
  INTEGER, PARAMETER :: ind_RN14O2 = 121 
  INTEGER, PARAMETER :: ind_RN16O2 = 122 
  INTEGER, PARAMETER :: ind_RN13O2 = 123 
  INTEGER, PARAMETER :: ind_C2H5CO3 = 124 
  INTEGER, PARAMETER :: ind_C2H5O2 = 125 
  INTEGER, PARAMETER :: ind_OH = 126 
  INTEGER, PARAMETER :: ind_NO = 127 
  INTEGER, PARAMETER :: ind_HO2 = 128 
  INTEGER, PARAMETER :: ind_NO2 = 129 
  INTEGER, PARAMETER :: ind_CH3CHO = 130 
  INTEGER, PARAMETER :: ind_NO3 = 131 

! Index declaration for fixed species in C
!   C(ind_spc)

  INTEGER, PARAMETER :: ind_DUMMY = 132 

! Index declaration for fixed species in FIX
!    FIX(indf_spc) = C(ind_spc) = C(NVAR+indf_spc)

  INTEGER, PARAMETER :: indf_DUMMY = 1 

! NJVRP - Length of sparse Jacobian JVRP
  INTEGER, PARAMETER :: NJVRP = 643 

! NSTOICM - Length of Sparse Stoichiometric Matrix
  INTEGER, PARAMETER :: NSTOICM = 1412 

END MODULE CRI_5VOC_Parameters

