! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Linear Algebra Data and Routines File
! 
! Generated by KPP-2.2.3 symbolic chemistry Kinetics PreProcessor
!       (http://www.cs.vt.edu/~asandu/Software/KPP)
! KPP is distributed under GPL, the general public licence
!       (http://www.gnu.org/copyleft/gpl.html)
! (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa
! (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech
!     With important contributions from:
!        M. Damian, Villanova University, USA
!        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany
! 
! File                 : CRI_5VOC_LinearAlgebra.f90
! Time                 : Tue Aug 27 15:48:09 2013
! Working directory    : /home/hes134/kpp-2.2.3/CRI_5VOC
! Equation file        : CRI_5VOC.kpp
! Output root filename : CRI_5VOC
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



MODULE CRI_5VOC_LinearAlgebra

  USE CRI_5VOC_Parameters
  USE CRI_5VOC_JacobianSP

  IMPLICIT NONE

CONTAINS


! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! SPARSE_UTIL - SPARSE utility functions
!   Arguments :
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
SUBROUTINE KppDecomp( JVS, IER )
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!        Sparse LU factorization
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  USE CRI_5VOC_Parameters
  USE CRI_5VOC_JacobianSP

      INTEGER  :: IER
      REAL(kind=dp) :: JVS(LU_NONZERO), W(NVAR), a
      INTEGER  :: k, kk, j, jj

      a = 0. ! mz_rs_20050606
      IER = 0
      DO k=1,NVAR
        ! mz_rs_20050606: don't check if real value == 0
        ! IF ( JVS( LU_DIAG(k) ) .EQ. 0. ) THEN
        IF ( ABS(JVS(LU_DIAG(k))) < TINY(a) ) THEN
            IER = k
            RETURN
        END IF
        DO kk = LU_CROW(k), LU_CROW(k+1)-1
              W( LU_ICOL(kk) ) = JVS(kk)
        END DO
        DO kk = LU_CROW(k), LU_DIAG(k)-1
            j = LU_ICOL(kk)
            a = -W(j) / JVS( LU_DIAG(j) )
            W(j) = -a
            DO jj = LU_DIAG(j)+1, LU_CROW(j+1)-1
               W( LU_ICOL(jj) ) = W( LU_ICOL(jj) ) + a*JVS(jj)
            END DO
         END DO
         DO kk = LU_CROW(k), LU_CROW(k+1)-1
            JVS(kk) = W( LU_ICOL(kk) )
         END DO
      END DO
      
END SUBROUTINE KppDecomp


! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
SUBROUTINE KppDecompCmplx( JVS, IER )
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!        Sparse LU factorization, complex
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  USE CRI_5VOC_Parameters
  USE CRI_5VOC_JacobianSP

      INTEGER        :: IER
      DOUBLE COMPLEX :: JVS(LU_NONZERO), W(NVAR), a
      REAL(kind=dp)  :: b = 0.0
      INTEGER        :: k, kk, j, jj

      IER = 0
      DO k=1,NVAR
        IF ( ABS(JVS(LU_DIAG(k))) < TINY(b) ) THEN
            IER = k
            RETURN
        END IF
        DO kk = LU_CROW(k), LU_CROW(k+1)-1
              W( LU_ICOL(kk) ) = JVS(kk)
        END DO
        DO kk = LU_CROW(k), LU_DIAG(k)-1
            j = LU_ICOL(kk)
            a = -W(j) / JVS( LU_DIAG(j) )
            W(j) = -a
            DO jj = LU_DIAG(j)+1, LU_CROW(j+1)-1
               W( LU_ICOL(jj) ) = W( LU_ICOL(jj) ) + a*JVS(jj)
            END DO
         END DO
         DO kk = LU_CROW(k), LU_CROW(k+1)-1
            JVS(kk) = W( LU_ICOL(kk) )
         END DO
      END DO
      
END SUBROUTINE KppDecompCmplx


! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
SUBROUTINE KppDecompCmplxR( JVSR, JVSI, IER )
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!    Sparse LU factorization, complex
!   (Real and Imaginary parts are used instead of complex data type)     
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  USE CRI_5VOC_Parameters
  USE CRI_5VOC_JacobianSP

      INTEGER       :: IER
      REAL(kind=dp) :: JVSR(LU_NONZERO), JVSI(LU_NONZERO) 
      REAL(kind=dp) :: WR(NVAR), WI(NVAR), ar, ai, den
      INTEGER       :: k, kk, j, jj

      IER = 0
      ar  = 0.0
      DO k=1,NVAR
        IF (  ( ABS(JVSR(LU_DIAG(k))) < TINY(ar) ) .AND. &
              ( ABS(JVSI(LU_DIAG(k))) < TINY(ar) ) )  THEN
            IER = k
            RETURN
        END IF
        DO kk = LU_CROW(k), LU_CROW(k+1)-1
              WR( LU_ICOL(kk) ) = JVSR(kk)
              WI( LU_ICOL(kk) ) = JVSI(kk)
        END DO
        DO kk = LU_CROW(k), LU_DIAG(k)-1
            j = LU_ICOL(kk)
            den = JVSR(LU_DIAG(j))**2 + JVSI(LU_DIAG(j))**2
            ar = -(WR(j)*JVSR(LU_DIAG(j)) + WI(j)*JVSI(LU_DIAG(j)))/den
            ai = -(WI(j)*JVSR(LU_DIAG(j)) - WR(j)*JVSI(LU_DIAG(j)))/den
            WR(j) = -ar
            WI(j) = -ai
            DO jj = LU_DIAG(j)+1, LU_CROW(j+1)-1
               WR( LU_ICOL(jj) ) = WR( LU_ICOL(jj) ) + ar*JVSR(jj) - ai*JVSI(jj)
               WI( LU_ICOL(jj) ) = WI( LU_ICOL(jj) ) + ar*JVSI(jj) + ai*JVSR(jj)
            END DO
         END DO
         DO kk = LU_CROW(k), LU_CROW(k+1)-1
            JVSR(kk) = WR( LU_ICOL(kk) )
            JVSI(kk) = WI( LU_ICOL(kk) )
         END DO
      END DO

END SUBROUTINE KppDecompCmplxR


! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
SUBROUTINE KppSolveIndirect( JVS, X )
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!        Sparse solve subroutine using indirect addressing
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  USE CRI_5VOC_Parameters
  USE CRI_5VOC_JacobianSP

      INTEGER  :: i, j
      REAL(kind=dp) :: JVS(LU_NONZERO), X(NVAR), sum

      DO i=1,NVAR
         DO j = LU_CROW(i), LU_DIAG(i)-1 
             X(i) = X(i) - JVS(j)*X(LU_ICOL(j));
         END DO  
      END DO

      DO i=NVAR,1,-1
        sum = X(i);
        DO j = LU_DIAG(i)+1, LU_CROW(i+1)-1
          sum = sum - JVS(j)*X(LU_ICOL(j));
        END DO
        X(i) = sum/JVS(LU_DIAG(i));
      END DO
      
END SUBROUTINE KppSolveIndirect


! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
SUBROUTINE KppSolveTRIndirect( JVS, X )
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!        Complex sparse solve transpose subroutine using indirect addressing
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  USE CRI_5VOC_Parameters
  USE CRI_5VOC_JacobianSP

      INTEGER       :: i, j
      REAL(kind=dp) :: JVS(LU_NONZERO), X(NVAR)

      DO i=1,NVAR
        X(i) = X(i)/JVS(LU_DIAG(i))
	! subtract all nonzero elements in row i of JVS from X
        DO j=LU_DIAG(i)+1,LU_CROW(i+1)-1
	  X(LU_ICOL(j)) = X(LU_ICOL(j))-JVS(j)*X(i)
	END DO
      END DO

      DO i=NVAR, 1, -1
	! subtract all nonzero elements in row i of JVS from X
        DO j=LU_CROW(i),LU_DIAG(i)-1
	  X(LU_ICOL(j)) = X(LU_ICOL(j))-JVS(j)*X(i)
	END DO
      END DO
      
END SUBROUTINE KppSolveTRIndirect


! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
SUBROUTINE KppSolveCmplx( JVS, X )
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!        Complex sparse solve subroutine using indirect addressing
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  USE CRI_5VOC_Parameters
  USE CRI_5VOC_JacobianSP

      INTEGER        :: i, j
      DOUBLE COMPLEX :: JVS(LU_NONZERO), X(NVAR), sum

      DO i=1,NVAR
         DO j = LU_CROW(i), LU_DIAG(i)-1 
             X(i) = X(i) - JVS(j)*X(LU_ICOL(j));
         END DO  
      END DO

      DO i=NVAR,1,-1
        sum = X(i);
        DO j = LU_DIAG(i)+1, LU_CROW(i+1)-1
          sum = sum - JVS(j)*X(LU_ICOL(j));
        END DO
        X(i) = sum/JVS(LU_DIAG(i));
      END DO
      
END SUBROUTINE KppSolveCmplx

! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
SUBROUTINE KppSolveCmplxR( JVSR, JVSI, XR, XI )
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!   Complex sparse solve subroutine using indirect addressing
!   (Real and Imaginary parts are used instead of complex data type)     
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  USE CRI_5VOC_Parameters
  USE CRI_5VOC_JacobianSP

      INTEGER       ::  i, j
      REAL(kind=dp) ::  JVSR(LU_NONZERO), JVSI(LU_NONZERO), XR(NVAR), XI(NVAR), sumr, sumi, den

      DO i=1,NVAR
         DO j = LU_CROW(i), LU_DIAG(i)-1 
             XR(i) = XR(i) - (JVSR(j)*XR(LU_ICOL(j)) - JVSI(j)*XI(LU_ICOL(j)))
             XI(i) = XI(i) - (JVSR(j)*XI(LU_ICOL(j)) + JVSI(j)*XR(LU_ICOL(j)))
         END DO  
      END DO

      DO i=NVAR,1,-1
        sumr = XR(i); sumi = XI(i)
        DO j = LU_DIAG(i)+1, LU_CROW(i+1)-1
            sumr = sumr - (JVSR(j)*XR(LU_ICOL(j)) - JVSI(j)*XI(LU_ICOL(j)))
            sumi = sumi - (JVSR(j)*XI(LU_ICOL(j)) + JVSI(j)*XR(LU_ICOL(j)))
        END DO
        den   = JVSR(LU_DIAG(i))**2 + JVSI(LU_DIAG(i))**2
        XR(i) = (sumr*JVSR(LU_DIAG(i)) + sumi*JVSI(LU_DIAG(i)))/den
        XI(i) = (sumi*JVSR(LU_DIAG(i)) - sumr*JVSI(LU_DIAG(i)))/den
      END DO
      
END SUBROUTINE KppSolveCmplxR


! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
SUBROUTINE KppSolveTRCmplx( JVS, X )
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!        Complex sparse solve transpose subroutine using indirect addressing
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  USE CRI_5VOC_Parameters
  USE CRI_5VOC_JacobianSP

      INTEGER        :: i, j
      DOUBLE COMPLEX :: JVS(LU_NONZERO), X(NVAR)

      DO i=1,NVAR
        X(i) = X(i)/JVS(LU_DIAG(i))
	! subtract all nonzero elements in row i of JVS from X
        DO j=LU_DIAG(i)+1,LU_CROW(i+1)-1
	  X(LU_ICOL(j)) = X(LU_ICOL(j))-JVS(j)*X(i)
	END DO
      END DO

      DO i=NVAR, 1, -1
	! subtract all nonzero elements in row i of JVS from X
        DO j=LU_CROW(i),LU_DIAG(i)-1
	  X(LU_ICOL(j)) = X(LU_ICOL(j))-JVS(j)*X(i)
	END DO
      END DO
      
END SUBROUTINE KppSolveTRCmplx


! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
SUBROUTINE KppSolveTRCmplxR( JVSR, JVSI, XR, XI )
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!   Complex sparse solve transpose subroutine using indirect addressing
!   (Real and Imaginary parts are used instead of complex data type)     
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  USE CRI_5VOC_Parameters
  USE CRI_5VOC_JacobianSP

      INTEGER       ::  i, j
      REAL(kind=dp) ::  JVSR(LU_NONZERO), JVSI(LU_NONZERO), XR(NVAR), XI(NVAR), den

      DO i=1,NVAR
        den   = JVSR(LU_DIAG(i))**2 + JVSI(LU_DIAG(i))**2
        XR(i) = (XR(i)*JVSR(LU_DIAG(i)) + XI(i)*JVSI(LU_DIAG(i)))/den
        XI(i) = (XI(i)*JVSR(LU_DIAG(i)) - XR(i)*JVSI(LU_DIAG(i)))/den
	! subtract all nonzero elements in row i of JVS from X
        DO j=LU_DIAG(i)+1,LU_CROW(i+1)-1
	  XR(LU_ICOL(j)) = XR(LU_ICOL(j))-(JVSR(j)*XR(i) - JVSI(j)*XI(i))
	  XI(LU_ICOL(j)) = XI(LU_ICOL(j))-(JVSI(j)*XR(i) + JVSR(j)*XI(i))
	END DO
      END DO

      DO i=NVAR, 1, -1
	! subtract all nonzero elements in row i of JVS from X
        DO j=LU_CROW(i),LU_DIAG(i)-1
	  XR(LU_ICOL(j)) = XR(LU_ICOL(j))-(JVSR(j)*XR(i) - JVSI(j)*XI(i))
	  XI(LU_ICOL(j)) = XI(LU_ICOL(j))-(JVSI(j)*XR(i) + JVSR(j)*XI(i))
	END DO
      END DO
      
END SUBROUTINE KppSolveTRCmplxR


!
! Next few commented subroutines perform sparse big linear algebra
!
!! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!SUBROUTINE KppDecompBig( JVS, IP, IER )
!! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!!        Sparse LU factorization
!!        for the Runge Kutta (3n)x(3n) linear system
!! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!
!  USE CRI_5VOC_Parameters
!  USE CRI_5VOC_JacobianSP
!
!      INTEGER  :: IP3(3), IER, IP(3,NVAR)
!      REAL(kind=dp) :: JVS(3,3,LU_NONZERO), W(3,3,NVAR), a(3,3), E(3,3)
!      INTEGER  :: k, kk, j, jj
!
!      a = 0.0d0
!      IER = 0
!      DO k=1,NVAR
!        DO kk = LU_CROW(k), LU_CROW(k+1)-1
!              W( 1:3,1:3,LU_ICOL(kk) ) = JVS(1:3,1:3,kk)
!        END DO
!        DO kk = LU_CROW(k), LU_DIAG(k)-1
!            j = LU_ICOL(kk)
!            E(1:3,1:3) = JVS( 1:3,1:3,LU_DIAG(j) )
!            ! CALL DGETRF(3,3,E,3,IP3,IER) 
!            CALL FAC3(E,IP3,IER)
!            IF ( IER /= 0 )  RETURN
!            ! a = W(j) / JVS( LU_DIAG(j) )
!            a(1:3,1:3) = W( 1:3,1:3,j )
!            ! CALL DGETRS ('N',3,3,E,3,IP3,a,3,IER) 
!            CALL SOL3('N',E,IP3,a(1,1))
!            CALL SOL3('N',E,IP3,a(1,2))
!            CALL SOL3('N',E,IP3,a(1,3))
!            W(1:3,1:3,j) = a(1:3,1:3)
!            DO jj = LU_DIAG(j)+1, LU_CROW(j+1)-1
!               W( 1:3,1:3,LU_ICOL(jj) ) = W( 1:3,1:3,LU_ICOL(jj) ) &
!                        - MATMUL( a(1:3,1:3) , JVS(1:3,1:3,jj) )
!            END DO
!         END DO
!         DO kk = LU_CROW(k), LU_CROW(k+1)-1
!            JVS(1:3,1:3,kk) = W( 1:3,1:3,LU_ICOL(kk) )
!         END DO
!      END DO
!
!      DO k=1,NVAR
!         ! CALL WGEFA(JVS(1,1,LU_DIAG(k)),3,3,IP(1,k),IER)
!         ! CALL DGETRF(3,3,JVS(1,1,LU_DIAG(k)),3,IP(1,k),IER)
!         CALL FAC3(JVS(1,1,LU_DIAG(k)),IP(1,k),IER)
!         IF ( IER /= 0 )  RETURN
!      END DO 
!      
!END SUBROUTINE KppDecompBig
!
!
!! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!SUBROUTINE KppSolveBig( JVS, IP, X )
!! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!!        Sparse solve subroutine using indirect addressing
!!        for the Runge Kutta (3n)x(3n) linear system
!! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!
!  USE CRI_5VOC_Parameters
!  USE CRI_5VOC_JacobianSP
!
!      INTEGER  :: i, j, k, m, IP3(3), IP(3,NVAR), IER
!      REAL(kind=dp) :: JVS(3,3,LU_NONZERO), X(3,NVAR), sum(3)
!
!      DO i=1,NVAR
!        DO j = LU_CROW(i), LU_DIAG(i)-1 
!          !X(1:3,i) = X(1:3,i) - MATMUL(JVS(1:3,1:3,j),X(1:3,LU_ICOL(j)));
!          DO k=1,3
!            DO m=1,3
!	       X(k,i) = X(k,i) - JVS(k,m,j)*X(m,LU_ICOL(j))
!            END DO
!          END DO
!        END DO  
!      END DO
!
!      DO i=NVAR,1,-1
!        sum(1:3) = X(1:3,i);
!        DO j = LU_DIAG(i)+1, LU_CROW(i+1)-1
!          !sum(1:3) = sum(1:3) - MATMUL(JVS(1:3,1:3,j),X(1:3,LU_ICOL(j)));
!          DO k=1,3
!            DO m=1,3
!	       sum(k) = sum(k) - JVS(k,m,j)*X(m,LU_ICOL(j))
!            END DO
!          END DO
!        END DO
!        ! X(i) = sum/JVS(LU_DIAG(i));
!        ! CALL DGETRS ('N',3,1,JVS(1:3,1:3,LU_DIAG(i)),3,IP(1,i),sum,3,0) 
!        ! CALL WGESL('N',JVS(1,1,LU_DIAG(i)),3,3,IP(1,i),sum)
!        CALL SOL3('N',JVS(1,1,LU_DIAG(i)),IP(1,i),sum)
!        X(1:3,i) = sum(1:3)
!      END DO
!      
!END SUBROUTINE KppSolveBig
!
!
!! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!SUBROUTINE KppSolveBigTR( JVS, IP, X )
!! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!!        Big sparse transpose solve using indirect addressing
!! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!
!  USE CRI_5VOC_Parameters
!  USE CRI_5VOC_JacobianSP
!
!      INTEGER       :: i, j, k, m, IP(3,NVAR)
!      REAL(kind=dp) :: JVS(3,3,LU_NONZERO), X(3,NVAR)
!
!      DO i=1,NVAR
!        ! X(i) = X(i)/JVS(LU_DIAG(i))
!        CALL SOL3('T',JVS(1,1,LU_DIAG(i)),IP(1,i),X(1,i))
!        DO j=LU_DIAG(i)+1,LU_CROW(i+1)-1
!	  !X(1:3,LU_ICOL(j)) = X(1:3,LU_ICOL(j)) &
!          !    - MATMUL( TRANSPOSE(JVS(1:3,1:3,j)), X(1:3,i) )
!          DO k=1,3
!            DO m=1,3
!	       X(k,LU_ICOL(j)) = X(k,LU_ICOL(j)) - JVS(m,k,j)*X(m,i)
!            END DO
!          END DO
!	END DO
!      END DO
!
!      DO i=NVAR, 1, -1
!        DO j=LU_CROW(i),LU_DIAG(i)-1
!	  !X(1:3,LU_ICOL(j)) = X(1:3,LU_ICOL(j)) &
!          !   - MATMUL( TRANSPOSE(JVS(1:3,1:3,j)), X(1:3,i) )
!          DO k=1,3
!            DO m=1,3
!	       X(k,LU_ICOL(j)) = X(k,LU_ICOL(j)) - JVS(m,k,j)*X(m,i)
!            END DO
!          END DO
!	END DO
!      END DO
!      
!END SUBROUTINE KppSolveBigTR
!
!
!
!! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!SUBROUTINE FAC3(A,IPVT,INFO)
!! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!!     FAC3 FACTORS THE MATRIX A (3,3) BY
!!           GAUSS ELIMINATION WITH PARTIAL PIVOTING
!!     LINPACK - LIKE 
!!
!!     Remove comments to perform pivoting
!! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!!
!      REAL(kind=dp) :: A(3,3)
!      INTEGER       :: IPVT(3),INFO
!!      INTEGER       :: L
!!      REAL(kind=dp) :: t, dmax, da, TMP(3)
!      REAL(kind=dp), PARAMETER :: ZERO = 0.0, ONE = 1.0
!
!      info = 0
!!      t = TINY(da)
!!      
!!      da = ABS(A(1,1)); L = 1
!!      IF ( ABS(A(2,1))>da ) THEN
!!        da = ABS(A(2,1)); L = 2
!!        IF ( ABS(A(3,1))>da ) THEN
!!          L = 3
!!        END IF  
!!      END IF  
!!      IPVT(1)  = L
!!      IF (L /=1 ) THEN
!!         TMP(1:3) = A(L,1:3)
!!         A(L,1:3) = A(1,1:3)
!!         A(1,1:3) = TMP(1:3)
!!      END IF
!!      IF (ABS(A(1,1)) < t) THEN
!!         info = 1
!!         return
!!      END IF   
!!
!      A(2,1) = A(2,1)/A(1,1)
!      A(2,2) = A(2,2) - A(2,1)*A(1,2)
!      A(2,3) = A(2,3) - A(2,1)*A(1,3)
!      A(3,1) = A(3,1)/A(1,1)
!      A(3,2) = A(3,2) - A(3,1)*A(1,2)
!      A(3,3) = A(3,3) - A(3,1)*A(1,3)
!      
!!      IPVT(2)  = 2
!!      IF (ABS(A(3,2))>ABS(A(2,2))) THEN
!!         IPVT(2)  = 3
!!         TMP(2:3) = A(3,2:3)
!!         A(3,2:3) = A(2,2:3)
!!         A(2,2:3) = TMP(2:3)
!!      END IF
!!      IF (ABS(A(2,2)) < t) THEN
!!         info = 1
!!         return
!!      END IF   
!!      
!      A(3,2)   = A(3,2)/A(2,2)
!      A(3,3)   = A(3,3) - A(3,2)*A(2,3)
!      IPVT(3)  = 3
!      
!END SUBROUTINE FAC3
!
!
!! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!SUBROUTINE SOL3(Trans,A,IPVT,b)
!! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!!     SOL3 solves the system 3x3
!!     A * x = b  or  trans(a) * x = b
!!     using the factors computed by WGEFA.
!!
!!     Trans      = 'N'   to solve  A*x = b ,
!!                = 'T'   to solve  transpose(A)*x = b
!!     LINPACK - LIKE 
!!
!!     Remove comments to use pivoting
!! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!
!      CHARACTER     :: Trans
!      REAL(kind=dp) :: a(3,3),b(3)
!      INTEGER       :: IPVT(3)
!!      INTEGER       :: L
!!      REAL(kind=dp) :: TMP
!      
!      SELECT CASE (Trans)
!
!      CASE ('n','N')  !  Solve  A * x = b
!
!!     Solve  L*y = b
!!         L = IPVT(1)
!!         IF (L /= 1) THEN
!!            TMP = B(1); B(1) = B(L); B(L) = TMP
!!         END IF
!         b(2) = b(2)-A(2,1)*b(1)
!         b(3) = b(3)-A(3,1)*b(1)
!         
!!         L = IPVT(2)
!!         IF (L /= 2) THEN
!!            TMP = B(2); B(2) = B(L); B(L) = TMP
!!         END IF
!         b(3) = b(3)-A(3,2)*b(2)
!
!!     Solve  U*x = y
!         b(3) = b(3)/A(3,3)
!         b(2) = (b(2)-A(2,3)*b(3))/A(2,2)
!         b(1) = (b(1)-A(1,3)*b(3)-A(1,2)*b(2))/A(1,1)
!      
!      
!      CASE ('t','T')  !  Solve transpose(A) * x = b
!
!!      Solve transpose(U)*y = b
!         b(1) = b(1)/A(1,1)
!         b(2) = (b(2)-A(1,2)*b(1))/A(2,2)
!         b(3) = (b(3)-A(1,3)*b(1)-A(2,3)*b(2))/A(3,3)
!
!!      Solve transpose(L)*x = y
!         b(2) = b(2)-A(3,2)*b(3)
!!         L = ipvt(2)
!!         IF (L /= 2) THEN
!!            TMP = B(2); B(2) = B(L); B(L) = TMP
!!         END IF
!         b(1) = b(1)-A(3,1)*b(3)-A(2,1)*b(2)
!!         L = ipvt(1)
!!         IF (L /= 1) THEN
!!            TMP = B(1); B(1) = B(L); B(L) = TMP
!!         END IF
!   
!      END SELECT
!
!END SUBROUTINE SOL3

! End of SPARSE_UTIL function
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! KppSolve - sparse back substitution
!   Arguments :
!      JVS       - sparse Jacobian of variables
!      X         - Vector for variables
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

SUBROUTINE KppSolve ( JVS, X )

! JVS - sparse Jacobian of variables
  REAL(kind=dp) :: JVS(LU_NONZERO)
! X - Vector for variables
  REAL(kind=dp) :: X(NVAR)

  X(17) = X(17)-JVS(48)*X(7)
  X(18) = X(18)-JVS(52)*X(17)
  X(21) = X(21)-JVS(63)*X(9)
  X(22) = X(22)-JVS(67)*X(21)
  X(60) = X(60)-JVS(222)*X(22)
  X(61) = X(61)-JVS(227)*X(18)
  X(68) = X(68)-JVS(256)*X(61)
  X(74) = X(74)-JVS(282)*X(37)-JVS(283)*X(49)
  X(76) = X(76)-JVS(293)*X(42)-JVS(294)*X(51)-JVS(295)*X(64)-JVS(296)*X(70)
  X(77) = X(77)-JVS(304)*X(29)-JVS(305)*X(46)
  X(79) = X(79)-JVS(316)*X(65)-JVS(317)*X(75)
  X(80) = X(80)-JVS(324)*X(42)-JVS(325)*X(64)
  X(83) = X(83)-JVS(341)*X(51)-JVS(342)*X(70)
  X(84) = X(84)-JVS(349)*X(24)
  X(85) = X(85)-JVS(356)*X(17)-JVS(357)*X(21)-JVS(358)*X(60)-JVS(359)*X(61)
  X(86) = X(86)-JVS(370)*X(23)-JVS(371)*X(31)-JVS(372)*X(40)-JVS(373)*X(43)-JVS(374)*X(48)-JVS(375)*X(69)
  X(87) = X(87)-JVS(384)*X(56)-JVS(385)*X(84)
  X(88) = X(88)-JVS(393)*X(5)-JVS(394)*X(14)
  X(89) = X(89)-JVS(401)*X(81)
  X(90) = X(90)-JVS(408)*X(9)
  X(91) = X(91)-JVS(414)*X(44)-JVS(415)*X(60)-JVS(416)*X(78)
  X(92) = X(92)-JVS(425)*X(82)
  X(93) = X(93)-JVS(432)*X(20)-JVS(433)*X(71)
  X(94) = X(94)-JVS(440)*X(36)-JVS(441)*X(67)-JVS(442)*X(72)
  X(95) = X(95)-JVS(452)*X(50)-JVS(453)*X(63)
  X(96) = X(96)-JVS(461)*X(56)-JVS(462)*X(58)-JVS(463)*X(63)-JVS(464)*X(66)-JVS(465)*X(72)-JVS(466)*X(76)-JVS(467)*X(81)&
            &-JVS(468)*X(82)-JVS(469)*X(84)-JVS(470)*X(90)-JVS(471)*X(95)
  X(97) = X(97)-JVS(493)*X(7)
  X(98) = X(98)-JVS(499)*X(84)
  X(99) = X(99)-JVS(506)*X(26)-JVS(507)*X(59)-JVS(508)*X(87)-JVS(509)*X(94)-JVS(510)*X(97)-JVS(511)*X(98)
  X(100) = X(100)-JVS(526)*X(82)
  X(101) = X(101)-JVS(533)*X(35)-JVS(534)*X(62)-JVS(535)*X(92)
  X(102) = X(102)-JVS(542)*X(53)-JVS(543)*X(74)-JVS(544)*X(83)-JVS(545)*X(97)
  X(103) = X(103)-JVS(553)*X(13)-JVS(554)*X(15)-JVS(555)*X(80)-JVS(556)*X(81)-JVS(557)*X(83)-JVS(558)*X(90)-JVS(559)&
             &*X(97)
  X(104) = X(104)-JVS(567)*X(79)
  X(105) = X(105)-JVS(574)*X(37)
  X(106) = X(106)-JVS(581)*X(73)
  X(107) = X(107)-JVS(588)*X(49)
  X(108) = X(108)-JVS(595)*X(19)-JVS(596)*X(30)-JVS(597)*X(47)-JVS(598)*X(68)-JVS(599)*X(78)-JVS(600)*X(102)-JVS(601)&
             &*X(104)-JVS(602)*X(105)-JVS(603)*X(107)
  X(109) = X(109)-JVS(612)*X(38)-JVS(613)*X(55)-JVS(614)*X(83)-JVS(615)*X(86)-JVS(616)*X(97)-JVS(617)*X(106)
  X(110) = X(110)-JVS(627)*X(28)-JVS(628)*X(41)-JVS(629)*X(52)-JVS(630)*X(59)-JVS(631)*X(101)-JVS(632)*X(103)
  X(111) = X(111)-JVS(642)*X(52)-JVS(643)*X(72)
  X(112) = X(112)-JVS(651)*X(45)-JVS(652)*X(59)-JVS(653)*X(101)
  X(113) = X(113)-JVS(661)*X(81)-JVS(662)*X(82)-JVS(663)*X(88)-JVS(664)*X(101)
  X(114) = X(114)-JVS(672)*X(45)-JVS(673)*X(62)-JVS(674)*X(82)-JVS(675)*X(92)-JVS(676)*X(112)-JVS(677)*X(113)
  X(115) = X(115)-JVS(684)*X(6)
  X(116) = X(116)-JVS(690)*X(40)-JVS(691)*X(73)-JVS(692)*X(115)
  X(117) = X(117)-JVS(698)*X(12)-JVS(699)*X(27)-JVS(700)*X(41)-JVS(701)*X(50)-JVS(702)*X(54)-JVS(703)*X(55)-JVS(704)&
             &*X(58)-JVS(705)*X(62)-JVS(706)*X(63)-JVS(707)*X(67)-JVS(708)*X(81)-JVS(709)*X(87)-JVS(710)*X(89)-JVS(711)&
             &*X(92)-JVS(712)*X(94)-JVS(713)*X(95)-JVS(714)*X(98)-JVS(715)*X(100)-JVS(716)*X(103)-JVS(717)*X(109)-JVS(718)&
             &*X(110)-JVS(719)*X(111)-JVS(720)*X(112)-JVS(721)*X(113)-JVS(722)*X(114)-JVS(723)*X(115)-JVS(724)*X(116)
  X(118) = X(118)-JVS(736)*X(20)-JVS(737)*X(68)-JVS(738)*X(71)-JVS(739)*X(86)-JVS(740)*X(91)-JVS(741)*X(105)-JVS(742)&
             &*X(106)-JVS(743)*X(107)-JVS(744)*X(115)-JVS(745)*X(116)
  X(119) = X(119)-JVS(754)*X(19)-JVS(755)*X(23)-JVS(756)*X(34)-JVS(757)*X(53)-JVS(758)*X(77)-JVS(759)*X(93)-JVS(760)&
             &*X(102)-JVS(761)*X(104)-JVS(762)*X(106)-JVS(763)*X(115)
  X(120) = X(120)-JVS(772)*X(20)-JVS(773)*X(34)-JVS(774)*X(38)-JVS(775)*X(40)-JVS(776)*X(52)-JVS(777)*X(53)-JVS(778)&
             &*X(58)-JVS(779)*X(71)-JVS(780)*X(73)-JVS(781)*X(74)-JVS(782)*X(77)-JVS(783)*X(79)-JVS(784)*X(86)-JVS(785)&
             &*X(87)-JVS(786)*X(93)-JVS(787)*X(94)-JVS(788)*X(98)-JVS(789)*X(99)-JVS(790)*X(100)-JVS(791)*X(101)-JVS(792)&
             &*X(104)-JVS(793)*X(106)-JVS(794)*X(111)-JVS(795)*X(112)-JVS(796)*X(113)-JVS(797)*X(114)-JVS(798)*X(115)&
             &-JVS(799)*X(116)-JVS(800)*X(118)-JVS(801)*X(119)
  X(121) = X(121)-JVS(812)*X(74)
  X(122) = X(122)-JVS(819)*X(68)
  X(123) = X(123)-JVS(826)*X(71)-JVS(827)*X(91)-JVS(828)*X(105)-JVS(829)*X(107)-JVS(830)*X(121)-JVS(831)*X(122)
  X(124) = X(124)-JVS(838)*X(25)-JVS(839)*X(66)-JVS(840)*X(108)-JVS(841)*X(116)-JVS(842)*X(121)-JVS(843)*X(122)-JVS(844)&
             &*X(123)
  X(125) = X(125)-JVS(851)*X(25)-JVS(852)*X(26)-JVS(853)*X(48)-JVS(854)*X(65)-JVS(855)*X(69)-JVS(856)*X(75)-JVS(857)&
             &*X(79)-JVS(858)*X(80)-JVS(859)*X(90)-JVS(860)*X(97)-JVS(861)*X(108)-JVS(862)*X(115)-JVS(863)*X(118)-JVS(864)&
             &*X(121)-JVS(865)*X(122)-JVS(866)*X(123)-JVS(867)*X(124)
  X(126) = X(126)-JVS(874)*X(5)-JVS(875)*X(6)-JVS(876)*X(7)-JVS(877)*X(9)-JVS(878)*X(10)-JVS(879)*X(11)-JVS(880)*X(12)&
             &-JVS(881)*X(13)-JVS(882)*X(14)-JVS(883)*X(15)-JVS(884)*X(16)-JVS(885)*X(17)-JVS(886)*X(19)-JVS(887)*X(20)&
             &-JVS(888)*X(21)-JVS(889)*X(23)-JVS(890)*X(24)-JVS(891)*X(25)-JVS(892)*X(26)-JVS(893)*X(27)-JVS(894)*X(28)&
             &-JVS(895)*X(29)-JVS(896)*X(30)-JVS(897)*X(31)-JVS(898)*X(32)-JVS(899)*X(33)-JVS(900)*X(34)-JVS(901)*X(35)&
             &-JVS(902)*X(36)-JVS(903)*X(37)-JVS(904)*X(38)-JVS(905)*X(39)-JVS(906)*X(40)-JVS(907)*X(41)-JVS(908)*X(42)&
             &-JVS(909)*X(43)-JVS(910)*X(44)-JVS(911)*X(45)-JVS(912)*X(46)-JVS(913)*X(47)-JVS(914)*X(48)-JVS(915)*X(49)&
             &-JVS(916)*X(50)-JVS(917)*X(51)-JVS(918)*X(52)-JVS(919)*X(53)-JVS(920)*X(54)-JVS(921)*X(55)-JVS(922)*X(56)&
             &-JVS(923)*X(57)-JVS(924)*X(58)-JVS(925)*X(59)-JVS(926)*X(60)-JVS(927)*X(61)-JVS(928)*X(62)-JVS(929)*X(63)&
             &-JVS(930)*X(64)-JVS(931)*X(65)-JVS(932)*X(66)-JVS(933)*X(67)-JVS(934)*X(68)-JVS(935)*X(69)-JVS(936)*X(70)&
             &-JVS(937)*X(71)-JVS(938)*X(72)-JVS(939)*X(73)-JVS(940)*X(74)-JVS(941)*X(75)-JVS(942)*X(76)-JVS(943)*X(77)&
             &-JVS(944)*X(78)-JVS(945)*X(79)-JVS(946)*X(80)-JVS(947)*X(81)-JVS(948)*X(82)-JVS(949)*X(83)-JVS(950)*X(84)&
             &-JVS(951)*X(85)-JVS(952)*X(86)-JVS(953)*X(87)-JVS(954)*X(88)-JVS(955)*X(89)-JVS(956)*X(90)-JVS(957)*X(91)&
             &-JVS(958)*X(92)-JVS(959)*X(93)-JVS(960)*X(94)-JVS(961)*X(95)-JVS(962)*X(96)-JVS(963)*X(97)-JVS(964)*X(98)&
             &-JVS(965)*X(99)-JVS(966)*X(100)-JVS(967)*X(101)-JVS(968)*X(102)-JVS(969)*X(103)-JVS(970)*X(104)-JVS(971)&
             &*X(105)-JVS(972)*X(106)-JVS(973)*X(107)-JVS(974)*X(108)-JVS(975)*X(109)-JVS(976)*X(110)-JVS(977)*X(111)&
             &-JVS(978)*X(112)-JVS(979)*X(113)-JVS(980)*X(114)-JVS(981)*X(115)-JVS(982)*X(116)-JVS(983)*X(117)-JVS(984)&
             &*X(118)-JVS(985)*X(119)-JVS(986)*X(120)-JVS(987)*X(121)-JVS(988)*X(122)-JVS(989)*X(123)-JVS(990)*X(124)&
             &-JVS(991)*X(125)
  X(127) = X(127)-JVS(998)*X(11)-JVS(999)*X(88)-JVS(1000)*X(89)-JVS(1001)*X(90)-JVS(1002)*X(92)-JVS(1003)*X(93)&
             &-JVS(1004)*X(95)-JVS(1005)*X(97)-JVS(1006)*X(98)-JVS(1007)*X(100)-JVS(1008)*X(102)-JVS(1009)*X(103)-JVS(1010)&
             &*X(104)-JVS(1011)*X(105)-JVS(1012)*X(106)-JVS(1013)*X(107)-JVS(1014)*X(109)-JVS(1015)*X(110)-JVS(1016)*X(111)&
             &-JVS(1017)*X(112)-JVS(1018)*X(113)-JVS(1019)*X(114)-JVS(1020)*X(115)-JVS(1021)*X(116)-JVS(1022)*X(118)&
             &-JVS(1023)*X(119)-JVS(1024)*X(120)-JVS(1025)*X(121)-JVS(1026)*X(122)-JVS(1027)*X(123)-JVS(1028)*X(124)&
             &-JVS(1029)*X(125)-JVS(1030)*X(126)
  X(128) = X(128)-JVS(1036)*X(4)-JVS(1037)*X(7)-JVS(1038)*X(9)-JVS(1039)*X(10)-JVS(1040)*X(12)-JVS(1041)*X(14)-JVS(1042)&
             &*X(15)-JVS(1043)*X(16)-JVS(1044)*X(19)-JVS(1045)*X(23)-JVS(1046)*X(24)-JVS(1047)*X(30)-JVS(1048)*X(31)&
             &-JVS(1049)*X(32)-JVS(1050)*X(33)-JVS(1051)*X(39)-JVS(1052)*X(41)-JVS(1053)*X(42)-JVS(1054)*X(43)-JVS(1055)&
             &*X(46)-JVS(1056)*X(47)-JVS(1057)*X(50)-JVS(1058)*X(51)-JVS(1059)*X(54)-JVS(1060)*X(55)-JVS(1061)*X(56)&
             &-JVS(1062)*X(57)-JVS(1063)*X(59)-JVS(1064)*X(62)-JVS(1065)*X(64)-JVS(1066)*X(65)-JVS(1067)*X(67)-JVS(1068)&
             &*X(68)-JVS(1069)*X(70)-JVS(1070)*X(75)-JVS(1071)*X(76)-JVS(1072)*X(77)-JVS(1073)*X(78)-JVS(1074)*X(80)&
             &-JVS(1075)*X(81)-JVS(1076)*X(82)-JVS(1077)*X(83)-JVS(1078)*X(84)-JVS(1079)*X(88)-JVS(1080)*X(89)-JVS(1081)&
             &*X(90)-JVS(1082)*X(91)-JVS(1083)*X(92)-JVS(1084)*X(93)-JVS(1085)*X(94)-JVS(1086)*X(95)-JVS(1087)*X(96)&
             &-JVS(1088)*X(97)-JVS(1089)*X(98)-JVS(1090)*X(99)-JVS(1091)*X(100)-JVS(1092)*X(101)-JVS(1093)*X(102)-JVS(1094)&
             &*X(103)-JVS(1095)*X(104)-JVS(1096)*X(105)-JVS(1097)*X(106)-JVS(1098)*X(107)-JVS(1099)*X(108)-JVS(1100)*X(109)&
             &-JVS(1101)*X(110)-JVS(1102)*X(111)-JVS(1103)*X(112)-JVS(1104)*X(113)-JVS(1105)*X(114)-JVS(1106)*X(115)&
             &-JVS(1107)*X(116)-JVS(1108)*X(117)-JVS(1109)*X(118)-JVS(1110)*X(119)-JVS(1111)*X(120)-JVS(1112)*X(121)&
             &-JVS(1113)*X(122)-JVS(1114)*X(123)-JVS(1115)*X(124)-JVS(1116)*X(125)-JVS(1117)*X(126)-JVS(1118)*X(127)
  X(129) = X(129)-JVS(1123)*X(8)-JVS(1124)*X(11)-JVS(1125)*X(18)-JVS(1126)*X(22)-JVS(1127)*X(27)-JVS(1128)*X(28)&
             &-JVS(1129)*X(29)-JVS(1130)*X(32)-JVS(1131)*X(35)-JVS(1132)*X(36)-JVS(1133)*X(43)-JVS(1134)*X(44)-JVS(1135)&
             &*X(45)-JVS(1136)*X(47)-JVS(1137)*X(49)-JVS(1138)*X(54)-JVS(1139)*X(57)-JVS(1140)*X(58)-JVS(1141)*X(60)&
             &-JVS(1142)*X(61)-JVS(1143)*X(63)-JVS(1144)*X(64)-JVS(1145)*X(66)-JVS(1146)*X(69)-JVS(1147)*X(70)-JVS(1148)&
             &*X(72)-JVS(1149)*X(75)-JVS(1150)*X(85)-JVS(1151)*X(87)-JVS(1152)*X(88)-JVS(1153)*X(89)-JVS(1154)*X(90)&
             &-JVS(1155)*X(92)-JVS(1156)*X(93)-JVS(1157)*X(95)-JVS(1158)*X(97)-JVS(1159)*X(98)-JVS(1160)*X(100)-JVS(1161)&
             &*X(101)-JVS(1162)*X(102)-JVS(1163)*X(103)-JVS(1164)*X(104)-JVS(1165)*X(105)-JVS(1166)*X(106)-JVS(1167)*X(107)&
             &-JVS(1168)*X(108)-JVS(1169)*X(109)-JVS(1170)*X(110)-JVS(1171)*X(111)-JVS(1172)*X(112)-JVS(1173)*X(113)&
             &-JVS(1174)*X(114)-JVS(1175)*X(115)-JVS(1176)*X(116)-JVS(1177)*X(117)-JVS(1178)*X(118)-JVS(1179)*X(119)&
             &-JVS(1180)*X(120)-JVS(1181)*X(121)-JVS(1182)*X(122)-JVS(1183)*X(123)-JVS(1184)*X(124)-JVS(1185)*X(125)&
             &-JVS(1186)*X(126)-JVS(1187)*X(127)-JVS(1188)*X(128)
  X(130) = X(130)-JVS(1192)*X(15)-JVS(1193)*X(33)-JVS(1194)*X(46)-JVS(1195)*X(48)-JVS(1196)*X(57)-JVS(1197)*X(65)&
             &-JVS(1198)*X(66)-JVS(1199)*X(67)-JVS(1200)*X(69)-JVS(1201)*X(75)-JVS(1202)*X(77)-JVS(1203)*X(78)-JVS(1204)&
             &*X(91)-JVS(1205)*X(93)-JVS(1206)*X(104)-JVS(1207)*X(105)-JVS(1208)*X(107)-JVS(1209)*X(115)-JVS(1210)*X(116)&
             &-JVS(1211)*X(119)-JVS(1212)*X(121)-JVS(1213)*X(122)-JVS(1214)*X(123)-JVS(1215)*X(124)-JVS(1216)*X(125)&
             &-JVS(1217)*X(126)-JVS(1218)*X(127)-JVS(1219)*X(128)-JVS(1220)*X(129)
  X(131) = X(131)-JVS(1223)*X(8)-JVS(1224)*X(17)-JVS(1225)*X(21)-JVS(1226)*X(60)-JVS(1227)*X(61)-JVS(1228)*X(81)&
             &-JVS(1229)*X(82)-JVS(1230)*X(85)-JVS(1231)*X(88)-JVS(1232)*X(89)-JVS(1233)*X(90)-JVS(1234)*X(92)-JVS(1235)&
             &*X(93)-JVS(1236)*X(95)-JVS(1237)*X(97)-JVS(1238)*X(98)-JVS(1239)*X(100)-JVS(1240)*X(101)-JVS(1241)*X(102)&
             &-JVS(1242)*X(103)-JVS(1243)*X(104)-JVS(1244)*X(105)-JVS(1245)*X(106)-JVS(1246)*X(107)-JVS(1247)*X(108)&
             &-JVS(1248)*X(109)-JVS(1249)*X(110)-JVS(1250)*X(111)-JVS(1251)*X(112)-JVS(1252)*X(113)-JVS(1253)*X(114)&
             &-JVS(1254)*X(115)-JVS(1255)*X(116)-JVS(1256)*X(117)-JVS(1257)*X(118)-JVS(1258)*X(119)-JVS(1259)*X(120)&
             &-JVS(1260)*X(121)-JVS(1261)*X(122)-JVS(1262)*X(123)-JVS(1263)*X(124)-JVS(1264)*X(125)-JVS(1265)*X(126)&
             &-JVS(1266)*X(127)-JVS(1267)*X(128)-JVS(1268)*X(129)-JVS(1269)*X(130)
  X(131) = X(131)/JVS(1270)
  X(130) = (X(130)-JVS(1222)*X(131))/(JVS(1221))
  X(129) = (X(129)-JVS(1190)*X(130)-JVS(1191)*X(131))/(JVS(1189))
  X(128) = (X(128)-JVS(1120)*X(129)-JVS(1121)*X(130)-JVS(1122)*X(131))/(JVS(1119))
  X(127) = (X(127)-JVS(1032)*X(128)-JVS(1033)*X(129)-JVS(1034)*X(130)-JVS(1035)*X(131))/(JVS(1031))
  X(126) = (X(126)-JVS(993)*X(127)-JVS(994)*X(128)-JVS(995)*X(129)-JVS(996)*X(130)-JVS(997)*X(131))/(JVS(992))
  X(125) = (X(125)-JVS(869)*X(126)-JVS(870)*X(127)-JVS(871)*X(128)-JVS(872)*X(129)-JVS(873)*X(131))/(JVS(868))
  X(124) = (X(124)-JVS(846)*X(126)-JVS(847)*X(127)-JVS(848)*X(128)-JVS(849)*X(129)-JVS(850)*X(131))/(JVS(845))
  X(123) = (X(123)-JVS(833)*X(126)-JVS(834)*X(127)-JVS(835)*X(128)-JVS(836)*X(129)-JVS(837)*X(131))/(JVS(832))
  X(122) = (X(122)-JVS(821)*X(126)-JVS(822)*X(127)-JVS(823)*X(128)-JVS(824)*X(129)-JVS(825)*X(131))/(JVS(820))
  X(121) = (X(121)-JVS(814)*X(122)-JVS(815)*X(126)-JVS(816)*X(127)-JVS(817)*X(128)-JVS(818)*X(131))/(JVS(813))
  X(120) = (X(120)-JVS(803)*X(121)-JVS(804)*X(122)-JVS(805)*X(123)-JVS(806)*X(126)-JVS(807)*X(127)-JVS(808)*X(128)&
             &-JVS(809)*X(129)-JVS(810)*X(130)-JVS(811)*X(131))/(JVS(802))
  X(119) = (X(119)-JVS(765)*X(121)-JVS(766)*X(122)-JVS(767)*X(123)-JVS(768)*X(126)-JVS(769)*X(127)-JVS(770)*X(128)&
             &-JVS(771)*X(131))/(JVS(764))
  X(118) = (X(118)-JVS(747)*X(121)-JVS(748)*X(122)-JVS(749)*X(126)-JVS(750)*X(127)-JVS(751)*X(128)-JVS(752)*X(129)&
             &-JVS(753)*X(131))/(JVS(746))
  X(117) = (X(117)-JVS(726)*X(118)-JVS(727)*X(119)-JVS(728)*X(120)-JVS(729)*X(125)-JVS(730)*X(126)-JVS(731)*X(127)&
             &-JVS(732)*X(128)-JVS(733)*X(129)-JVS(734)*X(130)-JVS(735)*X(131))/(JVS(725))
  X(116) = (X(116)-JVS(694)*X(126)-JVS(695)*X(127)-JVS(696)*X(128)-JVS(697)*X(131))/(JVS(693))
  X(115) = (X(115)-JVS(686)*X(126)-JVS(687)*X(127)-JVS(688)*X(128)-JVS(689)*X(131))/(JVS(685))
  X(114) = (X(114)-JVS(679)*X(126)-JVS(680)*X(127)-JVS(681)*X(128)-JVS(682)*X(129)-JVS(683)*X(131))/(JVS(678))
  X(113) = (X(113)-JVS(666)*X(114)-JVS(667)*X(126)-JVS(668)*X(127)-JVS(669)*X(128)-JVS(670)*X(129)-JVS(671)*X(131))&
             &/(JVS(665))
  X(112) = (X(112)-JVS(655)*X(113)-JVS(656)*X(126)-JVS(657)*X(127)-JVS(658)*X(128)-JVS(659)*X(129)-JVS(660)*X(131))&
             &/(JVS(654))
  X(111) = (X(111)-JVS(645)*X(114)-JVS(646)*X(126)-JVS(647)*X(127)-JVS(648)*X(128)-JVS(649)*X(129)-JVS(650)*X(131))&
             &/(JVS(644))
  X(110) = (X(110)-JVS(634)*X(111)-JVS(635)*X(112)-JVS(636)*X(113)-JVS(637)*X(125)-JVS(638)*X(126)-JVS(639)*X(127)&
             &-JVS(640)*X(128)-JVS(641)*X(131))/(JVS(633))
  X(109) = (X(109)-JVS(619)*X(115)-JVS(620)*X(116)-JVS(621)*X(120)-JVS(622)*X(126)-JVS(623)*X(127)-JVS(624)*X(128)&
             &-JVS(625)*X(130)-JVS(626)*X(131))/(JVS(618))
  X(108) = (X(108)-JVS(605)*X(122)-JVS(606)*X(123)-JVS(607)*X(126)-JVS(608)*X(127)-JVS(609)*X(128)-JVS(610)*X(129)&
             &-JVS(611)*X(131))/(JVS(604))
  X(107) = (X(107)-JVS(590)*X(122)-JVS(591)*X(126)-JVS(592)*X(127)-JVS(593)*X(128)-JVS(594)*X(131))/(JVS(589))
  X(106) = (X(106)-JVS(583)*X(115)-JVS(584)*X(126)-JVS(585)*X(127)-JVS(586)*X(128)-JVS(587)*X(131))/(JVS(582))
  X(105) = (X(105)-JVS(576)*X(122)-JVS(577)*X(126)-JVS(578)*X(127)-JVS(579)*X(128)-JVS(580)*X(131))/(JVS(575))
  X(104) = (X(104)-JVS(569)*X(123)-JVS(570)*X(126)-JVS(571)*X(127)-JVS(572)*X(128)-JVS(573)*X(131))/(JVS(568))
  X(103) = (X(103)-JVS(561)*X(113)-JVS(562)*X(125)-JVS(563)*X(126)-JVS(564)*X(127)-JVS(565)*X(128)-JVS(566)*X(131))&
             &/(JVS(560))
  X(102) = (X(102)-JVS(547)*X(104)-JVS(548)*X(122)-JVS(549)*X(126)-JVS(550)*X(127)-JVS(551)*X(128)-JVS(552)*X(131))&
             &/(JVS(546))
  X(101) = (X(101)-JVS(537)*X(113)-JVS(538)*X(126)-JVS(539)*X(127)-JVS(540)*X(128)-JVS(541)*X(131))/(JVS(536))
  X(100) = (X(100)-JVS(528)*X(113)-JVS(529)*X(126)-JVS(530)*X(127)-JVS(531)*X(128)-JVS(532)*X(131))/(JVS(527))
  X(99) = (X(99)-JVS(513)*X(100)-JVS(514)*X(101)-JVS(515)*X(111)-JVS(516)*X(112)-JVS(517)*X(113)-JVS(518)*X(114)&
            &-JVS(519)*X(118)-JVS(520)*X(119)-JVS(521)*X(126)-JVS(522)*X(127)-JVS(523)*X(128)-JVS(524)*X(129)-JVS(525)&
            &*X(131))/(JVS(512))
  X(98) = (X(98)-JVS(501)*X(100)-JVS(502)*X(126)-JVS(503)*X(127)-JVS(504)*X(128)-JVS(505)*X(131))/(JVS(500))
  X(97) = (X(97)-JVS(495)*X(126)-JVS(496)*X(127)-JVS(497)*X(128)-JVS(498)*X(131))/(JVS(494))
  X(96) = (X(96)-JVS(473)*X(97)-JVS(474)*X(98)-JVS(475)*X(99)-JVS(476)*X(100)-JVS(477)*X(101)-JVS(478)*X(108)-JVS(479)&
            &*X(110)-JVS(480)*X(111)-JVS(481)*X(112)-JVS(482)*X(113)-JVS(483)*X(114)-JVS(484)*X(117)-JVS(485)*X(120)&
            &-JVS(486)*X(124)-JVS(487)*X(126)-JVS(488)*X(127)-JVS(489)*X(128)-JVS(490)*X(129)-JVS(491)*X(130)-JVS(492)&
            &*X(131))/(JVS(472))
  X(95) = (X(95)-JVS(455)*X(110)-JVS(456)*X(126)-JVS(457)*X(127)-JVS(458)*X(128)-JVS(459)*X(129)-JVS(460)*X(131))&
            &/(JVS(454))
  X(94) = (X(94)-JVS(444)*X(111)-JVS(445)*X(112)-JVS(446)*X(119)-JVS(447)*X(126)-JVS(448)*X(127)-JVS(449)*X(128)&
            &-JVS(450)*X(129)-JVS(451)*X(131))/(JVS(443))
  X(93) = (X(93)-JVS(435)*X(121)-JVS(436)*X(126)-JVS(437)*X(127)-JVS(438)*X(128)-JVS(439)*X(131))/(JVS(434))
  X(92) = (X(92)-JVS(427)*X(113)-JVS(428)*X(126)-JVS(429)*X(127)-JVS(430)*X(128)-JVS(431)*X(131))/(JVS(426))
  X(91) = (X(91)-JVS(418)*X(105)-JVS(419)*X(107)-JVS(420)*X(126)-JVS(421)*X(127)-JVS(422)*X(128)-JVS(423)*X(129)&
            &-JVS(424)*X(131))/(JVS(417))
  X(90) = (X(90)-JVS(410)*X(126)-JVS(411)*X(127)-JVS(412)*X(128)-JVS(413)*X(131))/(JVS(409))
  X(89) = (X(89)-JVS(403)*X(113)-JVS(404)*X(126)-JVS(405)*X(127)-JVS(406)*X(128)-JVS(407)*X(131))/(JVS(402))
  X(88) = (X(88)-JVS(396)*X(113)-JVS(397)*X(126)-JVS(398)*X(127)-JVS(399)*X(129)-JVS(400)*X(131))/(JVS(395))
  X(87) = (X(87)-JVS(387)*X(98)-JVS(388)*X(100)-JVS(389)*X(126)-JVS(390)*X(127)-JVS(391)*X(128)-JVS(392)*X(131))&
            &/(JVS(386))
  X(86) = (X(86)-JVS(377)*X(106)-JVS(378)*X(115)-JVS(379)*X(116)-JVS(380)*X(126)-JVS(381)*X(127)-JVS(382)*X(128)&
            &-JVS(383)*X(131))/(JVS(376))
  X(85) = (X(85)-JVS(361)*X(101)-JVS(362)*X(108)-JVS(363)*X(110)-JVS(364)*X(114)-JVS(365)*X(117)-JVS(366)*X(126)&
            &-JVS(367)*X(129)-JVS(368)*X(130)-JVS(369)*X(131))/(JVS(360))
  X(84) = (X(84)-JVS(351)*X(100)-JVS(352)*X(126)-JVS(353)*X(127)-JVS(354)*X(128)-JVS(355)*X(131))/(JVS(350))
  X(83) = (X(83)-JVS(344)*X(97)-JVS(345)*X(126)-JVS(346)*X(127)-JVS(347)*X(128)-JVS(348)*X(131))/(JVS(343))
  X(82) = (X(82)-JVS(338)*X(113)-JVS(339)*X(126)-JVS(340)*X(131))/(JVS(337))
  X(81) = (X(81)-JVS(334)*X(113)-JVS(335)*X(126)-JVS(336)*X(131))/(JVS(333))
  X(80) = (X(80)-JVS(327)*X(90)-JVS(328)*X(97)-JVS(329)*X(126)-JVS(330)*X(127)-JVS(331)*X(128)-JVS(332)*X(131))&
            &/(JVS(326))
  X(79) = (X(79)-JVS(319)*X(123)-JVS(320)*X(126)-JVS(321)*X(127)-JVS(322)*X(128)-JVS(323)*X(131))/(JVS(318))
  X(78) = (X(78)-JVS(312)*X(105)-JVS(313)*X(107)-JVS(314)*X(126)-JVS(315)*X(128))/(JVS(311))
  X(77) = (X(77)-JVS(307)*X(93)-JVS(308)*X(126)-JVS(309)*X(127)-JVS(310)*X(128))/(JVS(306))
  X(76) = (X(76)-JVS(298)*X(90)-JVS(299)*X(97)-JVS(300)*X(126)-JVS(301)*X(127)-JVS(302)*X(128)-JVS(303)*X(131))&
            &/(JVS(297))
  X(75) = (X(75)-JVS(290)*X(123)-JVS(291)*X(126)-JVS(292)*X(127))/(JVS(289))
  X(74) = (X(74)-JVS(285)*X(122)-JVS(286)*X(126)-JVS(287)*X(127)-JVS(288)*X(128))/(JVS(284))
  X(73) = (X(73)-JVS(278)*X(115)-JVS(279)*X(126)-JVS(280)*X(127)-JVS(281)*X(131))/(JVS(277))
  X(72) = (X(72)-JVS(274)*X(111)-JVS(275)*X(126)-JVS(276)*X(129))/(JVS(273))
  X(71) = (X(71)-JVS(270)*X(121)-JVS(271)*X(126)-JVS(272)*X(128))/(JVS(269))
  X(70) = (X(70)-JVS(266)*X(97)-JVS(267)*X(126)-JVS(268)*X(127))/(JVS(265))
  X(69) = (X(69)-JVS(262)*X(115)-JVS(263)*X(126)-JVS(264)*X(127))/(JVS(261))
  X(68) = (X(68)-JVS(258)*X(126)-JVS(259)*X(129)-JVS(260)*X(131))/(JVS(257))
  X(67) = (X(67)-JVS(253)*X(119)-JVS(254)*X(126)-JVS(255)*X(128))/(JVS(252))
  X(66) = (X(66)-JVS(249)*X(124)-JVS(250)*X(126)-JVS(251)*X(129))/(JVS(248))
  X(65) = (X(65)-JVS(245)*X(123)-JVS(246)*X(126)-JVS(247)*X(128))/(JVS(244))
  X(64) = (X(64)-JVS(241)*X(90)-JVS(242)*X(126)-JVS(243)*X(127))/(JVS(240))
  X(63) = (X(63)-JVS(237)*X(95)-JVS(238)*X(126)-JVS(239)*X(129))/(JVS(236))
  X(62) = (X(62)-JVS(233)*X(92)-JVS(234)*X(126)-JVS(235)*X(128))/(JVS(232))
  X(61) = (X(61)-JVS(229)*X(126)-JVS(230)*X(129)-JVS(231)*X(131))/(JVS(228))
  X(60) = (X(60)-JVS(224)*X(126)-JVS(225)*X(129)-JVS(226)*X(131))/(JVS(223))
  X(59) = (X(59)-JVS(219)*X(112)-JVS(220)*X(126)-JVS(221)*X(128))/(JVS(218))
  X(58) = (X(58)-JVS(215)*X(120)-JVS(216)*X(126)-JVS(217)*X(129))/(JVS(214))
  X(57) = (X(57)-JVS(211)*X(125)-JVS(212)*X(126)-JVS(213)*X(127))/(JVS(210))
  X(56) = (X(56)-JVS(207)*X(98)-JVS(208)*X(126)-JVS(209)*X(128))/(JVS(206))
  X(55) = (X(55)-JVS(203)*X(109)-JVS(204)*X(126)-JVS(205)*X(128))/(JVS(202))
  X(54) = (X(54)-JVS(199)*X(109)-JVS(200)*X(126)-JVS(201)*X(127))/(JVS(198))
  X(53) = (X(53)-JVS(195)*X(104)-JVS(196)*X(126)-JVS(197)*X(128))/(JVS(194))
  X(52) = (X(52)-JVS(191)*X(111)-JVS(192)*X(126)-JVS(193)*X(128))/(JVS(190))
  X(51) = (X(51)-JVS(187)*X(97)-JVS(188)*X(126)-JVS(189)*X(128))/(JVS(186))
  X(50) = (X(50)-JVS(183)*X(95)-JVS(184)*X(126)-JVS(185)*X(128))/(JVS(182))
  X(49) = (X(49)-JVS(179)*X(122)-JVS(180)*X(126)-JVS(181)*X(127))/(JVS(178))
  X(48) = (X(48)-JVS(175)*X(115)-JVS(176)*X(126)-JVS(177)*X(128))/(JVS(174))
  X(47) = (X(47)-JVS(171)*X(102)-JVS(172)*X(126)-JVS(173)*X(127))/(JVS(170))
  X(46) = (X(46)-JVS(167)*X(93)-JVS(168)*X(126)-JVS(169)*X(128))/(JVS(166))
  X(45) = (X(45)-JVS(163)*X(112)-JVS(164)*X(126)-JVS(165)*X(129))/(JVS(162))
  X(44) = (X(44)-JVS(158)*X(105)-JVS(159)*X(107)-JVS(160)*X(126)-JVS(161)*X(127))/(JVS(157))
  X(43) = (X(43)-JVS(154)*X(106)-JVS(155)*X(126)-JVS(156)*X(127))/(JVS(153))
  X(42) = (X(42)-JVS(150)*X(90)-JVS(151)*X(126)-JVS(152)*X(128))/(JVS(149))
  X(41) = (X(41)-JVS(146)*X(103)-JVS(147)*X(126)-JVS(148)*X(128))/(JVS(145))
  X(40) = (X(40)-JVS(142)*X(116)-JVS(143)*X(126)-JVS(144)*X(128))/(JVS(141))
  X(39) = (X(39)-JVS(136)*X(101)-JVS(137)*X(113)-JVS(138)*X(114)-JVS(139)*X(126)-JVS(140)*X(128))/(JVS(135))
  X(38) = (X(38)-JVS(132)*X(120)-JVS(133)*X(126)-JVS(134)*X(128))/(JVS(131))
  X(37) = (X(37)-JVS(128)*X(122)-JVS(129)*X(126)-JVS(130)*X(128))/(JVS(127))
  X(36) = (X(36)-JVS(124)*X(119)-JVS(125)*X(126)-JVS(126)*X(127))/(JVS(123))
  X(35) = (X(35)-JVS(120)*X(92)-JVS(121)*X(126)-JVS(122)*X(127))/(JVS(119))
  X(34) = (X(34)-JVS(116)*X(53)-JVS(117)*X(77)-JVS(118)*X(126))/(JVS(115))
  X(33) = (X(33)-JVS(112)*X(125)-JVS(113)*X(126)-JVS(114)*X(128))/(JVS(111))
  X(32) = (X(32)-JVS(108)*X(126)-JVS(109)*X(128)-JVS(110)*X(129))/(JVS(107))
  X(31) = (X(31)-JVS(104)*X(106)-JVS(105)*X(126)-JVS(106)*X(128))/(JVS(103))
  X(30) = (X(30)-JVS(100)*X(102)-JVS(101)*X(126)-JVS(102)*X(128))/(JVS(99))
  X(29) = (X(29)-JVS(96)*X(93)-JVS(97)*X(126)-JVS(98)*X(127))/(JVS(95))
  X(28) = (X(28)-JVS(92)*X(103)-JVS(93)*X(126)-JVS(94)*X(127))/(JVS(91))
  X(27) = (X(27)-JVS(88)*X(89)-JVS(89)*X(126)-JVS(90)*X(128))/(JVS(87))
  X(26) = (X(26)-JVS(84)*X(118)-JVS(85)*X(126)-JVS(86)*X(128))/(JVS(83))
  X(25) = (X(25)-JVS(80)*X(124)-JVS(81)*X(126)-JVS(82)*X(128))/(JVS(79))
  X(24) = (X(24)-JVS(76)*X(100)-JVS(77)*X(126)-JVS(78)*X(128))/(JVS(75))
  X(23) = (X(23)-JVS(73)*X(106)-JVS(74)*X(126))/(JVS(72))
  X(22) = (X(22)-JVS(69)*X(126)-JVS(70)*X(129)-JVS(71)*X(131))/(JVS(68))
  X(21) = (X(21)-JVS(65)*X(126)-JVS(66)*X(131))/(JVS(64))
  X(20) = (X(20)-JVS(61)*X(71)-JVS(62)*X(126))/(JVS(60))
  X(19) = (X(19)-JVS(58)*X(102)-JVS(59)*X(126))/(JVS(57))
  X(18) = (X(18)-JVS(54)*X(126)-JVS(55)*X(129)-JVS(56)*X(131))/(JVS(53))
  X(17) = (X(17)-JVS(50)*X(126)-JVS(51)*X(131))/(JVS(49))
  X(16) = (X(16)-JVS(44)*X(81)-JVS(45)*X(82)-JVS(46)*X(113)-JVS(47)*X(126))/(JVS(43))
  X(15) = (X(15)-JVS(41)*X(125)-JVS(42)*X(126))/(JVS(40))
  X(14) = (X(14)-JVS(38)*X(88)-JVS(39)*X(126))/(JVS(37))
  X(13) = (X(13)-JVS(34)*X(80)-JVS(35)*X(83)-JVS(36)*X(126))/(JVS(33))
  X(12) = (X(12)-JVS(31)*X(109)-JVS(32)*X(126))/(JVS(30))
  X(11) = (X(11)-JVS(28)*X(126)-JVS(29)*X(127))/(JVS(27))
  X(10) = (X(10)-JVS(25)*X(117)-JVS(26)*X(126))/(JVS(24))
  X(9) = (X(9)-JVS(23)*X(126))/(JVS(22))
  X(8) = (X(8)-JVS(20)*X(129)-JVS(21)*X(131))/(JVS(19))
  X(7) = (X(7)-JVS(18)*X(126))/(JVS(17))
  X(6) = (X(6)-JVS(16)*X(126))/(JVS(15))
  X(5) = (X(5)-JVS(14)*X(113))/(JVS(13))
  X(4) = (X(4)-JVS(11)*X(14)-JVS(12)*X(126))/(JVS(10))
  X(3) = (X(3)-JVS(7)*X(4)-JVS(8)*X(14)-JVS(9)*X(88))/(JVS(6))
  X(2) = (X(2)-JVS(5)*X(3))/(JVS(4))
  X(1) = (X(1)-JVS(2)*X(8)-JVS(3)*X(85))/(JVS(1))
      
END SUBROUTINE KppSolve

! End of KppSolve function
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! KppSolveTR - sparse, transposed back substitution
!   Arguments :
!      JVS       - sparse Jacobian of variables
!      X         - Vector for variables
!      XX        - Vector for output variables
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

SUBROUTINE KppSolveTR ( JVS, X, XX )

! JVS - sparse Jacobian of variables
  REAL(kind=dp) :: JVS(LU_NONZERO)
! X - Vector for variables
  REAL(kind=dp) :: X(NVAR)
! XX - Vector for output variables
  REAL(kind=dp) :: XX(NVAR)

  XX(1) = X(1)/JVS(1)
  XX(2) = X(2)/JVS(4)
  XX(3) = (X(3)-JVS(5)*XX(2))/(JVS(6))
  XX(4) = (X(4)-JVS(7)*XX(3))/(JVS(10))
  XX(5) = X(5)/JVS(13)
  XX(6) = X(6)/JVS(15)
  XX(7) = X(7)/JVS(17)
  XX(8) = (X(8)-JVS(2)*XX(1))/(JVS(19))
  XX(9) = X(9)/JVS(22)
  XX(10) = X(10)/JVS(24)
  XX(11) = X(11)/JVS(27)
  XX(12) = X(12)/JVS(30)
  XX(13) = X(13)/JVS(33)
  XX(14) = (X(14)-JVS(8)*XX(3)-JVS(11)*XX(4))/(JVS(37))
  XX(15) = X(15)/JVS(40)
  XX(16) = X(16)/JVS(43)
  XX(17) = X(17)/JVS(49)
  XX(18) = X(18)/JVS(53)
  XX(19) = X(19)/JVS(57)
  XX(20) = X(20)/JVS(60)
  XX(21) = X(21)/JVS(64)
  XX(22) = X(22)/JVS(68)
  XX(23) = X(23)/JVS(72)
  XX(24) = X(24)/JVS(75)
  XX(25) = X(25)/JVS(79)
  XX(26) = X(26)/JVS(83)
  XX(27) = X(27)/JVS(87)
  XX(28) = X(28)/JVS(91)
  XX(29) = X(29)/JVS(95)
  XX(30) = X(30)/JVS(99)
  XX(31) = X(31)/JVS(103)
  XX(32) = X(32)/JVS(107)
  XX(33) = X(33)/JVS(111)
  XX(34) = X(34)/JVS(115)
  XX(35) = X(35)/JVS(119)
  XX(36) = X(36)/JVS(123)
  XX(37) = X(37)/JVS(127)
  XX(38) = X(38)/JVS(131)
  XX(39) = X(39)/JVS(135)
  XX(40) = X(40)/JVS(141)
  XX(41) = X(41)/JVS(145)
  XX(42) = X(42)/JVS(149)
  XX(43) = X(43)/JVS(153)
  XX(44) = X(44)/JVS(157)
  XX(45) = X(45)/JVS(162)
  XX(46) = X(46)/JVS(166)
  XX(47) = X(47)/JVS(170)
  XX(48) = X(48)/JVS(174)
  XX(49) = X(49)/JVS(178)
  XX(50) = X(50)/JVS(182)
  XX(51) = X(51)/JVS(186)
  XX(52) = X(52)/JVS(190)
  XX(53) = (X(53)-JVS(116)*XX(34))/(JVS(194))
  XX(54) = X(54)/JVS(198)
  XX(55) = X(55)/JVS(202)
  XX(56) = X(56)/JVS(206)
  XX(57) = X(57)/JVS(210)
  XX(58) = X(58)/JVS(214)
  XX(59) = X(59)/JVS(218)
  XX(60) = X(60)/JVS(223)
  XX(61) = X(61)/JVS(228)
  XX(62) = X(62)/JVS(232)
  XX(63) = X(63)/JVS(236)
  XX(64) = X(64)/JVS(240)
  XX(65) = X(65)/JVS(244)
  XX(66) = X(66)/JVS(248)
  XX(67) = X(67)/JVS(252)
  XX(68) = X(68)/JVS(257)
  XX(69) = X(69)/JVS(261)
  XX(70) = X(70)/JVS(265)
  XX(71) = (X(71)-JVS(61)*XX(20))/(JVS(269))
  XX(72) = X(72)/JVS(273)
  XX(73) = X(73)/JVS(277)
  XX(74) = X(74)/JVS(284)
  XX(75) = X(75)/JVS(289)
  XX(76) = X(76)/JVS(297)
  XX(77) = (X(77)-JVS(117)*XX(34))/(JVS(306))
  XX(78) = X(78)/JVS(311)
  XX(79) = X(79)/JVS(318)
  XX(80) = (X(80)-JVS(34)*XX(13))/(JVS(326))
  XX(81) = (X(81)-JVS(44)*XX(16))/(JVS(333))
  XX(82) = (X(82)-JVS(45)*XX(16))/(JVS(337))
  XX(83) = (X(83)-JVS(35)*XX(13))/(JVS(343))
  XX(84) = X(84)/JVS(350)
  XX(85) = (X(85)-JVS(3)*XX(1))/(JVS(360))
  XX(86) = X(86)/JVS(376)
  XX(87) = X(87)/JVS(386)
  XX(88) = (X(88)-JVS(9)*XX(3)-JVS(38)*XX(14))/(JVS(395))
  XX(89) = (X(89)-JVS(88)*XX(27))/(JVS(402))
  XX(90) = (X(90)-JVS(150)*XX(42)-JVS(241)*XX(64)-JVS(298)*XX(76)-JVS(327)*XX(80))/(JVS(409))
  XX(91) = X(91)/JVS(417)
  XX(92) = (X(92)-JVS(120)*XX(35)-JVS(233)*XX(62))/(JVS(426))
  XX(93) = (X(93)-JVS(96)*XX(29)-JVS(167)*XX(46)-JVS(307)*XX(77))/(JVS(434))
  XX(94) = X(94)/JVS(443)
  XX(95) = (X(95)-JVS(183)*XX(50)-JVS(237)*XX(63))/(JVS(454))
  XX(96) = X(96)/JVS(472)
  XX(97) = (X(97)-JVS(187)*XX(51)-JVS(266)*XX(70)-JVS(299)*XX(76)-JVS(328)*XX(80)-JVS(344)*XX(83)-JVS(473)*XX(96))&
             &/(JVS(494))
  XX(98) = (X(98)-JVS(207)*XX(56)-JVS(387)*XX(87)-JVS(474)*XX(96))/(JVS(500))
  XX(99) = (X(99)-JVS(475)*XX(96))/(JVS(512))
  XX(100) = (X(100)-JVS(76)*XX(24)-JVS(351)*XX(84)-JVS(388)*XX(87)-JVS(476)*XX(96)-JVS(501)*XX(98)-JVS(513)*XX(99))&
              &/(JVS(527))
  XX(101) = (X(101)-JVS(136)*XX(39)-JVS(361)*XX(85)-JVS(477)*XX(96)-JVS(514)*XX(99))/(JVS(536))
  XX(102) = (X(102)-JVS(58)*XX(19)-JVS(100)*XX(30)-JVS(171)*XX(47))/(JVS(546))
  XX(103) = (X(103)-JVS(92)*XX(28)-JVS(146)*XX(41))/(JVS(560))
  XX(104) = (X(104)-JVS(195)*XX(53)-JVS(547)*XX(102))/(JVS(568))
  XX(105) = (X(105)-JVS(158)*XX(44)-JVS(312)*XX(78)-JVS(418)*XX(91))/(JVS(575))
  XX(106) = (X(106)-JVS(73)*XX(23)-JVS(104)*XX(31)-JVS(154)*XX(43)-JVS(377)*XX(86))/(JVS(582))
  XX(107) = (X(107)-JVS(159)*XX(44)-JVS(313)*XX(78)-JVS(419)*XX(91))/(JVS(589))
  XX(108) = (X(108)-JVS(362)*XX(85)-JVS(478)*XX(96))/(JVS(604))
  XX(109) = (X(109)-JVS(31)*XX(12)-JVS(199)*XX(54)-JVS(203)*XX(55))/(JVS(618))
  XX(110) = (X(110)-JVS(363)*XX(85)-JVS(455)*XX(95)-JVS(479)*XX(96))/(JVS(633))
  XX(111) = (X(111)-JVS(191)*XX(52)-JVS(274)*XX(72)-JVS(444)*XX(94)-JVS(480)*XX(96)-JVS(515)*XX(99)-JVS(634)*XX(110))&
              &/(JVS(644))
  XX(112) = (X(112)-JVS(163)*XX(45)-JVS(219)*XX(59)-JVS(445)*XX(94)-JVS(481)*XX(96)-JVS(516)*XX(99)-JVS(635)*XX(110))&
              &/(JVS(654))
  XX(113) = (X(113)-JVS(14)*XX(5)-JVS(46)*XX(16)-JVS(137)*XX(39)-JVS(334)*XX(81)-JVS(338)*XX(82)-JVS(396)*XX(88)&
              &-JVS(403)*XX(89)-JVS(427)*XX(92)-JVS(482)*XX(96)-JVS(517)*XX(99)-JVS(528)*XX(100)-JVS(537)*XX(101)-JVS(561)&
              &*XX(103)-JVS(636)*XX(110)-JVS(655)*XX(112))/(JVS(665))
  XX(114) = (X(114)-JVS(138)*XX(39)-JVS(364)*XX(85)-JVS(483)*XX(96)-JVS(518)*XX(99)-JVS(645)*XX(111)-JVS(666)*XX(113))&
              &/(JVS(678))
  XX(115) = (X(115)-JVS(175)*XX(48)-JVS(262)*XX(69)-JVS(278)*XX(73)-JVS(378)*XX(86)-JVS(583)*XX(106)-JVS(619)*XX(109))&
              &/(JVS(685))
  XX(116) = (X(116)-JVS(142)*XX(40)-JVS(379)*XX(86)-JVS(620)*XX(109))/(JVS(693))
  XX(117) = (X(117)-JVS(25)*XX(10)-JVS(365)*XX(85)-JVS(484)*XX(96))/(JVS(725))
  XX(118) = (X(118)-JVS(84)*XX(26)-JVS(519)*XX(99)-JVS(726)*XX(117))/(JVS(746))
  XX(119) = (X(119)-JVS(124)*XX(36)-JVS(253)*XX(67)-JVS(446)*XX(94)-JVS(520)*XX(99)-JVS(727)*XX(117))/(JVS(764))
  XX(120) = (X(120)-JVS(132)*XX(38)-JVS(215)*XX(58)-JVS(485)*XX(96)-JVS(621)*XX(109)-JVS(728)*XX(117))/(JVS(802))
  XX(121) = (X(121)-JVS(270)*XX(71)-JVS(435)*XX(93)-JVS(747)*XX(118)-JVS(765)*XX(119)-JVS(803)*XX(120))/(JVS(813))
  XX(122) = (X(122)-JVS(128)*XX(37)-JVS(179)*XX(49)-JVS(285)*XX(74)-JVS(548)*XX(102)-JVS(576)*XX(105)-JVS(590)*XX(107)&
              &-JVS(605)*XX(108)-JVS(748)*XX(118)-JVS(766)*XX(119)-JVS(804)*XX(120)-JVS(814)*XX(121))/(JVS(820))
  XX(123) = (X(123)-JVS(245)*XX(65)-JVS(290)*XX(75)-JVS(319)*XX(79)-JVS(569)*XX(104)-JVS(606)*XX(108)-JVS(767)*XX(119)&
              &-JVS(805)*XX(120))/(JVS(832))
  XX(124) = (X(124)-JVS(80)*XX(25)-JVS(249)*XX(66)-JVS(486)*XX(96))/(JVS(845))
  XX(125) = (X(125)-JVS(41)*XX(15)-JVS(112)*XX(33)-JVS(211)*XX(57)-JVS(562)*XX(103)-JVS(637)*XX(110)-JVS(729)*XX(117))&
              &/(JVS(868))
  XX(126) = (X(126)-JVS(12)*XX(4)-JVS(16)*XX(6)-JVS(18)*XX(7)-JVS(23)*XX(9)-JVS(26)*XX(10)-JVS(28)*XX(11)-JVS(32)*XX(12)&
              &-JVS(36)*XX(13)-JVS(39)*XX(14)-JVS(42)*XX(15)-JVS(47)*XX(16)-JVS(50)*XX(17)-JVS(54)*XX(18)-JVS(59)*XX(19)&
              &-JVS(62)*XX(20)-JVS(65)*XX(21)-JVS(69)*XX(22)-JVS(74)*XX(23)-JVS(77)*XX(24)-JVS(81)*XX(25)-JVS(85)*XX(26)&
              &-JVS(89)*XX(27)-JVS(93)*XX(28)-JVS(97)*XX(29)-JVS(101)*XX(30)-JVS(105)*XX(31)-JVS(108)*XX(32)-JVS(113)*XX(33)&
              &-JVS(118)*XX(34)-JVS(121)*XX(35)-JVS(125)*XX(36)-JVS(129)*XX(37)-JVS(133)*XX(38)-JVS(139)*XX(39)-JVS(143)&
              &*XX(40)-JVS(147)*XX(41)-JVS(151)*XX(42)-JVS(155)*XX(43)-JVS(160)*XX(44)-JVS(164)*XX(45)-JVS(168)*XX(46)&
              &-JVS(172)*XX(47)-JVS(176)*XX(48)-JVS(180)*XX(49)-JVS(184)*XX(50)-JVS(188)*XX(51)-JVS(192)*XX(52)-JVS(196)&
              &*XX(53)-JVS(200)*XX(54)-JVS(204)*XX(55)-JVS(208)*XX(56)-JVS(212)*XX(57)-JVS(216)*XX(58)-JVS(220)*XX(59)&
              &-JVS(224)*XX(60)-JVS(229)*XX(61)-JVS(234)*XX(62)-JVS(238)*XX(63)-JVS(242)*XX(64)-JVS(246)*XX(65)-JVS(250)&
              &*XX(66)-JVS(254)*XX(67)-JVS(258)*XX(68)-JVS(263)*XX(69)-JVS(267)*XX(70)-JVS(271)*XX(71)-JVS(275)*XX(72)&
              &-JVS(279)*XX(73)-JVS(286)*XX(74)-JVS(291)*XX(75)-JVS(300)*XX(76)-JVS(308)*XX(77)-JVS(314)*XX(78)-JVS(320)&
              &*XX(79)-JVS(329)*XX(80)-JVS(335)*XX(81)-JVS(339)*XX(82)-JVS(345)*XX(83)-JVS(352)*XX(84)-JVS(366)*XX(85)&
              &-JVS(380)*XX(86)-JVS(389)*XX(87)-JVS(397)*XX(88)-JVS(404)*XX(89)-JVS(410)*XX(90)-JVS(420)*XX(91)-JVS(428)&
              &*XX(92)-JVS(436)*XX(93)-JVS(447)*XX(94)-JVS(456)*XX(95)-JVS(487)*XX(96)-JVS(495)*XX(97)-JVS(502)*XX(98)&
              &-JVS(521)*XX(99)-JVS(529)*XX(100)-JVS(538)*XX(101)-JVS(549)*XX(102)-JVS(563)*XX(103)-JVS(570)*XX(104)&
              &-JVS(577)*XX(105)-JVS(584)*XX(106)-JVS(591)*XX(107)-JVS(607)*XX(108)-JVS(622)*XX(109)-JVS(638)*XX(110)&
              &-JVS(646)*XX(111)-JVS(656)*XX(112)-JVS(667)*XX(113)-JVS(679)*XX(114)-JVS(686)*XX(115)-JVS(694)*XX(116)&
              &-JVS(730)*XX(117)-JVS(749)*XX(118)-JVS(768)*XX(119)-JVS(806)*XX(120)-JVS(815)*XX(121)-JVS(821)*XX(122)&
              &-JVS(833)*XX(123)-JVS(846)*XX(124)-JVS(869)*XX(125))/(JVS(992))
  XX(127) = (X(127)-JVS(29)*XX(11)-JVS(94)*XX(28)-JVS(98)*XX(29)-JVS(122)*XX(35)-JVS(126)*XX(36)-JVS(156)*XX(43)&
              &-JVS(161)*XX(44)-JVS(173)*XX(47)-JVS(181)*XX(49)-JVS(201)*XX(54)-JVS(213)*XX(57)-JVS(243)*XX(64)-JVS(264)&
              &*XX(69)-JVS(268)*XX(70)-JVS(280)*XX(73)-JVS(287)*XX(74)-JVS(292)*XX(75)-JVS(301)*XX(76)-JVS(309)*XX(77)&
              &-JVS(321)*XX(79)-JVS(330)*XX(80)-JVS(346)*XX(83)-JVS(353)*XX(84)-JVS(381)*XX(86)-JVS(390)*XX(87)-JVS(398)&
              &*XX(88)-JVS(405)*XX(89)-JVS(411)*XX(90)-JVS(421)*XX(91)-JVS(429)*XX(92)-JVS(437)*XX(93)-JVS(448)*XX(94)&
              &-JVS(457)*XX(95)-JVS(488)*XX(96)-JVS(496)*XX(97)-JVS(503)*XX(98)-JVS(522)*XX(99)-JVS(530)*XX(100)-JVS(539)&
              &*XX(101)-JVS(550)*XX(102)-JVS(564)*XX(103)-JVS(571)*XX(104)-JVS(578)*XX(105)-JVS(585)*XX(106)-JVS(592)&
              &*XX(107)-JVS(608)*XX(108)-JVS(623)*XX(109)-JVS(639)*XX(110)-JVS(647)*XX(111)-JVS(657)*XX(112)-JVS(668)&
              &*XX(113)-JVS(680)*XX(114)-JVS(687)*XX(115)-JVS(695)*XX(116)-JVS(731)*XX(117)-JVS(750)*XX(118)-JVS(769)&
              &*XX(119)-JVS(807)*XX(120)-JVS(816)*XX(121)-JVS(822)*XX(122)-JVS(834)*XX(123)-JVS(847)*XX(124)-JVS(870)&
              &*XX(125)-JVS(993)*XX(126))/(JVS(1031))
  XX(128) = (X(128)-JVS(78)*XX(24)-JVS(82)*XX(25)-JVS(86)*XX(26)-JVS(90)*XX(27)-JVS(102)*XX(30)-JVS(106)*XX(31)-JVS(109)&
              &*XX(32)-JVS(114)*XX(33)-JVS(130)*XX(37)-JVS(134)*XX(38)-JVS(140)*XX(39)-JVS(144)*XX(40)-JVS(148)*XX(41)&
              &-JVS(152)*XX(42)-JVS(169)*XX(46)-JVS(177)*XX(48)-JVS(185)*XX(50)-JVS(189)*XX(51)-JVS(193)*XX(52)-JVS(197)&
              &*XX(53)-JVS(205)*XX(55)-JVS(209)*XX(56)-JVS(221)*XX(59)-JVS(235)*XX(62)-JVS(247)*XX(65)-JVS(255)*XX(67)&
              &-JVS(272)*XX(71)-JVS(288)*XX(74)-JVS(302)*XX(76)-JVS(310)*XX(77)-JVS(315)*XX(78)-JVS(322)*XX(79)-JVS(331)&
              &*XX(80)-JVS(347)*XX(83)-JVS(354)*XX(84)-JVS(382)*XX(86)-JVS(391)*XX(87)-JVS(406)*XX(89)-JVS(412)*XX(90)&
              &-JVS(422)*XX(91)-JVS(430)*XX(92)-JVS(438)*XX(93)-JVS(449)*XX(94)-JVS(458)*XX(95)-JVS(489)*XX(96)-JVS(497)&
              &*XX(97)-JVS(504)*XX(98)-JVS(523)*XX(99)-JVS(531)*XX(100)-JVS(540)*XX(101)-JVS(551)*XX(102)-JVS(565)*XX(103)&
              &-JVS(572)*XX(104)-JVS(579)*XX(105)-JVS(586)*XX(106)-JVS(593)*XX(107)-JVS(609)*XX(108)-JVS(624)*XX(109)&
              &-JVS(640)*XX(110)-JVS(648)*XX(111)-JVS(658)*XX(112)-JVS(669)*XX(113)-JVS(681)*XX(114)-JVS(688)*XX(115)&
              &-JVS(696)*XX(116)-JVS(732)*XX(117)-JVS(751)*XX(118)-JVS(770)*XX(119)-JVS(808)*XX(120)-JVS(817)*XX(121)&
              &-JVS(823)*XX(122)-JVS(835)*XX(123)-JVS(848)*XX(124)-JVS(871)*XX(125)-JVS(994)*XX(126)-JVS(1032)*XX(127))&
              &/(JVS(1119))
  XX(129) = (X(129)-JVS(20)*XX(8)-JVS(55)*XX(18)-JVS(70)*XX(22)-JVS(110)*XX(32)-JVS(165)*XX(45)-JVS(217)*XX(58)-JVS(225)&
              &*XX(60)-JVS(230)*XX(61)-JVS(239)*XX(63)-JVS(251)*XX(66)-JVS(259)*XX(68)-JVS(276)*XX(72)-JVS(367)*XX(85)&
              &-JVS(399)*XX(88)-JVS(423)*XX(91)-JVS(450)*XX(94)-JVS(459)*XX(95)-JVS(490)*XX(96)-JVS(524)*XX(99)-JVS(610)&
              &*XX(108)-JVS(649)*XX(111)-JVS(659)*XX(112)-JVS(670)*XX(113)-JVS(682)*XX(114)-JVS(733)*XX(117)-JVS(752)&
              &*XX(118)-JVS(809)*XX(120)-JVS(824)*XX(122)-JVS(836)*XX(123)-JVS(849)*XX(124)-JVS(872)*XX(125)-JVS(995)&
              &*XX(126)-JVS(1033)*XX(127)-JVS(1120)*XX(128))/(JVS(1189))
  XX(130) = (X(130)-JVS(368)*XX(85)-JVS(491)*XX(96)-JVS(625)*XX(109)-JVS(734)*XX(117)-JVS(810)*XX(120)-JVS(996)*XX(126)&
              &-JVS(1034)*XX(127)-JVS(1121)*XX(128)-JVS(1190)*XX(129))/(JVS(1221))
  XX(131) = (X(131)-JVS(21)*XX(8)-JVS(51)*XX(17)-JVS(56)*XX(18)-JVS(66)*XX(21)-JVS(71)*XX(22)-JVS(226)*XX(60)-JVS(231)&
              &*XX(61)-JVS(260)*XX(68)-JVS(281)*XX(73)-JVS(303)*XX(76)-JVS(323)*XX(79)-JVS(332)*XX(80)-JVS(336)*XX(81)&
              &-JVS(340)*XX(82)-JVS(348)*XX(83)-JVS(355)*XX(84)-JVS(369)*XX(85)-JVS(383)*XX(86)-JVS(392)*XX(87)-JVS(400)&
              &*XX(88)-JVS(407)*XX(89)-JVS(413)*XX(90)-JVS(424)*XX(91)-JVS(431)*XX(92)-JVS(439)*XX(93)-JVS(451)*XX(94)&
              &-JVS(460)*XX(95)-JVS(492)*XX(96)-JVS(498)*XX(97)-JVS(505)*XX(98)-JVS(525)*XX(99)-JVS(532)*XX(100)-JVS(541)&
              &*XX(101)-JVS(552)*XX(102)-JVS(566)*XX(103)-JVS(573)*XX(104)-JVS(580)*XX(105)-JVS(587)*XX(106)-JVS(594)&
              &*XX(107)-JVS(611)*XX(108)-JVS(626)*XX(109)-JVS(641)*XX(110)-JVS(650)*XX(111)-JVS(660)*XX(112)-JVS(671)&
              &*XX(113)-JVS(683)*XX(114)-JVS(689)*XX(115)-JVS(697)*XX(116)-JVS(735)*XX(117)-JVS(753)*XX(118)-JVS(771)&
              &*XX(119)-JVS(811)*XX(120)-JVS(818)*XX(121)-JVS(825)*XX(122)-JVS(837)*XX(123)-JVS(850)*XX(124)-JVS(873)&
              &*XX(125)-JVS(997)*XX(126)-JVS(1035)*XX(127)-JVS(1122)*XX(128)-JVS(1191)*XX(129)-JVS(1222)*XX(130))&
              &/(JVS(1270))
  XX(131) = XX(131)
  XX(130) = XX(130)-JVS(1269)*XX(131)
  XX(129) = XX(129)-JVS(1220)*XX(130)-JVS(1268)*XX(131)
  XX(128) = XX(128)-JVS(1188)*XX(129)-JVS(1219)*XX(130)-JVS(1267)*XX(131)
  XX(127) = XX(127)-JVS(1118)*XX(128)-JVS(1187)*XX(129)-JVS(1218)*XX(130)-JVS(1266)*XX(131)
  XX(126) = XX(126)-JVS(1030)*XX(127)-JVS(1117)*XX(128)-JVS(1186)*XX(129)-JVS(1217)*XX(130)-JVS(1265)*XX(131)
  XX(125) = XX(125)-JVS(991)*XX(126)-JVS(1029)*XX(127)-JVS(1116)*XX(128)-JVS(1185)*XX(129)-JVS(1216)*XX(130)-JVS(1264)&
              &*XX(131)
  XX(124) = XX(124)-JVS(867)*XX(125)-JVS(990)*XX(126)-JVS(1028)*XX(127)-JVS(1115)*XX(128)-JVS(1184)*XX(129)-JVS(1215)&
              &*XX(130)-JVS(1263)*XX(131)
  XX(123) = XX(123)-JVS(844)*XX(124)-JVS(866)*XX(125)-JVS(989)*XX(126)-JVS(1027)*XX(127)-JVS(1114)*XX(128)-JVS(1183)&
              &*XX(129)-JVS(1214)*XX(130)-JVS(1262)*XX(131)
  XX(122) = XX(122)-JVS(831)*XX(123)-JVS(843)*XX(124)-JVS(865)*XX(125)-JVS(988)*XX(126)-JVS(1026)*XX(127)-JVS(1113)&
              &*XX(128)-JVS(1182)*XX(129)-JVS(1213)*XX(130)-JVS(1261)*XX(131)
  XX(121) = XX(121)-JVS(830)*XX(123)-JVS(842)*XX(124)-JVS(864)*XX(125)-JVS(987)*XX(126)-JVS(1025)*XX(127)-JVS(1112)&
              &*XX(128)-JVS(1181)*XX(129)-JVS(1212)*XX(130)-JVS(1260)*XX(131)
  XX(120) = XX(120)-JVS(986)*XX(126)-JVS(1024)*XX(127)-JVS(1111)*XX(128)-JVS(1180)*XX(129)-JVS(1259)*XX(131)
  XX(119) = XX(119)-JVS(801)*XX(120)-JVS(985)*XX(126)-JVS(1023)*XX(127)-JVS(1110)*XX(128)-JVS(1179)*XX(129)-JVS(1211)&
              &*XX(130)-JVS(1258)*XX(131)
  XX(118) = XX(118)-JVS(800)*XX(120)-JVS(863)*XX(125)-JVS(984)*XX(126)-JVS(1022)*XX(127)-JVS(1109)*XX(128)-JVS(1178)&
              &*XX(129)-JVS(1257)*XX(131)
  XX(117) = XX(117)-JVS(983)*XX(126)-JVS(1108)*XX(128)-JVS(1177)*XX(129)-JVS(1256)*XX(131)
  XX(116) = XX(116)-JVS(724)*XX(117)-JVS(745)*XX(118)-JVS(799)*XX(120)-JVS(841)*XX(124)-JVS(982)*XX(126)-JVS(1021)&
              &*XX(127)-JVS(1107)*XX(128)-JVS(1176)*XX(129)-JVS(1210)*XX(130)-JVS(1255)*XX(131)
  XX(115) = XX(115)-JVS(692)*XX(116)-JVS(723)*XX(117)-JVS(744)*XX(118)-JVS(763)*XX(119)-JVS(798)*XX(120)-JVS(862)&
              &*XX(125)-JVS(981)*XX(126)-JVS(1020)*XX(127)-JVS(1106)*XX(128)-JVS(1175)*XX(129)-JVS(1209)*XX(130)-JVS(1254)&
              &*XX(131)
  XX(114) = XX(114)-JVS(722)*XX(117)-JVS(797)*XX(120)-JVS(980)*XX(126)-JVS(1019)*XX(127)-JVS(1105)*XX(128)-JVS(1174)&
              &*XX(129)-JVS(1253)*XX(131)
  XX(113) = XX(113)-JVS(677)*XX(114)-JVS(721)*XX(117)-JVS(796)*XX(120)-JVS(979)*XX(126)-JVS(1018)*XX(127)-JVS(1104)&
              &*XX(128)-JVS(1173)*XX(129)-JVS(1252)*XX(131)
  XX(112) = XX(112)-JVS(676)*XX(114)-JVS(720)*XX(117)-JVS(795)*XX(120)-JVS(978)*XX(126)-JVS(1017)*XX(127)-JVS(1103)&
              &*XX(128)-JVS(1172)*XX(129)-JVS(1251)*XX(131)
  XX(111) = XX(111)-JVS(719)*XX(117)-JVS(794)*XX(120)-JVS(977)*XX(126)-JVS(1016)*XX(127)-JVS(1102)*XX(128)-JVS(1171)&
              &*XX(129)-JVS(1250)*XX(131)
  XX(110) = XX(110)-JVS(718)*XX(117)-JVS(976)*XX(126)-JVS(1015)*XX(127)-JVS(1101)*XX(128)-JVS(1170)*XX(129)-JVS(1249)&
              &*XX(131)
  XX(109) = XX(109)-JVS(717)*XX(117)-JVS(975)*XX(126)-JVS(1014)*XX(127)-JVS(1100)*XX(128)-JVS(1169)*XX(129)-JVS(1248)&
              &*XX(131)
  XX(108) = XX(108)-JVS(840)*XX(124)-JVS(861)*XX(125)-JVS(974)*XX(126)-JVS(1099)*XX(128)-JVS(1168)*XX(129)-JVS(1247)&
              &*XX(131)
  XX(107) = XX(107)-JVS(603)*XX(108)-JVS(743)*XX(118)-JVS(829)*XX(123)-JVS(973)*XX(126)-JVS(1013)*XX(127)-JVS(1098)&
              &*XX(128)-JVS(1167)*XX(129)-JVS(1208)*XX(130)-JVS(1246)*XX(131)
  XX(106) = XX(106)-JVS(617)*XX(109)-JVS(742)*XX(118)-JVS(762)*XX(119)-JVS(793)*XX(120)-JVS(972)*XX(126)-JVS(1012)&
              &*XX(127)-JVS(1097)*XX(128)-JVS(1166)*XX(129)-JVS(1245)*XX(131)
  XX(105) = XX(105)-JVS(602)*XX(108)-JVS(741)*XX(118)-JVS(828)*XX(123)-JVS(971)*XX(126)-JVS(1011)*XX(127)-JVS(1096)&
              &*XX(128)-JVS(1165)*XX(129)-JVS(1207)*XX(130)-JVS(1244)*XX(131)
  XX(104) = XX(104)-JVS(601)*XX(108)-JVS(761)*XX(119)-JVS(792)*XX(120)-JVS(970)*XX(126)-JVS(1010)*XX(127)-JVS(1095)&
              &*XX(128)-JVS(1164)*XX(129)-JVS(1206)*XX(130)-JVS(1243)*XX(131)
  XX(103) = XX(103)-JVS(632)*XX(110)-JVS(716)*XX(117)-JVS(969)*XX(126)-JVS(1009)*XX(127)-JVS(1094)*XX(128)-JVS(1163)&
              &*XX(129)-JVS(1242)*XX(131)
  XX(102) = XX(102)-JVS(600)*XX(108)-JVS(760)*XX(119)-JVS(968)*XX(126)-JVS(1008)*XX(127)-JVS(1093)*XX(128)-JVS(1162)&
              &*XX(129)-JVS(1241)*XX(131)
  XX(101) = XX(101)-JVS(631)*XX(110)-JVS(653)*XX(112)-JVS(664)*XX(113)-JVS(791)*XX(120)-JVS(967)*XX(126)-JVS(1092)&
              &*XX(128)-JVS(1161)*XX(129)-JVS(1240)*XX(131)
  XX(100) = XX(100)-JVS(715)*XX(117)-JVS(790)*XX(120)-JVS(966)*XX(126)-JVS(1007)*XX(127)-JVS(1091)*XX(128)-JVS(1160)&
              &*XX(129)-JVS(1239)*XX(131)
  XX(99) = XX(99)-JVS(789)*XX(120)-JVS(965)*XX(126)-JVS(1090)*XX(128)
  XX(98) = XX(98)-JVS(511)*XX(99)-JVS(714)*XX(117)-JVS(788)*XX(120)-JVS(964)*XX(126)-JVS(1006)*XX(127)-JVS(1089)*XX(128)&
             &-JVS(1159)*XX(129)-JVS(1238)*XX(131)
  XX(97) = XX(97)-JVS(510)*XX(99)-JVS(545)*XX(102)-JVS(559)*XX(103)-JVS(616)*XX(109)-JVS(860)*XX(125)-JVS(963)*XX(126)&
             &-JVS(1005)*XX(127)-JVS(1088)*XX(128)-JVS(1158)*XX(129)-JVS(1237)*XX(131)
  XX(96) = XX(96)-JVS(962)*XX(126)-JVS(1087)*XX(128)
  XX(95) = XX(95)-JVS(471)*XX(96)-JVS(713)*XX(117)-JVS(961)*XX(126)-JVS(1004)*XX(127)-JVS(1086)*XX(128)-JVS(1157)&
             &*XX(129)-JVS(1236)*XX(131)
  XX(94) = XX(94)-JVS(509)*XX(99)-JVS(712)*XX(117)-JVS(787)*XX(120)-JVS(960)*XX(126)-JVS(1085)*XX(128)
  XX(93) = XX(93)-JVS(759)*XX(119)-JVS(786)*XX(120)-JVS(959)*XX(126)-JVS(1003)*XX(127)-JVS(1084)*XX(128)-JVS(1156)&
             &*XX(129)-JVS(1205)*XX(130)-JVS(1235)*XX(131)
  XX(92) = XX(92)-JVS(535)*XX(101)-JVS(675)*XX(114)-JVS(711)*XX(117)-JVS(958)*XX(126)-JVS(1002)*XX(127)-JVS(1083)&
             &*XX(128)-JVS(1155)*XX(129)-JVS(1234)*XX(131)
  XX(91) = XX(91)-JVS(740)*XX(118)-JVS(827)*XX(123)-JVS(957)*XX(126)-JVS(1082)*XX(128)-JVS(1204)*XX(130)
  XX(90) = XX(90)-JVS(470)*XX(96)-JVS(558)*XX(103)-JVS(859)*XX(125)-JVS(956)*XX(126)-JVS(1001)*XX(127)-JVS(1081)*XX(128)&
             &-JVS(1154)*XX(129)-JVS(1233)*XX(131)
  XX(89) = XX(89)-JVS(710)*XX(117)-JVS(955)*XX(126)-JVS(1000)*XX(127)-JVS(1080)*XX(128)-JVS(1153)*XX(129)-JVS(1232)&
             &*XX(131)
  XX(88) = XX(88)-JVS(663)*XX(113)-JVS(954)*XX(126)-JVS(999)*XX(127)-JVS(1079)*XX(128)-JVS(1152)*XX(129)-JVS(1231)&
             &*XX(131)
  XX(87) = XX(87)-JVS(508)*XX(99)-JVS(709)*XX(117)-JVS(785)*XX(120)-JVS(953)*XX(126)-JVS(1151)*XX(129)
  XX(86) = XX(86)-JVS(615)*XX(109)-JVS(739)*XX(118)-JVS(784)*XX(120)-JVS(952)*XX(126)
  XX(85) = XX(85)-JVS(951)*XX(126)-JVS(1150)*XX(129)-JVS(1230)*XX(131)
  XX(84) = XX(84)-JVS(385)*XX(87)-JVS(469)*XX(96)-JVS(499)*XX(98)-JVS(950)*XX(126)-JVS(1078)*XX(128)
  XX(83) = XX(83)-JVS(544)*XX(102)-JVS(557)*XX(103)-JVS(614)*XX(109)-JVS(949)*XX(126)-JVS(1077)*XX(128)
  XX(82) = XX(82)-JVS(425)*XX(92)-JVS(468)*XX(96)-JVS(526)*XX(100)-JVS(662)*XX(113)-JVS(674)*XX(114)-JVS(948)*XX(126)&
             &-JVS(1076)*XX(128)-JVS(1229)*XX(131)
  XX(81) = XX(81)-JVS(401)*XX(89)-JVS(467)*XX(96)-JVS(556)*XX(103)-JVS(661)*XX(113)-JVS(708)*XX(117)-JVS(947)*XX(126)&
             &-JVS(1075)*XX(128)-JVS(1228)*XX(131)
  XX(80) = XX(80)-JVS(555)*XX(103)-JVS(858)*XX(125)-JVS(946)*XX(126)-JVS(1074)*XX(128)
  XX(79) = XX(79)-JVS(567)*XX(104)-JVS(783)*XX(120)-JVS(857)*XX(125)-JVS(945)*XX(126)
  XX(78) = XX(78)-JVS(416)*XX(91)-JVS(599)*XX(108)-JVS(944)*XX(126)-JVS(1073)*XX(128)-JVS(1203)*XX(130)
  XX(77) = XX(77)-JVS(758)*XX(119)-JVS(782)*XX(120)-JVS(943)*XX(126)-JVS(1072)*XX(128)-JVS(1202)*XX(130)
  XX(76) = XX(76)-JVS(466)*XX(96)-JVS(942)*XX(126)-JVS(1071)*XX(128)
  XX(75) = XX(75)-JVS(317)*XX(79)-JVS(856)*XX(125)-JVS(941)*XX(126)-JVS(1070)*XX(128)-JVS(1149)*XX(129)-JVS(1201)&
             &*XX(130)
  XX(74) = XX(74)-JVS(543)*XX(102)-JVS(781)*XX(120)-JVS(812)*XX(121)-JVS(940)*XX(126)
  XX(73) = XX(73)-JVS(581)*XX(106)-JVS(691)*XX(116)-JVS(780)*XX(120)-JVS(939)*XX(126)
  XX(72) = XX(72)-JVS(442)*XX(94)-JVS(465)*XX(96)-JVS(643)*XX(111)-JVS(938)*XX(126)-JVS(1148)*XX(129)
  XX(71) = XX(71)-JVS(433)*XX(93)-JVS(738)*XX(118)-JVS(779)*XX(120)-JVS(826)*XX(123)-JVS(937)*XX(126)
  XX(70) = XX(70)-JVS(296)*XX(76)-JVS(342)*XX(83)-JVS(936)*XX(126)-JVS(1069)*XX(128)-JVS(1147)*XX(129)
  XX(69) = XX(69)-JVS(375)*XX(86)-JVS(855)*XX(125)-JVS(935)*XX(126)-JVS(1146)*XX(129)-JVS(1200)*XX(130)
  XX(68) = XX(68)-JVS(598)*XX(108)-JVS(737)*XX(118)-JVS(819)*XX(122)-JVS(934)*XX(126)-JVS(1068)*XX(128)
  XX(67) = XX(67)-JVS(441)*XX(94)-JVS(707)*XX(117)-JVS(933)*XX(126)-JVS(1067)*XX(128)-JVS(1199)*XX(130)
  XX(66) = XX(66)-JVS(464)*XX(96)-JVS(839)*XX(124)-JVS(932)*XX(126)-JVS(1145)*XX(129)-JVS(1198)*XX(130)
  XX(65) = XX(65)-JVS(316)*XX(79)-JVS(854)*XX(125)-JVS(931)*XX(126)-JVS(1066)*XX(128)-JVS(1197)*XX(130)
  XX(64) = XX(64)-JVS(295)*XX(76)-JVS(325)*XX(80)-JVS(930)*XX(126)-JVS(1065)*XX(128)-JVS(1144)*XX(129)
  XX(63) = XX(63)-JVS(453)*XX(95)-JVS(463)*XX(96)-JVS(706)*XX(117)-JVS(929)*XX(126)-JVS(1143)*XX(129)
  XX(62) = XX(62)-JVS(534)*XX(101)-JVS(673)*XX(114)-JVS(705)*XX(117)-JVS(928)*XX(126)-JVS(1064)*XX(128)
  XX(61) = XX(61)-JVS(256)*XX(68)-JVS(359)*XX(85)-JVS(927)*XX(126)-JVS(1142)*XX(129)-JVS(1227)*XX(131)
  XX(60) = XX(60)-JVS(358)*XX(85)-JVS(415)*XX(91)-JVS(926)*XX(126)-JVS(1141)*XX(129)-JVS(1226)*XX(131)
  XX(59) = XX(59)-JVS(507)*XX(99)-JVS(630)*XX(110)-JVS(652)*XX(112)-JVS(925)*XX(126)-JVS(1063)*XX(128)
  XX(58) = XX(58)-JVS(462)*XX(96)-JVS(704)*XX(117)-JVS(778)*XX(120)-JVS(924)*XX(126)-JVS(1140)*XX(129)
  XX(57) = XX(57)-JVS(923)*XX(126)-JVS(1062)*XX(128)-JVS(1139)*XX(129)-JVS(1196)*XX(130)
  XX(56) = XX(56)-JVS(384)*XX(87)-JVS(461)*XX(96)-JVS(922)*XX(126)-JVS(1061)*XX(128)
  XX(55) = XX(55)-JVS(613)*XX(109)-JVS(703)*XX(117)-JVS(921)*XX(126)-JVS(1060)*XX(128)
  XX(54) = XX(54)-JVS(702)*XX(117)-JVS(920)*XX(126)-JVS(1059)*XX(128)-JVS(1138)*XX(129)
  XX(53) = XX(53)-JVS(542)*XX(102)-JVS(757)*XX(119)-JVS(777)*XX(120)-JVS(919)*XX(126)
  XX(52) = XX(52)-JVS(629)*XX(110)-JVS(642)*XX(111)-JVS(776)*XX(120)-JVS(918)*XX(126)
  XX(51) = XX(51)-JVS(294)*XX(76)-JVS(341)*XX(83)-JVS(917)*XX(126)-JVS(1058)*XX(128)
  XX(50) = XX(50)-JVS(452)*XX(95)-JVS(701)*XX(117)-JVS(916)*XX(126)-JVS(1057)*XX(128)
  XX(49) = XX(49)-JVS(283)*XX(74)-JVS(588)*XX(107)-JVS(915)*XX(126)-JVS(1137)*XX(129)
  XX(48) = XX(48)-JVS(374)*XX(86)-JVS(853)*XX(125)-JVS(914)*XX(126)-JVS(1195)*XX(130)
  XX(47) = XX(47)-JVS(597)*XX(108)-JVS(913)*XX(126)-JVS(1056)*XX(128)-JVS(1136)*XX(129)
  XX(46) = XX(46)-JVS(305)*XX(77)-JVS(912)*XX(126)-JVS(1055)*XX(128)-JVS(1194)*XX(130)
  XX(45) = XX(45)-JVS(651)*XX(112)-JVS(672)*XX(114)-JVS(911)*XX(126)-JVS(1135)*XX(129)
  XX(44) = XX(44)-JVS(414)*XX(91)-JVS(910)*XX(126)-JVS(1134)*XX(129)
  XX(43) = XX(43)-JVS(373)*XX(86)-JVS(909)*XX(126)-JVS(1054)*XX(128)-JVS(1133)*XX(129)
  XX(42) = XX(42)-JVS(293)*XX(76)-JVS(324)*XX(80)-JVS(908)*XX(126)-JVS(1053)*XX(128)
  XX(41) = XX(41)-JVS(628)*XX(110)-JVS(700)*XX(117)-JVS(907)*XX(126)-JVS(1052)*XX(128)
  XX(40) = XX(40)-JVS(372)*XX(86)-JVS(690)*XX(116)-JVS(775)*XX(120)-JVS(906)*XX(126)
  XX(39) = XX(39)-JVS(905)*XX(126)-JVS(1051)*XX(128)
  XX(38) = XX(38)-JVS(612)*XX(109)-JVS(774)*XX(120)-JVS(904)*XX(126)
  XX(37) = XX(37)-JVS(282)*XX(74)-JVS(574)*XX(105)-JVS(903)*XX(126)
  XX(36) = XX(36)-JVS(440)*XX(94)-JVS(902)*XX(126)-JVS(1132)*XX(129)
  XX(35) = XX(35)-JVS(533)*XX(101)-JVS(901)*XX(126)-JVS(1131)*XX(129)
  XX(34) = XX(34)-JVS(756)*XX(119)-JVS(773)*XX(120)-JVS(900)*XX(126)
  XX(33) = XX(33)-JVS(899)*XX(126)-JVS(1050)*XX(128)-JVS(1193)*XX(130)
  XX(32) = XX(32)-JVS(898)*XX(126)-JVS(1049)*XX(128)-JVS(1130)*XX(129)
  XX(31) = XX(31)-JVS(371)*XX(86)-JVS(897)*XX(126)-JVS(1048)*XX(128)
  XX(30) = XX(30)-JVS(596)*XX(108)-JVS(896)*XX(126)-JVS(1047)*XX(128)
  XX(29) = XX(29)-JVS(304)*XX(77)-JVS(895)*XX(126)-JVS(1129)*XX(129)
  XX(28) = XX(28)-JVS(627)*XX(110)-JVS(894)*XX(126)-JVS(1128)*XX(129)
  XX(27) = XX(27)-JVS(699)*XX(117)-JVS(893)*XX(126)-JVS(1127)*XX(129)
  XX(26) = XX(26)-JVS(506)*XX(99)-JVS(852)*XX(125)-JVS(892)*XX(126)
  XX(25) = XX(25)-JVS(838)*XX(124)-JVS(851)*XX(125)-JVS(891)*XX(126)
  XX(24) = XX(24)-JVS(349)*XX(84)-JVS(890)*XX(126)-JVS(1046)*XX(128)
  XX(23) = XX(23)-JVS(370)*XX(86)-JVS(755)*XX(119)-JVS(889)*XX(126)-JVS(1045)*XX(128)
  XX(22) = XX(22)-JVS(222)*XX(60)-JVS(1126)*XX(129)
  XX(21) = XX(21)-JVS(67)*XX(22)-JVS(357)*XX(85)-JVS(888)*XX(126)-JVS(1225)*XX(131)
  XX(20) = XX(20)-JVS(432)*XX(93)-JVS(736)*XX(118)-JVS(772)*XX(120)-JVS(887)*XX(126)
  XX(19) = XX(19)-JVS(595)*XX(108)-JVS(754)*XX(119)-JVS(886)*XX(126)-JVS(1044)*XX(128)
  XX(18) = XX(18)-JVS(227)*XX(61)-JVS(1125)*XX(129)
  XX(17) = XX(17)-JVS(52)*XX(18)-JVS(356)*XX(85)-JVS(885)*XX(126)-JVS(1224)*XX(131)
  XX(16) = XX(16)-JVS(884)*XX(126)-JVS(1043)*XX(128)
  XX(15) = XX(15)-JVS(554)*XX(103)-JVS(883)*XX(126)-JVS(1042)*XX(128)-JVS(1192)*XX(130)
  XX(14) = XX(14)-JVS(394)*XX(88)-JVS(882)*XX(126)-JVS(1041)*XX(128)
  XX(13) = XX(13)-JVS(553)*XX(103)-JVS(881)*XX(126)
  XX(12) = XX(12)-JVS(698)*XX(117)-JVS(880)*XX(126)-JVS(1040)*XX(128)
  XX(11) = XX(11)-JVS(879)*XX(126)-JVS(998)*XX(127)-JVS(1124)*XX(129)
  XX(10) = XX(10)-JVS(878)*XX(126)-JVS(1039)*XX(128)
  XX(9) = XX(9)-JVS(63)*XX(21)-JVS(408)*XX(90)-JVS(877)*XX(126)-JVS(1038)*XX(128)
  XX(8) = XX(8)-JVS(1123)*XX(129)-JVS(1223)*XX(131)
  XX(7) = XX(7)-JVS(48)*XX(17)-JVS(493)*XX(97)-JVS(876)*XX(126)-JVS(1037)*XX(128)
  XX(6) = XX(6)-JVS(684)*XX(115)-JVS(875)*XX(126)
  XX(5) = XX(5)-JVS(393)*XX(88)-JVS(874)*XX(126)
  XX(4) = XX(4)-JVS(1036)*XX(128)
  XX(3) = XX(3)
  XX(2) = XX(2)
  XX(1) = XX(1)
      
END SUBROUTINE KppSolveTR

! End of KppSolveTR function
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! BLAS_UTIL - BLAS-LIKE utility functions
!   Arguments :
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

!--------------------------------------------------------------
!
! BLAS/LAPACK-like subroutines used by the integration algorithms
! It is recommended to replace them by calls to the optimized
!      BLAS/LAPACK library for your machine
!
!  (C) Adrian Sandu, Aug. 2004
!      Virginia Polytechnic Institute and State University
!--------------------------------------------------------------


!--------------------------------------------------------------
      SUBROUTINE WCOPY(N,X,incX,Y,incY)
!--------------------------------------------------------------
!     copies a vector, x, to a vector, y:  y <- x
!     only for incX=incY=1
!     after BLAS
!     replace this by the function from the optimized BLAS implementation:
!         CALL  SCOPY(N,X,1,Y,1)   or   CALL  DCOPY(N,X,1,Y,1)
!--------------------------------------------------------------
!     USE CRI_5VOC_Precision
      
      INTEGER  :: i,incX,incY,M,MP1,N
      REAL(kind=dp) :: X(N),Y(N)

      IF (N.LE.0) RETURN

      M = MOD(N,8)
      IF( M .NE. 0 ) THEN
        DO i = 1,M
          Y(i) = X(i)
        END DO
        IF( N .LT. 8 ) RETURN
      END IF    
      MP1 = M+1
      DO i = MP1,N,8
        Y(i) = X(i)
        Y(i + 1) = X(i + 1)
        Y(i + 2) = X(i + 2)
        Y(i + 3) = X(i + 3)
        Y(i + 4) = X(i + 4)
        Y(i + 5) = X(i + 5)
        Y(i + 6) = X(i + 6)
        Y(i + 7) = X(i + 7)
      END DO

      END SUBROUTINE WCOPY


!--------------------------------------------------------------
      SUBROUTINE WAXPY(N,Alpha,X,incX,Y,incY)
!--------------------------------------------------------------
!     constant times a vector plus a vector: y <- y + Alpha*x
!     only for incX=incY=1
!     after BLAS
!     replace this by the function from the optimized BLAS implementation:
!         CALL SAXPY(N,Alpha,X,1,Y,1) or  CALL DAXPY(N,Alpha,X,1,Y,1)
!--------------------------------------------------------------

      INTEGER  :: i,incX,incY,M,MP1,N
      REAL(kind=dp) :: X(N),Y(N),Alpha
      REAL(kind=dp), PARAMETER :: ZERO = 0.0_dp

      IF (Alpha .EQ. ZERO) RETURN
      IF (N .LE. 0) RETURN

      M = MOD(N,4)
      IF( M .NE. 0 ) THEN
        DO i = 1,M
          Y(i) = Y(i) + Alpha*X(i)
        END DO
        IF( N .LT. 4 ) RETURN
      END IF
      MP1 = M + 1
      DO i = MP1,N,4
        Y(i) = Y(i) + Alpha*X(i)
        Y(i + 1) = Y(i + 1) + Alpha*X(i + 1)
        Y(i + 2) = Y(i + 2) + Alpha*X(i + 2)
        Y(i + 3) = Y(i + 3) + Alpha*X(i + 3)
      END DO
      
      END SUBROUTINE WAXPY



!--------------------------------------------------------------
      SUBROUTINE WSCAL(N,Alpha,X,incX)
!--------------------------------------------------------------
!     constant times a vector: x(1:N) <- Alpha*x(1:N) 
!     only for incX=incY=1
!     after BLAS
!     replace this by the function from the optimized BLAS implementation:
!         CALL SSCAL(N,Alpha,X,1) or  CALL DSCAL(N,Alpha,X,1)
!--------------------------------------------------------------

      INTEGER  :: i,incX,M,MP1,N
      REAL(kind=dp)  :: X(N),Alpha
      REAL(kind=dp), PARAMETER  :: ZERO=0.0_dp, ONE=1.0_dp

      IF (Alpha .EQ. ONE) RETURN
      IF (N .LE. 0) RETURN

      M = MOD(N,5)
      IF( M .NE. 0 ) THEN
        IF (Alpha .EQ. (-ONE)) THEN
          DO i = 1,M
            X(i) = -X(i)
          END DO
        ELSEIF (Alpha .EQ. ZERO) THEN
          DO i = 1,M
            X(i) = ZERO
          END DO
        ELSE
          DO i = 1,M
            X(i) = Alpha*X(i)
          END DO
        END IF
        IF( N .LT. 5 ) RETURN
      END IF
      MP1 = M + 1
      IF (Alpha .EQ. (-ONE)) THEN
        DO i = MP1,N,5
          X(i)     = -X(i)
          X(i + 1) = -X(i + 1)
          X(i + 2) = -X(i + 2)
          X(i + 3) = -X(i + 3)
          X(i + 4) = -X(i + 4)
        END DO
      ELSEIF (Alpha .EQ. ZERO) THEN
        DO i = MP1,N,5
          X(i)     = ZERO
          X(i + 1) = ZERO
          X(i + 2) = ZERO
          X(i + 3) = ZERO
          X(i + 4) = ZERO
        END DO
      ELSE
        DO i = MP1,N,5
          X(i)     = Alpha*X(i)
          X(i + 1) = Alpha*X(i + 1)
          X(i + 2) = Alpha*X(i + 2)
          X(i + 3) = Alpha*X(i + 3)
          X(i + 4) = Alpha*X(i + 4)
        END DO
      END IF

      END SUBROUTINE WSCAL

!--------------------------------------------------------------
      REAL(kind=dp) FUNCTION WLAMCH( C )
!--------------------------------------------------------------
!     returns epsilon machine
!     after LAPACK
!     replace this by the function from the optimized LAPACK implementation:
!          CALL SLAMCH('E') or CALL DLAMCH('E')
!--------------------------------------------------------------
!      USE CRI_5VOC_Precision

      CHARACTER ::  C
      INTEGER    :: i
      REAL(kind=dp), SAVE  ::  Eps
      REAL(kind=dp)  ::  Suma
      REAL(kind=dp), PARAMETER  ::  ONE=1.0_dp, HALF=0.5_dp
      LOGICAL, SAVE   ::  First=.TRUE.
      
      IF (First) THEN
        First = .FALSE.
        Eps = HALF**(16)
        DO i = 17, 80
          Eps = Eps*HALF
          CALL WLAMCH_ADD(ONE,Eps,Suma)
          IF (Suma.LE.ONE) GOTO 10
        END DO
        PRINT*,'ERROR IN WLAMCH. EPS < ',Eps
        RETURN
10      Eps = Eps*2
        i = i-1      
      END IF

      WLAMCH = Eps

      END FUNCTION WLAMCH
     
      SUBROUTINE WLAMCH_ADD( A, B, Suma )
!      USE CRI_5VOC_Precision
      
      REAL(kind=dp) A, B, Suma
      Suma = A + B

      END SUBROUTINE WLAMCH_ADD
!--------------------------------------------------------------


!--------------------------------------------------------------
      SUBROUTINE SET2ZERO(N,Y)
!--------------------------------------------------------------
!     copies zeros into the vector y:  y <- 0
!     after BLAS
!--------------------------------------------------------------
      
      INTEGER ::  i,M,MP1,N
      REAL(kind=dp) ::  Y(N)
      REAL(kind=dp), PARAMETER :: ZERO = 0.0d0

      IF (N.LE.0) RETURN

      M = MOD(N,8)
      IF( M .NE. 0 ) THEN
        DO i = 1,M
          Y(i) = ZERO
        END DO
        IF( N .LT. 8 ) RETURN
      END IF    
      MP1 = M+1
      DO i = MP1,N,8
        Y(i)     = ZERO
        Y(i + 1) = ZERO
        Y(i + 2) = ZERO
        Y(i + 3) = ZERO
        Y(i + 4) = ZERO
        Y(i + 5) = ZERO
        Y(i + 6) = ZERO
        Y(i + 7) = ZERO
      END DO

      END SUBROUTINE SET2ZERO


!--------------------------------------------------------------
      REAL(kind=dp) FUNCTION WDOT (N, DX, incX, DY, incY) 
!--------------------------------------------------------------
!     dot produce: wdot = x(1:N)*y(1:N) 
!     only for incX=incY=1
!     after BLAS
!     replace this by the function from the optimized BLAS implementation:
!         CALL SDOT(N,X,1,Y,1) or  CALL DDOT(N,X,1,Y,1)
!--------------------------------------------------------------
!      USE messy_mecca_kpp_Precision
!--------------------------------------------------------------
      IMPLICIT NONE
      INTEGER :: N, incX, incY
      REAL(kind=dp) :: DX(N), DY(N) 

      INTEGER :: i, IX, IY, M, MP1, NS
                                 
      WDOT = 0.0D0 
      IF (N .LE. 0) RETURN 
      IF (incX .EQ. incY) IF (incX-1) 5,20,60 
!                                                                       
!     Code for unequal or nonpositive increments.                       
!                                                                       
    5 IX = 1 
      IY = 1 
      IF (incX .LT. 0) IX = (-N+1)*incX + 1 
      IF (incY .LT. 0) IY = (-N+1)*incY + 1 
      DO i = 1,N 
        WDOT = WDOT + DX(IX)*DY(IY) 
        IX = IX + incX 
        IY = IY + incY 
      END DO 
      RETURN 
!                                                                       
!     Code for both increments equal to 1.                              
!                                                                       
!     Clean-up loop so remaining vector length is a multiple of 5.      
!                                                                       
   20 M = MOD(N,5) 
      IF (M .EQ. 0) GO TO 40 
      DO i = 1,M 
         WDOT = WDOT + DX(i)*DY(i) 
      END DO 
      IF (N .LT. 5) RETURN 
   40 MP1 = M + 1 
      DO i = MP1,N,5 
          WDOT = WDOT + DX(i)*DY(i) + DX(i+1)*DY(i+1) + DX(i+2)*DY(i+2) +  &
                   DX(i+3)*DY(i+3) + DX(i+4)*DY(i+4)                   
      END DO 
      RETURN 
!                                                                       
!     Code for equal, positive, non-unit increments.                    
!                                                                       
   60 NS = N*incX 
      DO i = 1,NS,incX 
        WDOT = WDOT + DX(i)*DY(i) 
      END DO 

      END FUNCTION WDOT                                          


!--------------------------------------------------------------
      SUBROUTINE WADD(N,X,Y,Z)
!--------------------------------------------------------------
!     adds two vectors: z <- x + y
!     BLAS - like
!--------------------------------------------------------------
!     USE CRI_5VOC_Precision
      
      INTEGER :: i, M, MP1, N
      REAL(kind=dp) :: X(N),Y(N),Z(N)

      IF (N.LE.0) RETURN

      M = MOD(N,5)
      IF( M /= 0 ) THEN
         DO i = 1,M
            Z(i) = X(i) + Y(i)
         END DO
         IF( N < 5 ) RETURN
      END IF    
      MP1 = M+1
      DO i = MP1,N,5
         Z(i)     = X(i)     + Y(i)
         Z(i + 1) = X(i + 1) + Y(i + 1)
         Z(i + 2) = X(i + 2) + Y(i + 2)
         Z(i + 3) = X(i + 3) + Y(i + 3)
         Z(i + 4) = X(i + 4) + Y(i + 4)
      END DO

      END SUBROUTINE WADD
      
      
      
!--------------------------------------------------------------
      SUBROUTINE WGEFA(N,A,Ipvt,info)
!--------------------------------------------------------------
!     WGEFA FACTORS THE MATRIX A (N,N) BY
!           GAUSS ELIMINATION WITH PARTIAL PIVOTING
!     LINPACK - LIKE 
!--------------------------------------------------------------
!
      INTEGER       :: N,Ipvt(N),info
      REAL(kind=dp) :: A(N,N)
      REAL(kind=dp) :: t, dmax, da
      INTEGER       :: j,k,l
      REAL(kind=dp), PARAMETER :: ZERO = 0.0, ONE = 1.0

      info = 0

size: IF (n > 1) THEN
      
col:  DO k = 1, n-1

!        find l = pivot index
!        l = idamax(n-k+1,A(k,k),1) + k - 1
         l = k; dmax = abs(A(k,k))
         DO j = k+1,n
            da = ABS(A(j,k))
            IF (da > dmax) THEN
              l = j; dmax = da
            END IF
         END DO
         Ipvt(k) = l

!        zero pivot implies this column already triangularized
         IF (ABS(A(l,k)) < TINY(ZERO)) THEN
            info = k
            return
         ELSE   
            IF (l /= k) THEN
               t = A(l,k); A(l,k) = A(k,k); A(k,k) = t
            END IF
            t = -ONE/A(k,k)
            CALL WSCAL(n-k,t,A(k+1,k),1)
            DO j = k+1, n
               t = A(l,j)
               IF (l /= k) THEN
                  A(l,j) = A(k,j); A(k,j) = t
               END IF
               CALL WAXPY(n-k,t,A(k+1,k),1,A(k+1,j),1)
            END DO         
         END IF
         
       END DO col
       
      END IF size
      
      Ipvt(N) = N
      IF (ABS(A(N,N)) == ZERO) info = N
      
      END SUBROUTINE WGEFA


!--------------------------------------------------------------
      SUBROUTINE WGESL(Trans,N,A,Ipvt,b)
!--------------------------------------------------------------
!     WGESL solves the system
!     a * x = b  or  trans(a) * x = b
!     using the factors computed by WGEFA.
!
!     Trans      = 'N'   to solve  A*x = b ,
!                = 'T'   to solve  transpose(A)*x = b
!     LINPACK - LIKE 
!--------------------------------------------------------------

      INTEGER       :: N,Ipvt(N)
      CHARACTER     :: trans
      REAL(kind=dp) :: A(N,N),b(N)
      REAL(kind=dp) :: t
      INTEGER       :: k,kb,l

      
      SELECT CASE (Trans)

      CASE ('n','N')  !  Solve  A * x = b

!        first solve  L*y = b
         IF (n >= 2) THEN
          DO k = 1, n-1
            l = Ipvt(k)
            t = b(l)
            IF (l /= k) THEN
               b(l) = b(k)
               b(k) = t
            END IF
            CALL WAXPY(n-k,t,a(k+1,k),1,b(k+1),1)
          END DO
         END IF
!        now solve  U*x = y
         DO kb = 1, n
            k = n + 1 - kb
            b(k) = b(k)/a(k,k)
            t = -b(k)
            CALL WAXPY(k-1,t,a(1,k),1,b(1),1)
         END DO
      
      CASE ('t','T')  !  Solve transpose(A) * x = b

!        first solve  trans(U)*y = b
         DO k = 1, n
            t = WDOT(k-1,a(1,k),1,b(1),1)
            b(k) = (b(k) - t)/a(k,k)
         END DO
!        now solve trans(L)*x = y
         IF (n >= 2) THEN
         DO kb = 1, n-1
            k = n - kb
            b(k) = b(k) + WDOT(n-k,a(k+1,k),1,b(k+1),1)
            l = Ipvt(k)
            IF (l /= k) THEN
               t = b(l); b(l) = b(k); b(k) = t
            END IF
         END DO
         END IF
   
      END SELECT

      END SUBROUTINE WGESL
! End of BLAS_UTIL function
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



END MODULE CRI_5VOC_LinearAlgebra

